CREATE KEYSPACE IF NOT EXISTS mondial WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

USE mondial;



CREATE TABLE IF NOT EXISTS countrypops (

    country TEXT,

    year DECIMAL,

    population DECIMAL,

    PRIMARY KEY (country)

);



INSERT INTO countrypops (country, year, population) VALUES ('AL', 1950, 1214489);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 1960, 1618829);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 1970, 2138966);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 1980, 2734776);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 1990, 3446882);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 1997, 3249136);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 2000, 3304948);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 2001, 3069275);

INSERT INTO countrypops (country, year, population) VALUES ('AL', 2011, 2821977);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1861, 1096810);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1870, 1457894);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1879, 1679470);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1896, 2433806);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1907, 2631592);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1920, 5016889);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1928, 6204684);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1940, 7344860);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1951, 7632801);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1961, 8388553);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1971, 8768372);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1981, 9739589);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 1991, 10217335);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 2001, 10934097);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 2011, 10816286);

INSERT INTO countrypops (country, year, population) VALUES ('GR', 2021, 10432481);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1881, 186173);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1891, 209286);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1901, 237022);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1911, 274108);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1921, 310715);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1931, 347959);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1946, 450114);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1960, 573566);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1973, 631778);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1976, 612851);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1982, 512098);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 1992, 615013);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 2001, 703529);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 2011, 856857);

INSERT INTO countrypops (country, year, population) VALUES ('CY', 2021, 918100);

INSERT INTO countrypops (country, year, population) VALUES ('AD', 2020, 18195);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1921, 808724);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1931, 949958);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1948, 1152986);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1953, 1304514);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1961, 1406003);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1971, 1647308);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1981, 1909136);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1991, 2033964);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 1994, 1935034);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 2002, 2022547);

INSERT INTO countrypops (country, year, population) VALUES ('MK', 2021, 1836713);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 1950, 6732256);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 1960, 7657958);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 1970, 8236185);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 1980, 9057483);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 1991, 7576837);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 2002, 7498001);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 2011, 7186862);

INSERT INTO countrypops (country, year, population) VALUES ('SRB', 2021, 6690887);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1921, 311341);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1931, 360044);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1948, 377189);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1953, 419873);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1961, 471894);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1971, 529604);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1981, 584310);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 1991, 615035);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 2003, 620145);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 2011, 620029);

INSERT INTO countrypops (country, year, population) VALUES ('MNE', 2021, 619211);

INSERT INTO countrypops (country, year, population) VALUES ('KOS', 1981, 1584440);

INSERT INTO countrypops (country, year, population) VALUES ('KOS', 1991, 1956196);

INSERT INTO countrypops (country, year, population) VALUES ('KOS', 2011, 1733872);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 1950, 6197);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 1960, 13414);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 1970, 24279);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 1980, 36063);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 1989, 46166);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 2001, 66334);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 2011, 69772);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 2016, 73105);

INSERT INTO countrypops (country, year, population) VALUES ('AND', 2021, 79535);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1946, 40502513);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1954, 42777162);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1962, 46520271);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1968, 49778540);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1975, 52591584);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1982, 54334871);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1990, 56615155);

INSERT INTO countrypops (country, year, population) VALUES ('F', 1999, 58518395);

INSERT INTO countrypops (country, year, population) VALUES ('F', 2007, 61795238);

INSERT INTO countrypops (country, year, population) VALUES ('F', 2015, 64300821);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1900, 18618086);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1910, 19995686);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1920, 21389842);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1930, 23677794);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1940, 25877971);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1950, 27976755);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1960, 30528539);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1970, 34040657);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1981, 37682355);

INSERT INTO countrypops (country, year, population) VALUES ('E', 1991, 38872268);

INSERT INTO countrypops (country, year, population) VALUES ('E', 2001, 40847371);

INSERT INTO countrypops (country, year, population) VALUES ('E', 2011, 46815916);

INSERT INTO countrypops (country, year, population) VALUES ('E', 2021, 47400798);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 1950, 8876260);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 1960, 9577974);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 1970, 9827923);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 1980, 10313309);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 1991, 10302215);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 2001, 10230060);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 2011, 10436560);

INSERT INTO countrypops (country, year, population) VALUES ('CZ', 2021, 10524167);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 1960, 4137224);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 1970, 4531874);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 1980, 4988654);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 1990, 5277709);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 2000, 5388010);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 2001, 5379455);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 2011, 5397036);

INSERT INTO countrypops (country, year, population) VALUES ('SK', 2021, 5449270);

INSERT INTO countrypops (country, year, population) VALUES ('D', 1950, 68230796);

INSERT INTO countrypops (country, year, population) VALUES ('D', 1997, 82501000);

INSERT INTO countrypops (country, year, population) VALUES ('D', 2007, 82217837);

INSERT INTO countrypops (country, year, population) VALUES ('D', 2011, 80219695);

INSERT INTO countrypops (country, year, population) VALUES ('D', 2016, 82521653);

INSERT INTO countrypops (country, year, population) VALUES ('H', 1949, 9204799);

INSERT INTO countrypops (country, year, population) VALUES ('H', 1960, 9961044);

INSERT INTO countrypops (country, year, population) VALUES ('H', 1970, 10322099);

INSERT INTO countrypops (country, year, population) VALUES ('H', 1980, 10709463);

INSERT INTO countrypops (country, year, population) VALUES ('H', 1990, 10374823);

INSERT INTO countrypops (country, year, population) VALUES ('H', 2001, 10198315);

INSERT INTO countrypops (country, year, population) VALUES ('H', 2011, 9937628);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1861, 22182377);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1871, 27303509);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1881, 28953480);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1901, 32965504);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1911, 35845048);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1921, 39943528);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1931, 41651000);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1936, 42943602);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1951, 47515537);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1961, 50623569);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1971, 54136547);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1981, 56556911);

INSERT INTO countrypops (country, year, population) VALUES ('I', 1991, 56778031);

INSERT INTO countrypops (country, year, population) VALUES ('I', 2001, 56995744);

INSERT INTO countrypops (country, year, population) VALUES ('I', 2011, 59433744);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 1950, 4668088);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 1960, 5296120);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 1970, 6169357);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 1980, 6365960);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 1990, 6873687);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 2000, 7288010);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 2010, 7870134);

INSERT INTO countrypops (country, year, population) VALUES ('CH', 2020, 8670300);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 1950, 13757);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 1960, 16628);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 1970, 21350);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 1980, 25215);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 1990, 29032);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 2000, 33307);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 2010, 36149);

INSERT INTO countrypops (country, year, population) VALUES ('FL', 2020, 39055);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1869, 4497873);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1910, 6648310);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1934, 6760233);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1951, 6933905);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1961, 7073807);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1971, 7491526);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1981, 7555338);

INSERT INTO countrypops (country, year, population) VALUES ('A', 1991, 7795786);

INSERT INTO countrypops (country, year, population) VALUES ('A', 2001, 8032926);

INSERT INTO countrypops (country, year, population) VALUES ('A', 2011, 8401940);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1881, 881455);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1897, 958351);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1922, 1107059);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1934, 1126413);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1959, 1196791);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1970, 1356079);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1979, 1464476);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 1989, 1565662);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 2000, 1370052);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 2011, 1294455);

INSERT INTO countrypops (country, year, population) VALUES ('EST', 2021, 1331824);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1897, 1929387);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1920, 1596131);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1925, 1844805);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1930, 1900045);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1935, 1950502);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1959, 2093458);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1979, 2502816);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 1989, 2666567);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 2000, 2377383);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 2011, 2070371);

INSERT INTO countrypops (country, year, population) VALUES ('LV', 2013, 2201196);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 1950, 2567402);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 1959, 2696700);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 1970, 3118900);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 1979, 3391490);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 1989, 3674802);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 2001, 3483972);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 2011, 3043429);

INSERT INTO countrypops (country, year, population) VALUES ('LT', 2021, 2810761);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 1950, 7745003);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 1959, 8054648);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 1970, 9002338);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 1979, 9560543);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 1989, 10199709);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 1999, 10045237);

INSERT INTO countrypops (country, year, population) VALUES ('BY', 2009, 9503807);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 1946, 23929757);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 1950, 24613684);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 1960, 29405729);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 1970, 32749400);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 1978, 35061450);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 1988, 37878641);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 2002, 38230080);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 2011, 38511824);

INSERT INTO countrypops (country, year, population) VALUES ('PL', 2021, 38036118);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 1950, 37297652);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 1959, 41869046);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 1970, 47126517);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 1979, 49609333);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 1989, 51706742);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 2001, 48457102);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 2014, 45426249);

INSERT INTO countrypops (country, year, population) VALUES ('UA', 2021, 43999924);

INSERT INTO countrypops (country, year, population) VALUES ('R', 1950, 102798657);

INSERT INTO countrypops (country, year, population) VALUES ('R', 1960, 120057109);

INSERT INTO countrypops (country, year, population) VALUES ('R', 1970, 130357806);

INSERT INTO countrypops (country, year, population) VALUES ('R', 1979, 137550949);

INSERT INTO countrypops (country, year, population) VALUES ('R', 1989, 147400537);

INSERT INTO countrypops (country, year, population) VALUES ('R', 2002, 145166731);

INSERT INTO countrypops (country, year, population) VALUES ('R', 2010, 142856536);

INSERT INTO countrypops (country, year, population) VALUES ('R', 2021, 144699673);

INSERT INTO countrypops (country, year, population) VALUES ('B', 1947, 8879814);

INSERT INTO countrypops (country, year, population) VALUES ('B', 1961, 9189741);

INSERT INTO countrypops (country, year, population) VALUES ('B', 1970, 9650944);

INSERT INTO countrypops (country, year, population) VALUES ('B', 1981, 9963374);

INSERT INTO countrypops (country, year, population) VALUES ('B', 1990, 9947782);

INSERT INTO countrypops (country, year, population) VALUES ('B', 2000, 10239085);

INSERT INTO countrypops (country, year, population) VALUES ('B', 2010, 10839905);

INSERT INTO countrypops (country, year, population) VALUES ('B', 2020, 11492641);

INSERT INTO countrypops (country, year, population) VALUES ('L', 1947, 290992);

INSERT INTO countrypops (country, year, population) VALUES ('L', 1960, 314889);

INSERT INTO countrypops (country, year, population) VALUES ('L', 1966, 334790);

INSERT INTO countrypops (country, year, population) VALUES ('L', 1970, 339841);

INSERT INTO countrypops (country, year, population) VALUES ('L', 1981, 364602);

INSERT INTO countrypops (country, year, population) VALUES ('L', 1991, 384634);

INSERT INTO countrypops (country, year, population) VALUES ('L', 2000, 435479);

INSERT INTO countrypops (country, year, population) VALUES ('L', 2001, 439539);

INSERT INTO countrypops (country, year, population) VALUES ('L', 2011, 512353);

INSERT INTO countrypops (country, year, population) VALUES ('L', 2022, 645397);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1795, 2078487);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1815, 2202191);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1830, 2613487);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1840, 2860559);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1849, 3056879);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1859, 3309128);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1869, 3579529);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1879, 4012693);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1889, 4511415);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1899, 5104137);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1909, 5858175);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1920, 6865314);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1930, 7935565);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1947, 9625499);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1960, 11461964);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 1971, 13060115);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 2002, 16105285);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 2010, 16577516);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 2014, 16843181);

INSERT INTO countrypops (country, year, population) VALUES ('NL', 2022, 17590672);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1857, 1101854);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1869, 1128768);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1880, 1182223);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1890, 1234056);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1900, 1268055);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1910, 1321098);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1921, 1054919);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1931, 1144298);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1948, 1391873);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1953, 1466425);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1961, 1591523);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1971, 1727137);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1981, 1891864);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 1991, 1913355);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 2002, 1964036);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 2011, 2050189);

INSERT INTO countrypops (country, year, population) VALUES ('SLO', 2021, 2108977);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 1950, 3850295);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 1960, 4059048);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 1970, 4171014);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 1971, 4426221);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 1981, 4601469);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 1991, 4784265);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 2001, 4437460);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 2011, 4284889);

INSERT INTO countrypops (country, year, population) VALUES ('HR', 2021, 3871833);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 1948, 2565277);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 1953, 2847790);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 1961, 3277948);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 1971, 3746111);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 1981, 4124256);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 1991, 4377033);

INSERT INTO countrypops (country, year, population) VALUES ('BIH', 2013, 3791622);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1887, 3154375);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1892, 3310713);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1900, 3744283);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1905, 4035575);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1910, 4337513);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1920, 4846971);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1926, 5528741);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1934, 6077939);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1946, 7029349);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1956, 7613709);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1965, 8227866);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1975, 8727771);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1985, 8948649);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 1992, 8487317);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 2001, 7932984);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 2011, 7351234);

INSERT INTO countrypops (country, year, population) VALUES ('BG', 2021, 6520314);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 1948, 15872624);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 1956, 17489450);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 1966, 19103163);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 1977, 21559910);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 1992, 22810035);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 2002, 21680974);

INSERT INTO countrypops (country, year, population) VALUES ('RO', 2011, 20121641);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1950, 4281275);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1955, 4448401);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1960, 4585256);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1965, 4767597);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1970, 4937579);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1981, 5123989);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 1991, 5146469);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 2001, 5349212);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 2006, 5427459);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 2010, 5534738);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 2012, 5580516);

INSERT INTO countrypops (country, year, population) VALUES ('DK', 2015, 5678348);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1901, 78470);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1910, 85183);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1920, 94690);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1930, 108861);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1940, 121474);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1950, 143973);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1960, 175680);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1970, 204578);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1980, 229187);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 1990, 255708);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 2000, 282849);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 2005, 293577);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 2010, 317630);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 2015, 329100);

INSERT INTO countrypops (country, year, population) VALUES ('IS', 2020, 364134);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 1950, 31781);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 1955, 32456);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 1960, 34596);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 1966, 37122);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 1970, 38612);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 1977, 41969);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 2009, 48668);

INSERT INTO countrypops (country, year, population) VALUES ('FO', 2011, 48346);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1901, 3221823);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1911, 3139688);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1926, 2971992);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1936, 2968420);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1946, 2955107);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1951, 2960593);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1956, 2898264);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1961, 2818341);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1966, 2884002);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1971, 2978248);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1979, 3368217);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1981, 3443405);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1986, 3540643);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1991, 3525719);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 1996, 3626087);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 2002, 3917203);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 2006, 4239848);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 2011, 4588252);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 2016, 4761865);

INSERT INTO countrypops (country, year, population) VALUES ('IRL', 2021, 5123536);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 1950, 4008299);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 1960, 4430228);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 1970, 4606740);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 1980, 4779454);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 1990, 4998478);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 2000, 5181115);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 2010, 5375276);

INSERT INTO countrypops (country, year, population) VALUES ('SF', 2017, 5513130);

INSERT INTO countrypops (country, year, population) VALUES ('N', 1950, 3265278);

INSERT INTO countrypops (country, year, population) VALUES ('N', 1960, 3582016);

INSERT INTO countrypops (country, year, population) VALUES ('N', 1970, 3875719);

INSERT INTO countrypops (country, year, population) VALUES ('N', 1980, 4082525);

INSERT INTO countrypops (country, year, population) VALUES ('N', 1990, 4240375);

INSERT INTO countrypops (country, year, population) VALUES ('N', 2001, 4520947);

INSERT INTO countrypops (country, year, population) VALUES ('N', 2011, 4920305);

INSERT INTO countrypops (country, year, population) VALUES ('N', 2013, 5051275);

INSERT INTO countrypops (country, year, population) VALUES ('S', 1950, 7009913);

INSERT INTO countrypops (country, year, population) VALUES ('S', 1960, 7479602);

INSERT INTO countrypops (country, year, population) VALUES ('S', 1970, 8049049);

INSERT INTO countrypops (country, year, population) VALUES ('S', 1980, 8310915);

INSERT INTO countrypops (country, year, population) VALUES ('S', 1990, 8559107);

INSERT INTO countrypops (country, year, population) VALUES ('S', 1997, 8900954);

INSERT INTO countrypops (country, year, population) VALUES ('S', 2000, 8872284);

INSERT INTO countrypops (country, year, population) VALUES ('S', 2004, 9011392);

INSERT INTO countrypops (country, year, population) VALUES ('S', 2009, 9340682);

INSERT INTO countrypops (country, year, population) VALUES ('S', 2012, 9555893);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1950, 20000);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1951, 20202);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1956, 20422);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1961, 22297);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1962, 21783);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1968, 23035);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1975, 25029);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1982, 27063);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 1990, 29972);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 2000, 32020);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 2008, 31109);

INSERT INTO countrypops (country, year, population) VALUES ('MC', 2016, 37308);

INSERT INTO countrypops (country, year, population) VALUES ('V', 1931, 994);

INSERT INTO countrypops (country, year, population) VALUES ('V', 1997, 840);

INSERT INTO countrypops (country, year, population) VALUES ('V', 2014, 842);

INSERT INTO countrypops (country, year, population) VALUES ('V', 2018, 826);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 1960, 73182);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 1970, 67187);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 1981, 65264);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 1991, 67615);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 2001, 71505);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 2011, 83517);

INSERT INTO countrypops (country, year, population) VALUES ('CEU', 2021, 84071);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 1960, 79056);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 1970, 64642);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 1981, 53593);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 1991, 56600);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 2001, 66411);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 2011, 81323);

INSERT INTO countrypops (country, year, population) VALUES ('MEL', 2021, 86450);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 1950, 12781);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 1960, 15393);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 1970, 19136);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 1976, 19149);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 1997, 24521);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 2000, 26941);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 2010, 31887);

INSERT INTO countrypops (country, year, population) VALUES ('RSM', 2020, 33627);

INSERT INTO countrypops (country, year, population) VALUES ('M', 1948, 305991);

INSERT INTO countrypops (country, year, population) VALUES ('M', 1957, 319620);

INSERT INTO countrypops (country, year, population) VALUES ('M', 1967, 314216);

INSERT INTO countrypops (country, year, population) VALUES ('M', 1985, 345418);

INSERT INTO countrypops (country, year, population) VALUES ('M', 1995, 378132);

INSERT INTO countrypops (country, year, population) VALUES ('M', 2005, 404962);

INSERT INTO countrypops (country, year, population) VALUES ('M', 2011, 417432);

INSERT INTO countrypops (country, year, population) VALUES ('M', 2021, 519562);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1950, 55253);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1951, 54024);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1961, 47166);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1966, 49312);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1971, 53228);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1976, 60496);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1981, 64679);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1986, 64282);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1991, 69788);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 1996, 71714);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 2001, 76315);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 2006, 80058);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 2011, 84497);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 2016, 83314);

INSERT INTO countrypops (country, year, population) VALUES ('GBM', 2021, 84069);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 1950, 2341003);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 1959, 2513483);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 1970, 3085080);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 1979, 3372051);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 1989, 3657665);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 2004, 3383332);

INSERT INTO countrypops (country, year, population) VALUES ('MD', 2012, 3473900);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1864, 3829618);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1878, 4550699);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1890, 5049729);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1900, 5423132);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1911, 5960056);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1920, 6032991);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1930, 6825883);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1940, 7755423);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1950, 8510240);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1960, 8889392);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1970, 8611125);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1981, 9833014);

INSERT INTO countrypops (country, year, population) VALUES ('P', 1991, 9862540);

INSERT INTO countrypops (country, year, population) VALUES ('P', 2001, 10356117);

INSERT INTO countrypops (country, year, population) VALUES ('P', 2011, 10562178);

INSERT INTO countrypops (country, year, population) VALUES ('P', 2021, 10343066);

INSERT INTO countrypops (country, year, population) VALUES ('SVA', 1987, 2116);

INSERT INTO countrypops (country, year, population) VALUES ('SVA', 2016, 2667);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 1950, 50616012);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 1960, 52544326);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 1970, 55645296);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 1980, 56302877);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 1990, 57214478);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 1991, 54888844);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 2001, 58789194);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 2011, 63182178);

INSERT INTO countrypops (country, year, population) VALUES ('GB', 2021, 66980000);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1753, 1816);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1767, 2710);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1777, 3201);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1787, 3386);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1791, 2890);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1814, 10136);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1834, 15002);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1844, 15823);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1871, 18695);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1878, 18014);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1881, 18381);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1891, 19100);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1901, 20355);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1911, 19120);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1921, 18061);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1931, 17405);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1951, 20845);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1961, 23926);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1970, 26818);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1981, 28719);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 1991, 28074);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 2001, 28240);

INSERT INTO countrypops (country, year, population) VALUES ('GBZ', 2012, 32577);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1951, 43652);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1961, 45068);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1971, 51458);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1976, 53637);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1981, 55950);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1991, 61700);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 1996, 61378);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 2001, 62692);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 2016, 65200);

INSERT INTO countrypops (country, year, population) VALUES ('GBG', 2021, 66150);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1821, 28600);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1831, 36582);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1841, 47544);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1851, 57020);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1861, 55613);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1871, 56627);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1881, 52445);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1891, 54518);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1901, 52576);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1911, 51898);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1921, 49701);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1931, 50462);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1939, 51080);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1951, 57310);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1961, 59489);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1971, 69329);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1976, 71018);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1981, 76050);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1986, 80212);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1989, 82809);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1991, 84082);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 1996, 85150);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 2001, 87186);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 2011, 97857);

INSERT INTO countrypops (country, year, population) VALUES ('GBJ', 2021, 103267);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 1926, 881300);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 1939, 1282300);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 1959, 1763048);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 1970, 2491900);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 1979, 3037259);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 1989, 3304776);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 2001, 3213011);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 2011, 3018854);

INSERT INTO countrypops (country, year, population) VALUES ('ARM', 2013, 3026879);

INSERT INTO countrypops (country, year, population) VALUES ('GE', 1950, 3527004);

INSERT INTO countrypops (country, year, population) VALUES ('GE', 1959, 4044045);

INSERT INTO countrypops (country, year, population) VALUES ('GE', 1979, 4993182);

INSERT INTO countrypops (country, year, population) VALUES ('GE', 1989, 5400841);

INSERT INTO countrypops (country, year, population) VALUES ('GE', 2002, 4650000);

INSERT INTO countrypops (country, year, population) VALUES ('GE', 2014, 4010000);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1897, 1806700);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1926, 2313700);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1939, 3205200);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1959, 3697717);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1970, 5117100);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1979, 6026515);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1989, 7021178);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 1999, 7953438);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 2009, 8922447);

INSERT INTO countrypops (country, year, population) VALUES ('AZ', 2013, 9356500);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1927, 13648270);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1935, 16158018);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1940, 17820950);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1945, 18790174);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1950, 20947188);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1955, 24064763);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1960, 27754820);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1965, 31391421);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1970, 35605176);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1975, 40347719);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1980, 44736957);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1985, 50664458);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 1990, 56473035);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 2000, 67803927);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 2011, 74525696);

INSERT INTO countrypops (country, year, population) VALUES ('TR', 2021, 84680273);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 1950, 1334618);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 1960, 1804927);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 1970, 2126325);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 1996, 3111829);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 2007, 3759136);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 2011, 4036450);

INSERT INTO countrypops (country, year, population) VALUES ('RL', 2017, 5416225);

INSERT INTO countrypops (country, year, population) VALUES ('WB', 1997, 1873476);

INSERT INTO countrypops (country, year, population) VALUES ('WB', 2007, 2350583);

INSERT INTO countrypops (country, year, population) VALUES ('WB', 2017, 2881687);

INSERT INTO countrypops (country, year, population) VALUES ('GAZA', 1997, 1022207);

INSERT INTO countrypops (country, year, population) VALUES ('GAZA', 2007, 1416963);

INSERT INTO countrypops (country, year, population) VALUES ('GAZA', 2017, 1899291);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 1950, 1257971);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 1960, 2089891);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 1961, 2179491);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 1972, 3147683);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 1983, 4037620);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 1995, 5548523);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 2008, 7412200);

INSERT INTO countrypops (country, year, population) VALUES ('IL', 2019, 9140500);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 1950, 3413329);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 1960, 4565121);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 1970, 6304685);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 1981, 9046144);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 1994, 13782315);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 2004, 17920844);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 2010, 21018834);

INSERT INTO countrypops (country, year, population) VALUES ('SYR', 2019, 17070135);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 1950, 448861);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 1960, 888632);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 1961, 1706226);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 1979, 2100019);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 1994, 4139458);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 2004, 5103639);

INSERT INTO countrypops (country, year, population) VALUES ('JOR', 2015, 9131712);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1950, 3121336);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1960, 4072110);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1970, 5802967);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1980, 9843265);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1990, 16206078);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1992, 16948388);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 1997, 19409058);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 2004, 22678262);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 2010, 27136977);

INSERT INTO countrypops (country, year, population) VALUES ('SA', 2018, 33413660);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1941, 89970);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1950, 109650);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1959, 143135);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1965, 182203);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1971, 216078);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1981, 350798);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 1991, 508037);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 2001, 650604);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 2010, 1234571);

INSERT INTO countrypops (country, year, population) VALUES ('BRN', 2020, 1501635);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 1950, 24999);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 1960, 47316);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 1970, 111133);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 1986, 369079);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 1997, 522023);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 2004, 744029);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 2010, 1699435);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 2015, 2404776);

INSERT INTO countrypops (country, year, population) VALUES ('Q', 2020, 2846118);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1950, 69590);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1960, 89608);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1968, 180226);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1975, 557887);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1980, 1042099);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1985, 1379303);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 1995, 2411041);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 2005, 4106427);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 2010, 8264070);

INSERT INTO countrypops (country, year, population) VALUES ('UAE', 2016, 9121167);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1950, 456418);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1960, 551737);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1970, 723850);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1980, 1154375);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1990, 1810103);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1993, 2018074);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 1997, 2186548);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 2003, 2340815);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 2010, 2773479);

INSERT INTO countrypops (country, year, population) VALUES ('OM', 2020, 4471148);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 1950, 4661279);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 1960, 5099785);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 1970, 6096574);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 1980, 7906977);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 1990, 11790249);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 1994, 14587807);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 2004, 19684603);

INSERT INTO countrypops (country, year, population) VALUES ('YE', 2012, 24527000);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1950, 152249);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1957, 190794);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1961, 303874);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1965, 467339);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1970, 738663);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1975, 994837);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1980, 1357952);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1985, 1697301);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 1995, 1575570);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 2000, 2193651);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 2015, 3743660);

INSERT INTO countrypops (country, year, population) VALUES ('KWT', 2020, 4464521);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 1950, 5719191);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 1957, 6339960);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 1965, 8047415);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 1977, 12000497);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 1987, 16335199);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 1997, 22046244);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 2003, 25897848);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 2011, 33330512);

INSERT INTO countrypops (country, year, population) VALUES ('IRQ', 2018, 38124182);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1950, 17119263);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1956, 18954704);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1966, 25078923);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1976, 33708744);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1986, 49445010);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1991, 55837163);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 1996, 60055488);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 2006, 70495782);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 2011, 75149669);

INSERT INTO countrypops (country, year, population) VALUES ('IR', 2016, 79926270);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 1950, 7450738);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 1960, 8774440);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 1970, 11015621);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 1979, 13051358);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 2006, 22575900);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 2013, 26023100);

INSERT INTO countrypops (country, year, population) VALUES ('AFG', 2020, 31390200);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 1950, 1211000);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 1959, 1516375);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 1979, 2764748);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 1989, 3522717);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 1995, 4993500);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 2005, 6550000);

INSERT INTO countrypops (country, year, population) VALUES ('TM', 2020, 6031187);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 1950, 6313997);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 1960, 8558503);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 1970, 11972994);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 1979, 15390836);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 1989, 19906000);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 1997, 23418381);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 2000, 24828562);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 2010, 27769270);

INSERT INTO countrypops (country, year, population) VALUES ('UZ', 2017, 32120500);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 1939, 1485000);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 1959, 1981000);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 1970, 2898000);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 1979, 3806220);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 1989, 5092603);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 2000, 6127493);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 2010, 7564502);

INSERT INTO countrypops (country, year, population) VALUES ('TJ', 2020, 9313800);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 1950, 1740000);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 1959, 2065837);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 1979, 3522832);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 1989, 4257755);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 1999, 4850734);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 2009, 5107640);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 2014, 5776600);

INSERT INTO countrypops (country, year, population) VALUES ('KG', 2018, 6256700);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 1950, 6702996);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 1959, 9303801);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 1970, 13026274);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 1979, 14709508);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 1989, 16232324);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 1999, 14981281);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 2009, 16009597);

INSERT INTO countrypops (country, year, population) VALUES ('KZ', 2014, 17165239);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1935, 738200);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1944, 759061);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1956, 845481);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1963, 1017158);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1969, 1197595);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1979, 1595006);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 1989, 2044000);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 2000, 2373493);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 2010, 2647545);

INSERT INTO countrypops (country, year, population) VALUES ('MNG', 2020, 3197020);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1950, 73716);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1960, 88960);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1965, 97743);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1967, 103801);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1974, 128697);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1977, 142832);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1985, 180088);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1990, 213215);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 1995, 244814);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 2000, 270101);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 2006, 298968);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 2010, 325694);

INSERT INTO countrypops (country, year, population) VALUES ('MV', 2014, 402071);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 1950, 37542380);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 1951, 31883037);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 1961, 46116934);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 1972, 65309000);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 1981, 84525300);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 1998, 132352279);

INSERT INTO countrypops (country, year, population) VALUES ('PK', 2017, 207776954);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1901, 238396327);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1911, 252093390);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1921, 251321213);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1931, 278977238);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1941, 318660580);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1951, 361088090);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1961, 439234771);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1971, 548159652);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1981, 683329097);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 1991, 843387888);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 2001, 1028610328);

INSERT INTO countrypops (country, year, population) VALUES ('IND', 2011, 1210854977);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1911, 5638749);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1920, 5573788);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1930, 5532574);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1941, 6283649);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1954, 8256625);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1961, 9412996);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1971, 11555983);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1981, 15022839);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 1991, 18489097);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 2001, 23151423);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 2011, 26494504);

INSERT INTO countrypops (country, year, population) VALUES ('NEP', 2021, 29192480);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 1950, 176795);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 1960, 224155);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 1970, 291555);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 1980, 412745);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 1990, 535738);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 2000, 564350);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 2005, 634982);

INSERT INTO countrypops (country, year, population) VALUES ('BHT', 2017, 727145);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1901, 28927786);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1911, 31555056);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1921, 33254096);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1931, 35604170);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1941, 41997297);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1951, 44165740);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1961, 55222663);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1974, 76398000);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1981, 89912000);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 1991, 106314992);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 2001, 124355263);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 2011, 144043697);

INSERT INTO countrypops (country, year, population) VALUES ('BD', 2022, 165158616);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1891, 7722053);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1901, 10490624);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1911, 12115217);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1921, 13212000);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1931, 14667000);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1941, 16823798);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1973, 28084513);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1983, 34124908);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 1997, 45975625);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 2002, 52171000);

INSERT INTO countrypops (country, year, population) VALUES ('MYA', 2014, 51419420);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1871, 2400380);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1881, 2759738);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1891, 3007789);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1901, 3565954);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1911, 4106350);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1921, 4497854);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1931, 5306863);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1946, 6657339);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1953, 8097845);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1963, 10582064);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1971, 12689897);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 1981, 14846750);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 2001, 18797257);

INSERT INTO countrypops (country, year, population) VALUES ('CL', 2012, 20359439);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 1950, 543776080);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 1960, 650680114);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 1970, 814377714);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 1982, 1008175288);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 1990, 1130822993);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 2000, 1242612226);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 2010, 1339724852);

INSERT INTO countrypops (country, year, population) VALUES ('CN', 2020, 1411778724);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1950, 7561863);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1956, 9367661);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1966, 13305463);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1970, 14769702);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1975, 16279356);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1980, 18029798);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 1990, 20393628);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 2000, 22300929);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 2006, 22876527);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 2012, 23315822);

INSERT INTO countrypops (country, year, population) VALUES ('RC', 2017, 23571227);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1901, 283205);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1911, 456739);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1921, 625166);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1931, 849751);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1961, 3133131);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1971, 3936630);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1981, 4986560);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 1991, 5522281);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 2001, 6708389);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 2011, 7071576);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 2016, 7336585);

INSERT INTO countrypops (country, year, population) VALUES ('HK', 2021, 7413070);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 1950, 187772);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 1960, 169299);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 1970, 248636);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 1981, 261680);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 1991, 355693);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 2001, 435235);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 2011, 552503);

INSERT INTO countrypops (country, year, population) VALUES ('MAC', 2021, 682070);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 1925, 6014099);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 1930, 6537303);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 1940, 7920279);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 1944, 8554857);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 1993, 20522351);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 2008, 23349859);

INSERT INTO countrypops (country, year, population) VALUES ('KP', 2010, 24500520);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1949, 20166756);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1955, 21502386);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1960, 24989241);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1966, 29159640);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1970, 31435252);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1975, 34678972);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1980, 37406815);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1985, 40419652);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1990, 43390374);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 1995, 44553710);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 2000, 46136101);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 2010, 48219172);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 2015, 51269554);

INSERT INTO countrypops (country, year, population) VALUES ('ROK', 2020, 51780579);

INSERT INTO countrypops (country, year, population) VALUES ('J', 1950, 82199470);

INSERT INTO countrypops (country, year, population) VALUES ('J', 1960, 92500754);

INSERT INTO countrypops (country, year, population) VALUES ('J', 1970, 103707537);

INSERT INTO countrypops (country, year, population) VALUES ('J', 1980, 115912104);

INSERT INTO countrypops (country, year, population) VALUES ('J', 1990, 122249285);

INSERT INTO countrypops (country, year, population) VALUES ('J', 2000, 125714674);

INSERT INTO countrypops (country, year, population) VALUES ('J', 2005, 127767994);

INSERT INTO countrypops (country, year, population) VALUES ('J', 2010, 128057352);

INSERT INTO countrypops (country, year, population) VALUES ('J', 2015, 127094745);

INSERT INTO countrypops (country, year, population) VALUES ('J', 2020, 126146099);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1799, 1502574);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1800, 1561251);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1812, 1933331);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1819, 2106230);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1829, 2593287);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1840, 3096031);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1850, 3857424);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1858, 4290381);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1870, 4712006);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1877, 5567685);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1887, 5984727);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1896, 6261339);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1903, 7635426);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1918, 10314310);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1939, 16000303);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1948, 19234182);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1960, 27087685);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1970, 36684486);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1975, 42070660);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1980, 48098460);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1990, 60703810);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 1995, 68616536);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 2000, 76506928);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 2010, 92337852);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 2015, 100981437);

INSERT INTO countrypops (country, year, population) VALUES ('RP', 2020, 109035343);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 1950, 24949467);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 1960, 32912298);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 1970, 43782542);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 1980, 54897387);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 1990, 68909883);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 1999, 76327900);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 2009, 85846997);

INSERT INTO countrypops (country, year, population) VALUES ('VN', 2019, 96208984);

INSERT INTO countrypops (country, year, population) VALUES ('K', 1950, 4432716);

INSERT INTO countrypops (country, year, population) VALUES ('K', 1960, 5720019);

INSERT INTO countrypops (country, year, population) VALUES ('K', 1962, 5728771);

INSERT INTO countrypops (country, year, population) VALUES ('K', 1998, 11437656);

INSERT INTO countrypops (country, year, population) VALUES ('K', 2008, 13395682);

INSERT INTO countrypops (country, year, population) VALUES ('K', 2019, 15288489);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 1950, 1682917);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 1960, 2119731);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 1970, 2685174);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 1980, 3250924);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 1985, 3570000);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 1995, 4581258);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 2005, 5621982);

INSERT INTO countrypops (country, year, population) VALUES ('LAO', 2015, 6492228);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1909, 8149487);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1919, 9207355);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1929, 11506207);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1937, 14464105);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1947, 17442689);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1956, 20095130);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1960, 26257916);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1970, 34397374);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1980, 44824540);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 1990, 54548530);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 2000, 60916441);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 2010, 65981659);

INSERT INTO countrypops (country, year, population) VALUES ('THA', 2019, 67993000);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 1950, 6109907);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 1960, 8160975);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 1970, 10623732);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 1980, 13136109);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 1991, 18379655);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 2000, 23274690);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 2010, 28334135);

INSERT INTO countrypops (country, year, population) VALUES ('MAL', 2020, 32447385);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 1950, 48001);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 1960, 81817);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 1970, 129719);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 1971, 136256);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 1981, 192832);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 1991, 260482);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 2001, 332844);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 2011, 393372);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 2016, 417256);

INSERT INTO countrypops (country, year, population) VALUES ('BRU', 2021, 440715);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 1950, 1022098);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 1957, 1445929);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 1970, 2074507);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 1980, 2413945);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 1990, 3047100);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 2000, 4027900);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 2010, 5076700);

INSERT INTO countrypops (country, year, population) VALUES ('SGP', 2020, 5685807);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 1950, 72592192);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 1960, 88692697);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 1961, 97100000);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 1971, 119208229);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 1980, 147490298);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 1990, 179378946);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 2000, 205132458);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 2010, 237641326);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 2015, 255182144);

INSERT INTO countrypops (country, year, population) VALUES ('RI', 2020, 270203917);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 1950, 433398);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 1960, 499681);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 1970, 604392);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 1980, 555350);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 1990, 747557);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 2001, 787340);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 2004, 923198);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 2010, 1066582);

INSERT INTO countrypops (country, year, population) VALUES ('TL', 2015, 1183643);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 1950, 1708192);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 1960, 1966957);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 1966, 2184986);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 1971, 2489936);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 1980, 3010727);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 1990, 3761954);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 2000, 5190786);

INSERT INTO countrypops (country, year, population) VALUES ('PNG', 2011, 7275324);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 1950, 89793);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 1959, 124076);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 1970, 160998);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 1976, 196823);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 1986, 285176);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 1999, 409042);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 2009, 551525);

INSERT INTO countrypops (country, year, population) VALUES ('SOL', 2019, 721455);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 1950, 47695);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 1960, 63701);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 1970, 85388);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 1980, 115634);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 1989, 142419);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 1999, 186678);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 2009, 234023);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 2016, 272459);

INSERT INTO countrypops (country, year, population) VALUES ('VU', 2020, 300019);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1956, 68480);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1963, 86519);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1969, 100579);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1976, 133233);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1983, 145368);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1989, 164173);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 1996, 196836);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 2004, 230789);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 2009, 245580);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 2014, 268767);

INSERT INTO countrypops (country, year, population) VALUES ('NCL', 2019, 271407);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1881, 2250194);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1891, 3174392);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1901, 3773801);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1911, 4455005);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1921, 5435734);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1933, 6629839);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1947, 7579358);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1954, 8986530);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1961, 10508186);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1966, 11550462);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1971, 12755638);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1976, 13548448);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1981, 14576328);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1986, 15602156);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1991, 17284036);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 1996, 17752829);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 2001, 18769249);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 2006, 19855288);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 2011, 21507719);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 2016, 23401892);

INSERT INTO countrypops (country, year, population) VALUES ('AUS', 2021, 25422788);

INSERT INTO countrypops (country, year, population) VALUES ('CX', 1996, 1832);

INSERT INTO countrypops (country, year, population) VALUES ('CX', 2001, 1402);

INSERT INTO countrypops (country, year, population) VALUES ('CX', 2006, 1347);

INSERT INTO countrypops (country, year, population) VALUES ('CX', 2011, 2072);

INSERT INTO countrypops (country, year, population) VALUES ('CX', 2016, 1843);

INSERT INTO countrypops (country, year, population) VALUES ('CX', 2021, 1692);

INSERT INTO countrypops (country, year, population) VALUES ('CC', 1996, 592);

INSERT INTO countrypops (country, year, population) VALUES ('CC', 2001, 596);

INSERT INTO countrypops (country, year, population) VALUES ('CC', 2006, 571);

INSERT INTO countrypops (country, year, population) VALUES ('CC', 2011, 550);

INSERT INTO countrypops (country, year, population) VALUES ('CC', 2016, 544);

INSERT INTO countrypops (country, year, population) VALUES ('CC', 2021, 593);

INSERT INTO countrypops (country, year, population) VALUES ('NF', 1996, 1772);

INSERT INTO countrypops (country, year, population) VALUES ('NF', 2001, 2037);

INSERT INTO countrypops (country, year, population) VALUES ('NF', 2006, 1863);

INSERT INTO countrypops (country, year, population) VALUES ('NF', 2011, 1795);

INSERT INTO countrypops (country, year, population) VALUES ('NF', 2016, 1748);

INSERT INTO countrypops (country, year, population) VALUES ('NF', 2021, 2188);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1901, 815862);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1906, 936309);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1911, 1058312);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1916, 1149225);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1921, 1271667);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1926, 1408140);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1936, 1573812);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1945, 1702299);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1951, 1939473);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1956, 2174061);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1961, 2414985);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1966, 2676918);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1971, 2862630);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1976, 3129384);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1981, 3175737);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1986, 3307083);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1991, 3434949);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 1996, 3681546);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 2001, 3737280);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 2006, 4027947);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 2013, 4242048);

INSERT INTO countrypops (country, year, population) VALUES ('NZ', 2018, 4699755);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1950, 7441);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1958, 9344);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1967, 11365);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1973, 12673);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1980, 12116);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1986, 13873);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1990, 15122);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 1995, 17225);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 2000, 19129);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 2005, 19907);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 2015, 17661);

INSERT INTO countrypops (country, year, population) VALUES ('PAL', 2020, 17614);

INSERT INTO countrypops (country, year, population) VALUES ('MP', 1970, 9640);

INSERT INTO countrypops (country, year, population) VALUES ('MP', 1980, 16780);

INSERT INTO countrypops (country, year, population) VALUES ('MP', 1990, 43345);

INSERT INTO countrypops (country, year, population) VALUES ('MP', 2000, 69221);

INSERT INTO countrypops (country, year, population) VALUES ('MP', 2010, 53883);

INSERT INTO countrypops (country, year, population) VALUES ('MP', 2020, 47329);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 1950, 59498);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 1960, 67044);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 1970, 84996);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 1980, 105979);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 1990, 133152);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 2000, 154805);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 2010, 159358);

INSERT INTO countrypops (country, year, population) VALUES ('GU', 2020, 153836);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1920, 29660);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1925, 29810);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1930, 29727);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1935, 29920);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1958, 39289);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1967, 50172);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1973, 62357);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1980, 73159);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1989, 95740);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 1994, 105506);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 2000, 107008);

INSERT INTO countrypops (country, year, population) VALUES ('FSM', 2010, 102843);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1920, 9800);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1925, 9644);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1930, 10412);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1935, 10446);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1958, 13928);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1967, 18925);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1980, 30873);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1988, 43380);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 1999, 50840);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 2011, 53158);

INSERT INTO countrypops (country, year, population) VALUES ('MH', 2021, 42594);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1921, 2066);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1933, 2641);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1947, 2855);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1954, 3473);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1961, 4613);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1966, 6057);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1977, 6966);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1983, 7674);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 1992, 9919);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 2002, 10065);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 2011, 10084);

INSERT INTO countrypops (country, year, population) VALUES ('NAU', 2019, 11550);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1950, 26100);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1960, 32970);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1963, 48780);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1968, 53517);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1973, 57813);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1978, 56213);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1985, 63883);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1990, 72335);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 1995, 77658);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 2000, 84494);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 2005, 92533);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 2010, 103058);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 2015, 110136);

INSERT INTO countrypops (country, year, population) VALUES ('KIR', 2020, 119940);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 1950, 5166);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 1960, 6104);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 1970, 7296);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 1980, 8051);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 1990, 9004);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 1991, 9043);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 2002, 9561);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 2012, 10640);

INSERT INTO countrypops (country, year, population) VALUES ('TUV', 2017, 10507);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1950, 1570);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1951, 1571);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1956, 1619);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1961, 1870);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1972, 1599);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1976, 1575);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1991, 1577);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 1996, 1487);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 2001, 1537);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 2006, 1466);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 2011, 1411);

INSERT INTO countrypops (country, year, population) VALUES ('TOK', 2016, 1499);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1950, 82102);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1951, 84909);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1956, 97327);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1961, 114427);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1966, 131377);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1971, 146627);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1976, 151983);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1981, 156349);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 1991, 161298);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 2001, 176710);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 2006, 180741);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 2011, 187820);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 2016, 195979);

INSERT INTO countrypops (country, year, population) VALUES ('WS', 2021, 200010);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1950, 18937);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1956, 20154);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1960, 20051);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1970, 27159);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1974, 29190);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1980, 32297);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 1990, 46773);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 2000, 57291);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 2010, 55519);

INSERT INTO countrypops (country, year, population) VALUES ('AS', 2020, 49710);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 1969, 8546);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 1976, 9192);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 1990, 13705);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 1996, 14166);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 2003, 14944);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 2008, 13484);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 2013, 12197);

INSERT INTO countrypops (country, year, population) VALUES ('WF', 2018, 11558);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1881, 127486);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1891, 121180);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1901, 120124);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1911, 139541);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1921, 157266);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1936, 198379);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1946, 259638);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1956, 345737);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1966, 476727);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1976, 588068);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1986, 715375);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 1996, 775077);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 2007, 837271);

INSERT INTO countrypops (country, year, population) VALUES ('FJI', 2017, 884887);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 1950, 47220);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 1956, 56838);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 1966, 77429);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 1976, 90085);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 1986, 94649);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 1996, 97784);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 2006, 101991);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 2011, 103252);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 2016, 100651);

INSERT INTO countrypops (country, year, population) VALUES ('TO', 2021, 100179);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1950, 4667);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1951, 4553);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1956, 4707);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1961, 4864);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1966, 5194);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1971, 4990);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1976, 3843);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1981, 3281);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1986, 2531);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1989, 2267);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1991, 2239);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1994, 2300);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 1997, 2088);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 2000, 1857);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 2001, 1736);

INSERT INTO countrypops (country, year, population) VALUES ('NU', 2011, 1611);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1945, 14088);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1951, 15079);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1956, 16680);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1961, 18378);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1966, 19247);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1971, 21322);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1976, 18128);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1981, 17743);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1986, 17614);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1991, 18617);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 1996, 18071);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 2001, 15017);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 2006, 15324);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 2011, 14974);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 2016, 14802);

INSERT INTO countrypops (country, year, population) VALUES ('CK', 2021, 14987);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 1951, 61469);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 1956, 75127);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 1962, 84551);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 1971, 113273);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 1988, 188814);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 1996, 219521);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 2002, 245405);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 2007, 259596);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 2012, 268270);

INSERT INTO countrypops (country, year, population) VALUES ('PF', 2017, 275918);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1936, 250);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1950, 161);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1960, 126);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1970, 96);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1980, 61);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1986, 68);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 1995, 55);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 2013, 56);

INSERT INTO countrypops (country, year, population) VALUES ('PN', 2020, 50);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 1947, 18967000);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 1960, 26085000);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 1976, 36626204);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 1986, 48254238);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 1996, 59312914);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 2006, 72798031);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 2012, 81395541);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 2013, 83667047);

INSERT INTO countrypops (country, year, population) VALUES ('ET', 2017, 94798827);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 1950, 1113382);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 1954, 1088873);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 1964, 1564369);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 1973, 2249237);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 1984, 3642576);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 1995, 4799065);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 2006, 5673031);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 2012, 5363369);

INSERT INTO countrypops (country, year, population) VALUES ('LAR', 2020, 6931061);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 1946, 3230952);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 1956, 3783169);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 1966, 4533351);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 1975, 5588209);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 1984, 6966175);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 1994, 8785711);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 2004, 9910872);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 2013, 10886527);

INSERT INTO countrypops (country, year, population) VALUES ('TN', 2014, 10982754);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 1950, 8872247);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 1960, 11277757);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 1970, 14690855);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 1980, 19475204);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 1990, 26239708);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 1998, 29100867);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 2008, 34080030);

INSERT INTO countrypops (country, year, population) VALUES ('DZ', 2010, 37062820);

INSERT INTO countrypops (country, year, population) VALUES ('MA', 1960, 11626470);

INSERT INTO countrypops (country, year, population) VALUES ('MA', 1971, 15379259);

INSERT INTO countrypops (country, year, population) VALUES ('MA', 1982, 20419555);

INSERT INTO countrypops (country, year, population) VALUES ('MA', 1994, 25475222);

INSERT INTO countrypops (country, year, population) VALUES ('MA', 2004, 29073779);

INSERT INTO countrypops (country, year, population) VALUES ('MA', 2014, 33337529);

INSERT INTO countrypops (country, year, population) VALUES ('WSA', 1997, 222631);

INSERT INTO countrypops (country, year, population) VALUES ('WSA', 2013, 554795);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 1950, 4637634);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 1960, 5098942);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 1970, 5716294);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 1976, 6394918);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 1987, 7696348);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 1998, 9810912);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 2009, 14528622);

INSERT INTO countrypops (country, year, population) VALUES ('RMM', 2020, 20250834);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 1950, 660491);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 1960, 858316);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 1970, 1148936);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 1977, 658361);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 1988, 1865236);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 1997, 2336048);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 2000, 2508159);

INSERT INTO countrypops (country, year, population) VALUES ('RIM', 2013, 3537368);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 1950, 2476638);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 1960, 3177737);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 1970, 4218056);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 1980, 5568908);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 1990, 7514110);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 2000, 9861679);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 2002, 9858482);

INSERT INTO countrypops (country, year, population) VALUES ('SN', 2013, 13508715);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1950, 271372);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1960, 367929);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1963, 315486);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1973, 493499);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1983, 687817);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1993, 1038145);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 1997, 1204984);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 2003, 1360681);

INSERT INTO countrypops (country, year, population) VALUES ('WAG', 2013, 1882450);

INSERT INTO countrypops (country, year, population) VALUES ('GUB', 1950, 510777);

INSERT INTO countrypops (country, year, population) VALUES ('GUB', 1979, 767739);

INSERT INTO countrypops (country, year, population) VALUES ('GUB', 1991, 979202);

INSERT INTO countrypops (country, year, population) VALUES ('GUB', 1997, 1151330);

INSERT INTO countrypops (country, year, population) VALUES ('GUB', 2009, 1520830);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 1950, 3093651);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 1960, 3576684);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 1970, 4209201);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 1980, 4495479);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 1983, 4660582);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 1996, 7156406);

INSERT INTO countrypops (country, year, population) VALUES ('RG', 2014, 10628972);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 1950, 1944001);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 1960, 2160111);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 1963, 2180355);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 1974, 2735159);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 1985, 3515812);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 2004, 4976871);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 2015, 7092113);

INSERT INTO countrypops (country, year, population) VALUES ('SLE', 2021, 7548702);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 1950, 930026);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 1960, 1120314);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 1962, 1016443);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 1974, 1503368);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 1984, 2101628);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 2008, 3476608);

INSERT INTO countrypops (country, year, population) VALUES ('LB', 2010, 3957990);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 1950, 4284457);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 1960, 4829291);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 1970, 5624597);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 1975, 5638203);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 1985, 7964705);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 1996, 10312609);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 2006, 14017262);

INSERT INTO countrypops (country, year, population) VALUES ('BF', 2019, 20505155);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 1950, 2630131);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 1960, 3474724);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 1970, 5241914);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 1975, 6709600);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 1988, 10815694);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 1998, 15366298);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 2000, 16131332);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 2010, 18976588);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 2014, 22671331);

INSERT INTO countrypops (country, year, population) VALUES ('CI', 2021, 29389150);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 1950, 4980878);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 1960, 6726815);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 1970, 8559313);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 1984, 12296081);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 1997, 17698271);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 2000, 18912079);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 2010, 24658823);

INSERT INTO countrypops (country, year, population) VALUES ('GH', 2021, 30832019);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 1950, 1395458);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 1960, 1580513);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 1970, 2115521);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 1981, 2719567);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 1997, 4570530);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 2010, 6191155);

INSERT INTO countrypops (country, year, population) VALUES ('RT', 2020, 7706000);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 1950, 2255221);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 1960, 2431620);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 1970, 2907769);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 1979, 3331210);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 1992, 4915555);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 2002, 6769914);

INSERT INTO countrypops (country, year, population) VALUES ('BEN', 2013, 10008749);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 1950, 37859744);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 1960, 45211614);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 1970, 56131845);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 1980, 73698099);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 1991, 88992218);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 1997, 103912489);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 2006, 140431790);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 2011, 164294516);

INSERT INTO countrypops (country, year, population) VALUES ('NGR', 2016, 193392500);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 1950, 2559703);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 1960, 3337141);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 1970, 4412638);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 1977, 5102990);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 1988, 7251626);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 1997, 9113001);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 2001, 11060291);

INSERT INTO countrypops (country, year, population) VALUES ('RN', 2012, 17138707);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 1950, 2502314);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 1960, 3002596);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 1970, 3644911);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 1980, 4512758);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 1990, 5951574);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 1993, 6279931);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 2009, 11039873);

INSERT INTO countrypops (country, year, population) VALUES ('TCH', 2019, 15775400);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 1950, 5733944);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 1960, 7527450);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 1970, 10232758);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 1980, 14418063);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 1990, 20008804);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 1993, 21266641);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 2000, 27729798);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 2008, 30894000);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 2010, 35652002);

INSERT INTO countrypops (country, year, population) VALUES ('SUD', 2017, 40782700);

INSERT INTO countrypops (country, year, population) VALUES ('SSD', 1983, 4929267);

INSERT INTO countrypops (country, year, population) VALUES ('SSD', 2008, 8260490);

INSERT INTO countrypops (country, year, population) VALUES ('SSD', 2017, 11868200);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 1950, 1326653);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 1960, 1503501);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 1970, 1828710);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 1975, 2054610);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 1988, 2463616);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 1997, 3274426);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 2003, 3895139);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 2010, 4349921);

INSERT INTO countrypops (country, year, population) VALUES ('RCA', 2021, 6091097);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 1950, 4466498);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 1960, 5361367);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 1970, 6770967);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 1976, 7131833);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 1987, 10493655);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 1997, 14261557);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 2005, 17463836);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 2010, 19406100);

INSERT INTO countrypops (country, year, population) VALUES ('CAM', 2015, 22179700);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 1950, 225536);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 1960, 252115);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 1970, 290905);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 1980, 220589);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 1983, 300000);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 1994, 406151);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 2001, 1014999);

INSERT INTO countrypops (country, year, population) VALUES ('GQ', 2015, 1225377);

INSERT INTO countrypops (country, year, population) VALUES ('G', 1950, 473300);

INSERT INTO countrypops (country, year, population) VALUES ('G', 1960, 448564);

INSERT INTO countrypops (country, year, population) VALUES ('G', 1993, 1014976);

INSERT INTO countrypops (country, year, population) VALUES ('G', 1997, 1172798);

INSERT INTO countrypops (country, year, population) VALUES ('G', 2003, 1517685);

INSERT INTO countrypops (country, year, population) VALUES ('G', 2013, 1811079);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 1950, 807726);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 1960, 1013581);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 1970, 1335090);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 1974, 1319790);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 1984, 1909248);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 1997, 2527841);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 2007, 3697490);

INSERT INTO countrypops (country, year, population) VALUES ('RCB', 2010, 4001831);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 1950, 12183661);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 1960, 15248246);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 1970, 20009902);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 1980, 26357407);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 1984, 29916800);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 2000, 46949244);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 2010, 62191161);

INSERT INTO countrypops (country, year, population) VALUES ('CGO', 2015, 86026000);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 1950, 4147509);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 1960, 4965988);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 1970, 5646166);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 1980, 7637141);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 1990, 10333844);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 1997, 10342899);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 2000, 13924930);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 2010, 19549124);

INSERT INTO countrypops (country, year, population) VALUES ('ANG', 2014, 25789024);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1921, 228910);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1936, 320450);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1946, 362460);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1951, 439080);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1970, 761010);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1981, 1033000);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 1991, 1409920);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 2001, 1830330);

INSERT INTO countrypops (country, year, population) VALUES ('NAM', 2011, 2113077);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1904, 120776);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1911, 124350);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1921, 152983);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1936, 265756);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1946, 296310);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1956, 309175);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1964, 549510);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1971, 574094);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1981, 941027);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 1991, 1326796);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 2001, 1680863);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 2011, 2038228);

INSERT INTO countrypops (country, year, population) VALUES ('RB', 2021, 2346179);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1904, 5174000);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1911, 5972000);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1921, 6926000);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1936, 9588000);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1946, 11415000);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1951, 12671452);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1960, 15994181);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1970, 21794328);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1980, 25016525);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1985, 23385645);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1991, 37944000);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 1996, 40583573);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 2001, 44819778);

INSERT INTO countrypops (country, year, population) VALUES ('RSA', 2011, 51770560);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 1950, 733942);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 1956, 641674);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 1966, 969634);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 1976, 1216815);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 1986, 1605177);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 1996, 1862275);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 2006, 1876633);

INSERT INTO countrypops (country, year, population) VALUES ('LS', 2016, 2007201);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 1950, 273000);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 1956, 237021);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 1966, 374571);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 1976, 494534);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 1986, 681059);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 1997, 965859);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 2007, 1018449);

INSERT INTO countrypops (country, year, population) VALUES ('SD', 2017, 1093238);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 1950, 5738911);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 1960, 6603653);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 1970, 8168933);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 1980, 1213000);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 1997, 16075708);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 2007, 20632434);

INSERT INTO countrypops (country, year, population) VALUES ('MOC', 2017, 27909798);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1950, 2746854);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1960, 3752390);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1970, 5206305);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1980, 7289069);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1990, 10461782);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1992, 10412548);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 1997, 11271314);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 2002, 11631657);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 2012, 13061239);

INSERT INTO countrypops (country, year, population) VALUES ('ZW', 2022, 15178979);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 1950, 2372431);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 1960, 3082627);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 1970, 4191114);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 1980, 5847241);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 1990, 7759117);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 2000, 9885591);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 2010, 13092666);

INSERT INTO countrypops (country, year, population) VALUES ('Z', 2022, 19610769);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 1950, 2880700);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 1960, 3525127);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 1966, 4039583);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 1977, 5547460);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 1987, 7988507);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 1998, 9933868);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 2008, 13077160);

INSERT INTO countrypops (country, year, population) VALUES ('MW', 2018, 17563749);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 1950, 7649766);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 1960, 10074490);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 1967, 12313469);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 1978, 17512611);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 1988, 23095882);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 1997, 29058470);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 2002, 34443603);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 2012, 44928923);

INSERT INTO countrypops (country, year, population) VALUES ('EAT', 2021, 61741120);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 1950, 2308923);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 1960, 2786740);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 1970, 3457113);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 1979, 4028420);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 1990, 5292793);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 1997, 5943057);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 2008, 8053574);

INSERT INTO countrypops (country, year, population) VALUES ('BI', 2010, 8444784);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 1950, 2186187);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 1960, 2933424);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 1970, 3754546);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 1978, 4831527);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 1991, 7157551);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 2002, 8128553);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 2012, 10515973);

INSERT INTO countrypops (country, year, population) VALUES ('RWA', 2022, 13246394);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1950, 5158193);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1960, 6788211);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1970, 9446024);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1980, 12549779);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1990, 17534839);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1991, 16671705);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 1997, 20158176);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 2002, 24227297);

INSERT INTO countrypops (country, year, population) VALUES ('EAU', 2014, 34634650);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1950, 6076757);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1960, 8105440);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1962, 8636300);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1969, 10942705);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1979, 15327061);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1989, 21448774);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 1999, 28686607);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 2009, 38610097);

INSERT INTO countrypops (country, year, population) VALUES ('EAK', 2019, 47564296);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 1950, 2264081);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 1960, 2756380);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 1970, 3445420);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 1980, 6089707);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 1987, 7114431);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 1990, 6321615);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 2000, 7385416);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 2010, 9636173);

INSERT INTO countrypops (country, year, population) VALUES ('SO', 2019, 15626000);

INSERT INTO countrypops (country, year, population) VALUES ('DJI', 1950, 62001);

INSERT INTO countrypops (country, year, population) VALUES ('DJI', 1960, 81200);

INSERT INTO countrypops (country, year, population) VALUES ('DJI', 1982, 335000);

INSERT INTO countrypops (country, year, population) VALUES ('DJI', 1991, 493900);

INSERT INTO countrypops (country, year, population) VALUES ('DJI', 2009, 818159);

INSERT INTO countrypops (country, year, population) VALUES ('DJI', 2019, 1049000);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 1950, 18128034);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 1960, 22151218);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 1970, 28414999);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 1980, 35241209);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 1984, 42616876);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 1994, 51766239);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 2007, 73918505);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 2012, 84320987);

INSERT INTO countrypops (country, year, population) VALUES ('ETH', 2022, 105164000);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 1950, 1141300);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 1960, 1404810);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 1970, 1796912);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 1980, 2414647);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 1984, 2748304);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 1997, 2634985);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 2005, 3622400);

INSERT INTO countrypops (country, year, population) VALUES ('ER', 2010, 5741159);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 1950, 148331);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 1960, 199661);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 1970, 272571);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 1980, 295703);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 1990, 341491);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 2000, 434625);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 2010, 491875);

INSERT INTO countrypops (country, year, population) VALUES ('CV', 2021, 483628);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 1940, 60490);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 1950, 60158);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 1960, 64263);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 1970, 73800);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 1981, 96611);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 1991, 117504);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 2001, 137599);

INSERT INTO countrypops (country, year, population) VALUES ('STP', 2012, 187356);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1950, 36322);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1960, 41377);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1970, 52164);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1971, 54695);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1977, 61898);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1987, 68598);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 1994, 74331);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 2002, 81755);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 2010, 90945);

INSERT INTO countrypops (country, year, population) VALUES ('SY', 2022, 100447);

INSERT INTO countrypops (country, year, population) VALUES ('COM', 1950, 156334);

INSERT INTO countrypops (country, year, population) VALUES ('COM', 1958, 183133);

INSERT INTO countrypops (country, year, population) VALUES ('COM', 1980, 335150);

INSERT INTO countrypops (country, year, population) VALUES ('COM', 1991, 446817);

INSERT INTO countrypops (country, year, population) VALUES ('COM', 2003, 575660);

INSERT INTO countrypops (country, year, population) VALUES ('COM', 2017, 758316);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 1985, 67167);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 1991, 94414);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 1997, 131320);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 2002, 160265);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 2007, 186452);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 2012, 212645);

INSERT INTO countrypops (country, year, population) VALUES ('MYT', 2017, 256518);

INSERT INTO countrypops (country, year, population) VALUES ('RM', 1950, 4083554);

INSERT INTO countrypops (country, year, population) VALUES ('RM', 1960, 5099371);

INSERT INTO countrypops (country, year, population) VALUES ('RM', 1970, 6576301);

INSERT INTO countrypops (country, year, population) VALUES ('RM', 1975, 7603790);

INSERT INTO countrypops (country, year, population) VALUES ('RM', 1993, 12209846);

INSERT INTO countrypops (country, year, population) VALUES ('RM', 2018, 25674196);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1851, 181318);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1861, 310743);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1871, 317150);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1881, 361305);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1891, 372656);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1901, 374185);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1911, 373620);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1921, 383069);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1931, 401440);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1944, 431070);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1952, 514748);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1962, 699954);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1972, 850968);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1983, 999945);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 1990, 1056660);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 2000, 1178848);

INSERT INTO countrypops (country, year, population) VALUES ('MS', 2011, 1237091);

INSERT INTO countrypops (country, year, population) VALUES ('RE', 1999, 706300);

INSERT INTO countrypops (country, year, population) VALUES ('RE', 2006, 791321);

INSERT INTO countrypops (country, year, population) VALUES ('RE', 2011, 828581);

INSERT INTO countrypops (country, year, population) VALUES ('HELX', 1997, 7637);

INSERT INTO countrypops (country, year, population) VALUES ('HELX', 2014, 5663);

INSERT INTO countrypops (country, year, population) VALUES ('HELX', 2019, 4577);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1951, 24118);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1955, 26933);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1960, 33140);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1965, 39600);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1970, 46531);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1976, 49630);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 1997, 55971);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 2000, 56124);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 2010, 56452);

INSERT INTO countrypops (country, year, population) VALUES ('GL', 2020, 56081);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1951, 4606);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1957, 4822);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1962, 4990);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1967, 5186);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1974, 5840);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1982, 6037);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 1999, 6316);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 2006, 6125);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 2011, 6080);

INSERT INTO countrypops (country, year, population) VALUES ('SPM', 2016, 6008);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1911, 18994);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1921, 20127);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1931, 27789);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1939, 30518);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1950, 37403);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1960, 42640);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1970, 52976);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1980, 54670);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 1990, 58460);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 2000, 62098);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 2010, 64319);

INSERT INTO countrypops (country, year, population) VALUES ('BM', 2016, 61178);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1871, 3689257);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1881, 4324810);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1891, 4833239);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1901, 5371315);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1911, 7206643);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1921, 8787949);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1931, 10376786);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1941, 11506655);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1951, 14009429);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1956, 16080791);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1961, 18238247);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1966, 20014900);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1971, 21568310);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1976, 22992605);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1981, 24343185);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1986, 25309330);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1991, 27296860);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 1996, 28846761);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 2001, 30007094);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 2006, 31612897);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 2011, 33476688);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 2016, 35151728);

INSERT INTO countrypops (country, year, population) VALUES ('CDN', 2021, 36991980);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 1950, 157813040);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 1960, 186361893);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 1970, 209891345);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 1980, 230176361);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 1990, 254506647);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 2000, 281414181);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 2010, 308745538);

INSERT INTO countrypops (country, year, population) VALUES ('USA', 2020, 331449281);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 1950, 28295514);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 1960, 38676974);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 1970, 52988138);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 1980, 70353013);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 1990, 86077004);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 2000, 97483412);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 2005, 103263388);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 2010, 112336538);

INSERT INTO countrypops (country, year, population) VALUES ('MEX', 2020, 126014024);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 1950, 68918);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 1960, 92068);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 1970, 122179);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 1980, 144151);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 1990, 187552);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 1991, 189392);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 2000, 240204);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 2010, 312971);

INSERT INTO countrypops (country, year, population) VALUES ('BZ', 2019, 430191);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 1950, 2790868);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 1964, 4287997);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 1973, 5160221);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 1981, 6054227);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 1994, 8331874);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 2002, 11237196);

INSERT INTO countrypops (country, year, population) VALUES ('GCA', 2018, 14901286);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 1778, 146684);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 1930, 1459594);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 1950, 1855917);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 1961, 2510984);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 1971, 3554648);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 1992, 5120411);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 2007, 5744113);

INSERT INTO countrypops (country, year, population) VALUES ('ES', 2013, 6290420);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 1945, 1200542);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 1950, 1368605);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 1961, 1884765);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 1974, 2656948);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 1988, 4614377);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 1997, 5605193);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 2001, 6535344);

INSERT INTO countrypops (country, year, population) VALUES ('HN', 2013, 8303771);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 1950, 1057023);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 1963, 1535588);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 1971, 1877952);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 1995, 4357099);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 2005, 5142098);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 2012, 6071045);

INSERT INTO countrypops (country, year, population) VALUES ('NIC', 2016, 6327927);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1864, 120499);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1883, 182073);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1892, 243205);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1927, 471524);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1950, 800875);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1963, 1336274);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1973, 1871780);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1984, 2416809);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 1997, 3463083);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 2000, 3810179);

INSERT INTO countrypops (country, year, population) VALUES ('CR', 2011, 4301712);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1911, 336742);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1921, 446098);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1930, 467459);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1940, 622576);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1950, 805285);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1960, 1075541);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1970, 1428082);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1980, 1805287);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1990, 2329329);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 1997, 2655094);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 2000, 2839177);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 2010, 3661835);

INSERT INTO countrypops (country, year, population) VALUES ('PA', 2020, 4278500);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 1950, 79088);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 1953, 84841);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 1963, 130220);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 1970, 168812);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 1980, 209505);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 1990, 255049);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 2000, 303611);

INSERT INTO countrypops (country, year, population) VALUES ('BS', 2010, 353658);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 1954, 5052);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 1960, 5668);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 1970, 5558);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 1980, 7413);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 1990, 11465);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 2001, 19886);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 2012, 31458);

INSERT INTO countrypops (country, year, population) VALUES ('TUCA', 2018, 53700);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1802, 933);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1891, 4322);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1911, 5564);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1921, 5270);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1934, 5930);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1943, 6690);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1960, 8511);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1970, 10068);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1979, 16677);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1989, 25355);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 1999, 39410);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 2010, 55456);

INSERT INTO countrypops (country, year, population) VALUES ('CYM', 2021, 69656);

INSERT INTO countrypops (country, year, population) VALUES ('C', 1950, 5919997);

INSERT INTO countrypops (country, year, population) VALUES ('C', 1960, 7141130);

INSERT INTO countrypops (country, year, population) VALUES ('C', 1970, 8715054);

INSERT INTO countrypops (country, year, population) VALUES ('C', 1981, 9723605);

INSERT INTO countrypops (country, year, population) VALUES ('C', 2002, 11177743);

INSERT INTO countrypops (country, year, population) VALUES ('C', 2012, 11167325);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 1950, 1402896);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 1960, 1609814);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 1970, 1813594);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 1982, 2190357);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 1991, 2391273);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 2001, 2607632);

INSERT INTO countrypops (country, year, population) VALUES ('JA', 2011, 2697983);

INSERT INTO countrypops (country, year, population) VALUES ('RH', 1950, 3097220);

INSERT INTO countrypops (country, year, population) VALUES ('RH', 1971, 4329991);

INSERT INTO countrypops (country, year, population) VALUES ('RH', 1982, 5053189);

INSERT INTO countrypops (country, year, population) VALUES ('RH', 2003, 7929048);

INSERT INTO countrypops (country, year, population) VALUES ('RH', 2010, 9896400);

INSERT INTO countrypops (country, year, population) VALUES ('RH', 2018, 10788000);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 1950, 2380116);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 1960, 3311788);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 1970, 4523917);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 1981, 5545741);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 1993, 7293390);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 2002, 8562541);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 2010, 9445281);

INSERT INTO countrypops (country, year, population) VALUES ('DOM', 2019, 10358300);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1899, 953243);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1910, 1118012);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1920, 1299809);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1930, 1543913);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1940, 1869255);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1950, 2210703);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1960, 2349544);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1970, 2712033);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1980, 3196520);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 1990, 3522037);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 2000, 3808603);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 2010, 3725789);

INSERT INTO countrypops (country, year, population) VALUES ('PR', 2020, 3285874);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 1950, 26665);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 1960, 32099);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 1970, 62468);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 1980, 96569);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 1990, 101809);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 2000, 108612);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 2010, 106405);

INSERT INTO countrypops (country, year, population) VALUES ('VIRG', 2020, 87146);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 1946, 6505);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 1960, 7921);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 1970, 9672);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 1980, 10985);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 1991, 16115);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 2001, 23161);

INSERT INTO countrypops (country, year, population) VALUES ('BVI', 2010, 28054);

INSERT INTO countrypops (country, year, population) VALUES ('AXA', 1992, 8960);

INSERT INTO countrypops (country, year, population) VALUES ('AXA', 2001, 11561);

INSERT INTO countrypops (country, year, population) VALUES ('AXA', 2011, 13452);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1954, 3366);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1961, 4502);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1967, 5061);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1974, 6191);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1982, 8072);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1990, 28518);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 1999, 29078);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 2006, 35263);

INSERT INTO countrypops (country, year, population) VALUES ('SMAR', 2011, 36286);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 1950, 1497);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 1960, 2834);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 1970, 6862);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 1980, 13098);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 1990, 28546);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 2000, 31347);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 2001, 30594);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 2011, 33609);

INSERT INTO countrypops (country, year, population) VALUES ('SX', 2015, 38247);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 1961, 2176);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 1967, 2351);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 1974, 2491);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 1982, 3059);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 1990, 5038);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 1999, 6852);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 2007, 8450);

INSERT INTO countrypops (country, year, population) VALUES ('SBAR', 2012, 9131);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 1950, 46054);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 1960, 56693);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 1970, 44884);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 1980, 43309);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 1991, 40618);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 2001, 46325);

INSERT INTO countrypops (country, year, population) VALUES ('KN', 2011, 47195);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1871, 35157);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1881, 34964);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1891, 36819);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1911, 32269);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1921, 29767);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1946, 41757);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1960, 54060);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1970, 64794);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 1991, 60840);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 2001, 70737);

INSERT INTO countrypops (country, year, population) VALUES ('AG', 2011, 81799);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 1921, 12120);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 1946, 13313);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 1960, 13378);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 1970, 12155);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 1980, 11685);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 1991, 11314);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 2001, 4491);

INSERT INTO countrypops (country, year, population) VALUES ('MNTS', 2011, 4922);

INSERT INTO countrypops (country, year, population) VALUES ('GP', 1982, 317269);

INSERT INTO countrypops (country, year, population) VALUES ('GP', 1990, 353431);

INSERT INTO countrypops (country, year, population) VALUES ('GP', 1999, 386566);

INSERT INTO countrypops (country, year, population) VALUES ('GP', 2006, 400736);

INSERT INTO countrypops (country, year, population) VALUES ('GP', 2011, 404635);

INSERT INTO countrypops (country, year, population) VALUES ('GP', 2016, 394110);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1871, 27178);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1881, 28211);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1891, 26841);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1901, 28894);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1911, 33863);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1921, 37059);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1946, 47624);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1960, 59916);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1970, 69549);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1981, 73795);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 1991, 71183);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 2001, 71242);

INSERT INTO countrypops (country, year, population) VALUES ('WD', 2011, 70739);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 1967, 320230);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 1974, 324832);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 1982, 328566);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 1990, 359572);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 1999, 381325);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 2006, 397732);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 2011, 392291);

INSERT INTO countrypops (country, year, population) VALUES ('MQ', 2013, 385551);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 1950, 82783);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 1960, 86108);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 1970, 99806);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 1980, 113409);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 1991, 133308);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 2001, 157775);

INSERT INTO countrypops (country, year, population) VALUES ('WL', 2010, 165595);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 1950, 210995);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 1960, 232327);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 1970, 236891);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 1980, 247129);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 1990, 260491);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 2000, 268792);

INSERT INTO countrypops (country, year, population) VALUES ('BDS', 2010, 277821);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 1946, 61647);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 1960, 79948);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 1970, 86944);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 1980, 97845);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 1991, 106499);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 2001, 107835);

INSERT INTO countrypops (country, year, population) VALUES ('WV', 2012, 109991);

INSERT INTO countrypops (country, year, population) VALUES ('WG', 1950, 76676);

INSERT INTO countrypops (country, year, population) VALUES ('WG', 1960, 88677);

INSERT INTO countrypops (country, year, population) VALUES ('WG', 1981, 89088);

INSERT INTO countrypops (country, year, population) VALUES ('WG', 1991, 95597);

INSERT INTO countrypops (country, year, population) VALUES ('WG', 2001, 100895);

INSERT INTO countrypops (country, year, population) VALUES ('WG', 2011, 103328);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 1946, 563222);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 1960, 834350);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 1970, 945210);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 1980, 1079791);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 1990, 1213733);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 2000, 1262366);

INSERT INTO countrypops (country, year, population) VALUES ('TT', 2011, 1328019);

INSERT INTO countrypops (country, year, population) VALUES ('NLB', 2007, 14319);

INSERT INTO countrypops (country, year, population) VALUES ('NLB', 2019, 20104);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 1930, 50165);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 1960, 125181);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 1972, 146884);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 1981, 147388);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 1992, 144097);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 2001, 130627);

INSERT INTO countrypops (country, year, population) VALUES ('CUR', 2011, 150563);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 1950, 38066);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 1960, 53199);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 1972, 57908);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 1981, 60312);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 1991, 66687);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 2000, 90506);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 2010, 101484);

INSERT INTO countrypops (country, year, population) VALUES ('ARU', 2020, 108166);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 1950, 5093708);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 1960, 7580281);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 1970, 10724328);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 1980, 15096432);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 1990, 18105265);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 2001, 23054210);

INSERT INTO countrypops (country, year, population) VALUES ('YV', 2011, 28946101);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 1946, 375701);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 1960, 560330);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 1970, 701718);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 1980, 759567);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 1991, 723673);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 2002, 751223);

INSERT INTO countrypops (country, year, population) VALUES ('GUY', 2012, 747884);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 1950, 183681);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 1964, 324211);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 1972, 379607);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 1980, 355240);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 1997, 436418);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 2004, 492829);

INSERT INTO countrypops (country, year, population) VALUES ('SME', 2012, 541638);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 1974, 55125);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 1982, 73022);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 1990, 114678);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 1999, 156790);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 2007, 213031);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 2012, 239648);

INSERT INTO countrypops (country, year, population) VALUES ('GF', 2017, 268700);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 1950, 11999600);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 1951, 11228509);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 1964, 17484508);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 1973, 22847055);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 1985, 30062198);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 1993, 37664711);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 2005, 41927699);

INSERT INTO countrypops (country, year, population) VALUES ('CO', 2018, 48258494);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 1950, 3452498);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 1960, 4514593);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 1970, 6024764);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 1980, 7909432);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 1990, 9697979);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 1997, 11466291);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 2001, 12156608);

INSERT INTO countrypops (country, year, population) VALUES ('EC', 2010, 14483499);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 1950, 7632461);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 1960, 9931518);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 1961, 10420357);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 1972, 14121564);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 1981, 17762231);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 1993, 22048356);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 2007, 27412157);

INSERT INTO countrypops (country, year, population) VALUES ('PE', 2017, 31237385);

INSERT INTO countrypops (country, year, population) VALUES ('BOL', 1950, 2704165);

INSERT INTO countrypops (country, year, population) VALUES ('BOL', 1976, 4613486);

INSERT INTO countrypops (country, year, population) VALUES ('BOL', 1992, 6420792);

INSERT INTO countrypops (country, year, population) VALUES ('BOL', 2001, 8274325);

INSERT INTO countrypops (country, year, population) VALUES ('BOL', 2012, 10027262);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1950, 6081931);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1960, 7649026);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1970, 9578923);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1980, 11192384);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1990, 13213930);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1992, 13348401);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 1997, 14333258);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 2002, 15051136);

INSERT INTO countrypops (country, year, population) VALUES ('RCH', 2017, 17574003);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 1950, 17150335);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 1960, 20623998);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 1970, 23978532);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 1980, 27947446);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 1991, 32615528);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 2001, 36260130);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 2010, 40117096);

INSERT INTO countrypops (country, year, population) VALUES ('RA', 2022, 46044703);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 1950, 1328452);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 1962, 1819103);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 1972, 2357955);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 1982, 3029830);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 1992, 4152588);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 2002, 5163198);

INSERT INTO countrypops (country, year, population) VALUES ('PY', 2012, 6672631);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1852, 131969);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1860, 229480);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1908, 1042686);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1963, 2595510);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1975, 2788429);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1985, 2955241);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 1996, 3163763);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 2004, 3241003);

INSERT INTO countrypops (country, year, population) VALUES ('ROU', 2011, 3286314);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 1950, 53974725);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 1960, 72775883);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 1970, 96060361);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 1980, 121740438);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 1990, 149648341);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 2000, 169799170);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 2010, 190732694);

INSERT INTO countrypops (country, year, population) VALUES ('BR', 2014, 202768562);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1901, 2043);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1911, 2272);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1921, 2094);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1931, 2392);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1946, 2239);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1953, 2230);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1962, 2172);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1972, 1957);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1986, 1878);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1991, 2091);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 1996, 2564);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 2001, 2913);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 2006, 2955);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 2012, 2931);

INSERT INTO countrypops (country, year, population) VALUES ('FALK', 2016, 3398);
