CREATE KEYSPACE IF NOT EXISTS mondial WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

USE mondial;



CREATE TABLE IF NOT EXISTS ethnicgroup (

    country TEXT,

    name TEXT,

    percentage DECIMAL,

    PRIMARY KEY (country)

);



INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AL', 'Albanian', 97);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AL', 'Greek', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AL', 'Macedonian', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AL', 'Roma', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AL', 'Aromanian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GR', 'Greek', 91);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GR', 'Albanian', 4.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GR', 'Roma', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GR', 'Macedonian', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GR', 'Turkish', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GR', 'Aromanian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Greek Cypriots', 58.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Turkish', 13);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Turkish Cypriots', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Greek', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'British', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Romanian', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Bulgarian', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CY', 'Filipino', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AD', 'Greek Cypriots', 60);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AD', 'British', 40);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Macedonian', 64.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Albanian', 25.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Turkish', 3.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Roma', 2.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Serb', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Bosniak', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MK', 'Aromanian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Serb', 83.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Hungarian', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Roma', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Bosniak', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Croat', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Slovak', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Aromanian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Montenegrin', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Macedonian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SRB', 'Bulgarian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNE', 'Montenegrin', 45.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNE', 'Serb', 29.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNE', 'Bosniak', 12.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNE', 'Albanian', 4.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNE', 'Croat', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNE', 'Roma', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KOS', 'Albanian', 92.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KOS', 'Bosniak', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KOS', 'Serb', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KOS', 'Roma', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KOS', 'Turk', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AND', 'Andorran', 48.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AND', 'Spanish', 25.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AND', 'Portuguese', 13);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AND', 'French', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AND', 'Arab', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AND', 'African', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'French', 75);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'Arab', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'Italian', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'West African', 3.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'Asian', 1.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'Portuguese', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'Berber', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('F', 'Turk', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('E', 'Spanish', 86.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('E', 'Mestizo', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('E', 'Arab', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('E', 'Romanian', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('E', 'Roma', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('E', 'British', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'Czech', 90);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'Moravian', 5.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'Slovak', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'Polish', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'German', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'Roma', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CZ', 'Hungarian', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'Slovak', 80.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'Hungarian', 8.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'Roma', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'Czech', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'Ukrainian', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'German', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SK', 'Polish', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'German', 82);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Turk', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Polish', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Arab', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Ukrainian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Italian', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Romanian', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Roma', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Russian', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Greek', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Serb', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('D', 'Kurd', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('H', 'Hungarian', 92);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('H', 'Roma', 3.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('H', 'German', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('H', 'Slovak', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('H', 'Romanian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('H', 'Croat', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Italian', 90.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Sardinian', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Romanian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Arab', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Albanian', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'German', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Chinese', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Slovene', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('I', 'Roma', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CH', 'German', 65);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CH', 'French', 22);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CH', 'Italian', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CH', 'Romansch', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FL', 'Alemannic', 85.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FL', 'Italian', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FL', 'Portuguese', 1.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FL', 'Turk', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FL', 'Albanian', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Austrian', 85);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Turk', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Serb', 4.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'German', 2.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Croat', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Romanian', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Slovene', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('A', 'Arab', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EST', 'Estonian', 68.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EST', 'Russian', 24.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EST', 'Ukrainian', 1.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EST', 'Belorussian', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EST', 'Finn', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EST', 'Latvian', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LV', 'Latvian', 62.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LV', 'Russian', 25.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LV', 'Belorussian', 3.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LV', 'Ukrainian', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LV', 'Polish', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LV', 'Lithuanian', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LT', 'Lithuanian', 84.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LT', 'Polish', 6.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LT', 'Russian', 5.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LT', 'Belorussian', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LT', 'Ukrainian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BY', 'Belorussian', 83.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BY', 'Russian', 8.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BY', 'Polish', 3.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BY', 'Ukrainian', 1.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BY', 'Tatar', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PL', 'Polish', 98);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PL', 'German', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PL', 'Ukrainian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Ukrainian', 77.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Russian', 17.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Belorussian', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Moldovan', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Crimean Tatar', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Bulgarian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Hungarian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Romanian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Polish', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UA', 'Jewish', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Russian', 80.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Tatar', 3.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Ukrainian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Bashkir', 1.15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Chuvash', 1.05);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Chechen', 1.04);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Armenian', 0.86);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Avars', 0.66);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Mongol', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Mordvin', 0.54);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Circassian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Kazakh', 0.47);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Azerbaijani', 0.44);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Dargin', 0.43);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Yakut', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Udmurt', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Ossetian', 0.38);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Mari', 0.35);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Lezgian', 0.34);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Ingush', 0.32);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Buryat', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'German', 0.29);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Komi', 0.26);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Uzbek', 0.21);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Tajik', 0.15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Kalmyk', 0.12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('R', 'Khanty', 0.02);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'French', 58);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'Dutch', 31);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'Italian', 4.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'Arab', 3.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'Turkish', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'Romanian', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('B', 'Polish', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('L', 'Luxembourgish', 51.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('L', 'Portuguese', 15.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('L', 'French', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('L', 'Italian', 3.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('L', 'German', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('L', 'Spanish', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Dutch', 76.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Arab', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Indonesian', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Surinamese', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'German', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Turk', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Berber', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Polish', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Caribbean', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NL', 'Kurd', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Slovene', 91.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Serb', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Croat', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Bosniak', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Hungarian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Albanian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Roma', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLO', 'Italian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Croat', 90.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Serb', 4.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Bosniak', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Italian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Albanian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Roma', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Hungarian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HR', 'Slovene', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BIH', 'Bosniak', 50.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BIH', 'Serb', 30.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BIH', 'Croat', 15.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BG', 'Bulgarian', 84.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BG', 'Turkish', 9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BG', 'Roma', 4.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BG', 'Russian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BG', 'Armenian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Romanian', 88.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Hungarian', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Roma', 3.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Ukrainian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'German', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Turkish', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Russian', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Crimean Tatar', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RO', 'Aromanian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DK', 'Danish', 86.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DK', 'Arab', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DK', 'Turkish', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DK', 'German', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IS', 'Icelander', 81);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IS', 'Polish', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IS', 'Danish', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FO', 'Faroese', 87.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FO', 'Danish', 7.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'Irish', 82.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'Polish', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'British', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'Asian', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'African', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'Lithuanian', 0.75);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'Romanian', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRL', 'Latvian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Finn', 87.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Swedish', 5.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Russian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Estonian', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Arab', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Somali', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'English', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SF', 'Sami', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('N', 'Norwegian', 82.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('N', 'Polish', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('N', 'Sami', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('S', 'Swedish', 80.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('S', 'Arab', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('S', 'Finnish', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('S', 'Polish', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'French', 26);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'Monegasque', 22.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'Italian', 22);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'British', 7.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'German', 4.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'Russian', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MC', 'Greek', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('V', 'Italian', 80);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('V', 'Swiss', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('V', 'German', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('V', 'Argentinian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CEU', 'Spanish', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CEU', 'Arab', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CEU', 'Berber', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEL', 'Spanish', 46);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEL', 'Berber', 40);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEL', 'Arab', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSM', 'Italian', 99);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('M', 'Maltese', 90);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('M', 'Italian', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('M', 'British', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('M', 'Arab', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBM', 'English', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBM', 'Manx', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBM', 'Irish', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBM', 'Scot', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBM', 'Welsh', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MD', 'Romanian', 78.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MD', 'Ukrainian', 7.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MD', 'Russian', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MD', 'Gagauz', 4.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MD', 'Bulgarian', 1.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MD', 'Roma', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('P', 'Portuguese', 96);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('P', 'African', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('P', 'Ukrainian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('P', 'Romanian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('P', 'Indian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SVA', 'Norwegian', 58);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SVA', 'Russian', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'English', 72.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Scot', 7.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Welsh', 4.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'African', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Northern Irish', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Indian', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Pakistani', 1.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Bangladeshi', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GB', 'Chinese', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBZ', 'Spanish', 28);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBZ', 'British', 27);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBZ', 'Italian', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBZ', 'Portuguese', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBZ', 'Maltese', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBZ', 'Arab', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBG', 'Norman-French', 52);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBG', 'British', 23.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBG', 'Portuguese', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBG', 'Latvian', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBJ', 'Norman-French', 46.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBJ', 'British', 32.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBJ', 'Portuguese', 8.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GBJ', 'Polish', 3.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARM', 'Armenian', 98.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARM', 'Yazidi', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARM', 'Russian', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Georgian', 86.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Azerbaijani', 6.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Armenian', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Abkhaz', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Ossetian', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Russian', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Yazidi', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GE', 'Kurd', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AZ', 'Azerbaijani', 91.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AZ', 'Lezgian', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AZ', 'Armenian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AZ', 'Russian', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Turkish', 71.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Kurd', 19);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Arab', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Circassian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Albanian', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Crimean Tatar', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Armenian', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TR', 'Bosniak', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RL', 'Arab', 95);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RL', 'Armenian', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WB', 'Arab', 83);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WB', 'Jewish', 17);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GAZA', 'Arab', 99.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GAZA', 'Jewish', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IL', 'Jewish', 74.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IL', 'Arab', 20.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SYR', 'Arab', 80);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SYR', 'Kurd', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SYR', 'Turkoman', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SYR', 'Assyrian', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SYR', 'Circassian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SYR', 'Armenian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JOR', 'Arab', 97.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JOR', 'Circassian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JOR', 'Armenian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SA', 'Arab', 85);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SA', 'Indian', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SA', 'Mahra', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRN', 'Arab', 36.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRN', 'Indian', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRN', 'Persian', 14);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRN', 'Bengali', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRN', 'Pakistani', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Arab', 28);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Indian', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Bengali', 12.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Filipino', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Egypt', 8.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Sinhalese', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Pakistani', 4.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Q', 'Persian', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Indian', 38.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Arab', 21.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Bengali', 9.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Persian', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Filipino', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Punjabi', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Pashtun', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UAE', 'Sindhi', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('OM', 'Arab', 58);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('OM', 'Indian', 9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('OM', 'Mahra', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('OM', 'Shehri', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('OM', 'Bengali', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('OM', 'Pakistani', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YE', 'Arab', 88);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YE', 'Afro-Arab', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YE', 'Soqotri', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YE', 'Mahra', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KWT', 'Arab', 57.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KWT', 'Persian', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KWT', 'Indian', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Arab', 70);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Kurd', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Turkoman', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Afro-Arab', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Yazidi', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Assyrian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IRQ', 'Lur', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Persian', 61);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Azerbaijani', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Kurd', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Lur', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Baloch', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Arab', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Qashqai', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Turkmen', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Hazara', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IR', 'Armenian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Pashtun', 42);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Tajik', 27);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Hazara', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Uzbek', 9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Turkmen', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Baloch', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AFG', 'Pamiri', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TM', 'Turkmen', 85.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TM', 'Uzbek', 5.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TM', 'Russian', 5.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TM', 'Azerbaijani', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TM', 'Baloch', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TM', 'Kazakh', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Uzbek', 83.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Tajik', 4.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Kazakh', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Russian', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Karakalpak', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Tatar', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Crimean Tatar', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('UZ', 'Uyghur', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Tajik', 82.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Uzbek', 13.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Pamiri', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Kyrgyz', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Russian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Turkmen', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Tatar', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TJ', 'Arab', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Kyrgyz', 73.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Uzbek', 14.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Russian', 5.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Dungan', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Uyghur', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Tajik', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Kazakh', 0.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KG', 'Ukrainian', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Kazakh', 67.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Russian', 19.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Uzbek', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Ukrainian', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Uyghur', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Tatar', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'German', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Tajik', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KZ', 'Dungan', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNG', 'Mongolian', 86);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNG', 'Oirat', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNG', 'Kazakh', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNG', 'Buryat', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MV', 'Maldivian', 84);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MV', 'Bengali', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MV', 'Filipino', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Punjabi', 44.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Pashtun', 15.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Sindhi', 14.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Saraiki', 12.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Baloch', 3.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Brahui', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Bengali', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Gujarati', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Hazara', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Balti', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PK', 'Kashmiri', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Hindi', 37.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Bengali', 8.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Marathi', 8.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Telugu', 6.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Tamil', 5.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Kannada', 3.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Odia', 3.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Malayali', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Magadhi', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Assamese', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Gondi', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Kashmiri', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Santal', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Kurukh', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Sindhi', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Munda', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Chin', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Pashtun', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Meitei', 0.15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('IND', 'Bodo', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Khas', 38);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Madheshi', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Magar', 7.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Tharu', 6.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Tamang', 5.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Newar', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Sherpa', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Kurukh', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NEP', 'Tibetan', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BHT', 'Sharchop', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BHT', 'Nepalese', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BHT', 'Ngalop', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BHT', 'Kurukh', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BD', 'Bengali', 98);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BD', 'Rohingya', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BD', 'Santal', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BD', 'Bihari', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Bamar', 68);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Dai', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Karen', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Rakhine', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Han Chinese', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Mon', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Jingpo', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Rohingya', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Kachin', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Wa', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Lisu', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Chin', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Indian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Hani', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYA', 'Lahu', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CL', 'Sinhalese', 74.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CL', 'Tamil', 15.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CL', 'Arab', 9.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Han Chinese', 91.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Zhuang', 1.27);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Hui', 0.80);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Manchu', 0.78);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Uyghur', 0.76);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Yi', 0.65);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Tujia', 0.63);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Miao', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Tibetan', 0.47);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Mongol', 0.45);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Bouyei', 0.22);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Kam', 0.22);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Mien', 0.21);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Hmong', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Korean', 0.14);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Hani', 0.12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Hlai', 0.11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Kazakh', 0.11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Dai', 0.09);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Lisu', 0.05);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Dongxiang', 0.05);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Lahu', 0.04);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Wa', 0.03);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Oirat', 0.02);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Xibe', 0.014);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Kyrgyz', 0.014);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Jingpo', 0.01);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CN', 'Salar', 0.01);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RC', 'Han Chinese', 95);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RC', 'Amis', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RC', 'Paiwan', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HK', 'Han Chinese', 95);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HK', 'Filipino', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HK', 'Indonesian', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAC', 'Han Chinese', 88.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAC', 'Portuguese', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KP', 'Korean', 100);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROK', 'Korean', 96);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROK', 'Chinese', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROK', 'Vietnamese', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROK', 'Thai', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('J', 'Japanese', 98.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('J', 'Chinese', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('J', 'Korean', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RP', 'Malay', 95.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RP', 'Chinese', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Viet/Kinh', 87.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Tay', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Thai', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Muong', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Khmer', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Hmong', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Nung', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Han Chinese', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Jarai', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Mien', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Rade', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Bahnar', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Koho', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Sedang', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Cham', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VN', 'Bouyei', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('K', 'Khmer', 95);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('K', 'Cham', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('K', 'Jarai', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('K', 'Kuy', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('K', 'Chinese', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('K', 'Viet/Kinh', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Thai', 59.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Khmu', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Hmong', 9.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Phouthay', 3.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Makong', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Katang', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Viet/Kinh', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Dai', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Akha', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Hani', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Kuy', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Chinese', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Mien', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Lahu', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAO', 'Khmer', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Thai', 52.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Lao', 24.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Chinese', 14);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Malay', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Khmer', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Karen', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Kuy', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Hmong', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Lahu', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Mon', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Lisu', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('THA', 'Mien', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAL', 'Malay', 50.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAL', 'Chinese', 23.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAL', 'Dayak', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAL', 'Tamil', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAL', 'Indian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MAL', 'Rohingya', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRU', 'Malay', 65.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRU', 'Chinese', 10.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BRU', 'Dayak', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SGP', 'Chinese', 74.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SGP', 'Malay', 13.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SGP', 'Tamil', 5.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SGP', 'Indian', 4.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Javanese', 41.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Sundanese', 15.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Malay', 3.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Batak', 3.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Madurese', 3.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Chinese', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Dayak', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RI', 'Laani', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TL', 'Mesticos', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TL', 'Malayo-Polynesian', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TL', 'Papuan', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PNG', 'Enga', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PNG', 'Huli', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SOL', 'Melanesian', 95.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SOL', 'Polynesian', 3.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SOL', 'Micronesian', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SOL', 'Chinese', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SOL', 'European', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VU', 'Melanesian', 97.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VU', 'French', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VU', 'Euronesian', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NCL', 'Melanesian', 40);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NCL', 'European', 35);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NCL', 'Polynesian', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NCL', 'Euronesian', 8.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NCL', 'Indonesian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NCL', 'Vietnamese', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'European', 80);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'Chinese', 5.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'Indian', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'Aboriginal Australians', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'Filipino', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'Vietnamese', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AUS', 'Maltese', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CX', 'European', 23);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CX', 'Chinese', 21.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CX', 'Malay', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CC', 'Malay', 80);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CC', 'European', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NF', 'European', 45);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NF', 'Euronesian', 45);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NZ', 'European', 56.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NZ', 'Asian', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NZ', 'Maori', 7.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NZ', 'Pacific Islander', 4.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PAL', 'Palauan', 72.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PAL', 'Filipino', 16.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PAL', 'Micronesian', 3.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PAL', 'Chinese', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PAL', 'Vietnamese', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PAL', 'European', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'Filipino', 35.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'Chamorro', 23.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'Chinese', 6.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'Micronesian', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'Polynesian', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'Korean', 4.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MP', 'European', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Chamorro', 37.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Filipino', 26.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Micronesian', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'European', 7.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Chuukese', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Korean', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Palauan', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Chinese', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GU', 'Japanese', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FSM', 'Micronesian', 96);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FSM', 'Asian', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FSM', 'Polynesian', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MH', 'Micronesian', 92.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MH', 'Euronesian', 5.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAU', 'Nauruan', 88.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAU', 'Micronesian', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAU', 'Chinese', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KIR', 'Micronesian', 89.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KIR', 'Micronesian-Polynesian', 9.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KIR', 'Polynesian', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUV', 'Polynesian', 86.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUV', 'Micronesian-Polynesian', 6.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUV', 'Micronesian', 5.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TOK', 'Polynesian', 94);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TOK', 'Micronesian', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WS', 'Polynesian', 92.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WS', 'Euronesian', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WS', 'European', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AS', 'Polynesian', 92.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AS', 'Filipino', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WF', 'Polynesian', 99);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FJI', 'Melanesian-Polynesian', 58);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FJI', 'Indian', 37.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TO', 'Polynesian-Melanesian', 95);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TO', 'Melanesian-Polynesian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TO', 'Chinese', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TO', 'European', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NU', 'Polynesian', 88);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CK', 'Polynesian', 88);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PF', 'Polynesian', 66.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PF', 'Euronesian', 16.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PF', 'French', 11.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PF', 'Chinese', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PN', 'Euronesian', 100);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ET', 'Arabized Egypt', 91);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ET', 'Arab', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ET', 'European', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ET', 'Nubian', 0.15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ET', 'Beja', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAR', 'Arabized Berber', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAR', 'Berber', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAR', 'Arab', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAR', 'Toubou', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LAR', 'Tuareg', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TN', 'Arabized Berber', 60);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TN', 'Arab', 35);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TN', 'Berber', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DZ', 'Arabized Berber', 55);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DZ', 'Berber', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DZ', 'Arab', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DZ', 'Turkish', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DZ', 'European', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MA', 'Arab', 44);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MA', 'Berber', 24);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MA', 'Arabized Berber', 21);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MA', 'Moor/Beydan', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WSA', 'Arab', 0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WSA', 'Sahrawi Berber', 0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Bambara', 33);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Fula', 13);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Soninke', 9.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Senufo', 9.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Mandinka', 8.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Dogon', 8.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Songhai', 5.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Bobo', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Black Moor/Haratin', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Tuareg', 1.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Bozo', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Khassonke', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Mossi', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RMM', 'Toucouleur', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RIM', 'Black Moor/Haratin', 40);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RIM', 'Moor/Beydan', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RIM', 'Toucouleur', 16.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RIM', 'Wolof', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RIM', 'Fula', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RIM', 'Soninke', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Wolof', 37);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Serer', 17);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Fula', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Toucouleur', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Mandinka', 5.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Diola', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Soninke', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Balanta', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Manjak', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Bambara', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SN', 'Europeans', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Mandinka', 34);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Fula', 22.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Wolof', 12.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Diola', 10.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Soninke', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Serer', 3.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Manjak', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Bambara', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WAG', 'Hausa', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUB', 'Fula', 28.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUB', 'Balanta', 22.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUB', 'Mandinka', 14.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUB', 'Manjak', 11.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUB', 'Papel', 9.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUB', 'Soninke', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Fula', 33.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Mandinka', 24.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Susu', 21.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Kpelle', 7.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Kissi', 6.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Kuranko', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RG', 'Loma', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Mende', 32.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Temne', 31.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Limba', 8.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Kono', 5.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Kuranko', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Fula', 3.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Susu', 2.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Kissi', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Mandinka', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SLE', 'Krio', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Kpelle', 20.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Bassa', 13.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Grebo', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Dan', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Mano', 7.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Klao', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Gola', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Loma', 5.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Kissi', 4.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Vai', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Mandinka', 3.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Americo-Liberians', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LB', 'Mende', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Mossi', 52);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Fula', 8.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Gurma', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Bobo', 4.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Gurunsi', 4.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Senufo', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Bissa', 3.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Mandinka', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Marka', 1.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BF', 'Tuareg', 1.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Akan', 42.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Senufo', 16.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Mandinka', 14.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Wee', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Guro', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Mossi', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Dan', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Fula', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Hausa', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Bissa', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Yoruba', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'Lebanese', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CI', 'French', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Akan', 47.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Dagbon', 16.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Ewe', 13.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Gurma', 5.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Gurunsi', 4.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Bissa', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Fula', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Hausa', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Yoruba', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Mandinka', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Mossi', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GH', 'Ibibio', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Ewe', 46);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Gurunsi', 22);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Gurma', 9.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Yoruba', 6.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Adja', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Fula', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Mossi', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Akan', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RT', 'Akebu', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Fon', 38.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Aja', 15.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Yoruba', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Bariba', 9.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Fula', 8.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Ottamari', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Gurma', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Bissa', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'Hausa', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BEN', 'French', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Hausa', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Yoruba', 15.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Igbo', 15.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Fula', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Kanuri', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Gbagyi', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Tiv', 2.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Nupe', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Igala', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Ibibio', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Ijo', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Anaang', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Arab', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Ebira', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Edo', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Idoma', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NGR', 'Berom', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Hausa', 53.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Songhai', 21.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Tuareg', 9.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Fula', 6.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Kanuri', 4.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Toubou', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Gurma', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RN', 'Arab', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Sara', 25.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Kanuri', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Arab', 8.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Masalit', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Toubou', 5.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Masa', 4.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Fula', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Hausa', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TCH', 'Bagirmi', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Arab', 70);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Nubian', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Beja', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Masalit', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Fur', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Hausa', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Fula', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SUD', 'Toubou', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SSD', 'Dinka', 35.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SSD', 'Nuer', 15.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SSD', 'Shilluk', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SSD', 'Bari', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SSD', 'Azande', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Gbaya', 46);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Banda', 27);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Sara', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Yakoma', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Mbaka', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Arab', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Azande', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCA', 'Hausa', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Pahuin', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Fula', 14);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Bamileke', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Bamum', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Basaa', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Duala', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Kom', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Ibibio', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Mafa', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Maka', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Gbaya', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Arab', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Igbo', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Kanuri', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CAM', 'Hausa', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GQ', 'Fang', 80);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GQ', 'Bubi', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GQ', 'Annobonese', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GQ', 'Ibibio', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Fang', 32);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Nzebi', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Teke', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Punu', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Shira', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Mbete', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Kota', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Myene', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'French', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('G', 'Hausa', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCB', 'Bakongo', 45);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCB', 'Teke', 16.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCB', 'Mboshi', 13.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCB', 'Mbete', 4.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCB', 'Punu', 4.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Baluba', 18);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Bakongo', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Mongo', 13);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Banyarwanda', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Azande', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Lugbara', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Chokwe', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Gbaya', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CGO', 'Lunda', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Ovimbundu', 37);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Ambundu', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Bakongo', 13);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Chokwe', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Lunda', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Mesticos', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Ovambo', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Chinese', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Herero', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ANG', 'Portuguese', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Ovambo', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Herero', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Damara', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Kavango', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Coloured', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Lozi', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'European', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NAM', 'Khoisan', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RB', 'Tswana', 79);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RB', 'Kalanga', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RB', 'San', 3.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RB', 'Shona', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RB', 'European', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RB', 'Ndebele', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Zulu', 22.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Basotho', 17.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Xhosa', 16.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'European', 8.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Coloured', 8.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Tswana', 8.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Tsonga', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Indian', 2.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Swazi', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RSA', 'Chinese', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('LS', 'Basotho', 99.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SD', 'Swazi', 90);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SD', 'Zulu', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SD', 'European', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SD', 'Tsonga', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Makua', 40);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Tsonga', 21);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Makonde', 11);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Swahili', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Chewa', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Shona', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Yao', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Portuguese', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MOC', 'Indian', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ZW', 'Shona', 70);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ZW', 'Ndebele', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ZW', 'Chewa', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ZW', 'Tonga', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ZW', 'European', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Bemba', 21);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Tonga', 13.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Chewa', 7.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Lozi', 5.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Nsenga', 5.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Tumbuka', 4.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Ngoni', 4.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Luba', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Lunda', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Chinese', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('Z', 'Indian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Chewa', 36.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Lomwe', 18.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Yao', 13.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Ngoni', 10.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Tumbuka', 9.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Sena', 3.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MW', 'Tonga', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Sukuma', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Nyamwezi', 9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Haya', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Swahili', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Chaga', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Luo', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Gogo', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Makonde', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Maasai', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Ha', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Iraqw', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Zigula', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Yao', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAT', 'Mijikenda', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BI', 'Hutu', 85);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BI', 'Tutsi', 14);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BI', 'Twa', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RWA', 'Hutu', 84);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RWA', 'Tutsi', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RWA', 'Twa', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Baganda', 16.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Banyarwanda', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Ankore', 9.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Basoga', 8.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Bakiga', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Iteso', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Langi', 6.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Bagisu', 4.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Acholi', 4.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Lugbara', 3.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Karamojong', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAU', 'Bari', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Kikuyu', 17.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Luhya', 13.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Kalenjin', 12.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Luo', 10.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Kamba', 10.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Somali', 6.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Kisii', 5.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Mijikenda', 5.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Meru', 5.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Turkana', 2.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Maasai', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Oromo', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EAK', 'Arab', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SO', 'Somali', 85);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SO', 'Somalian Bantu', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SO', 'Barawani', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SO', 'Oromo', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DJI', 'Somali', 60);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DJI', 'Afar', 35);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Oromo', 34.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Amhara', 27.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Somali', 6.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Tigray', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Sidama', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Welaita', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Hadiya', 1.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Afar', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ETH', 'Nuer', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ER', 'Tigrinya', 55);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ER', 'Tigre', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ER', 'Saho', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ER', 'Beja', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ER', 'Kunama', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ER', 'Rashaida Arab', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CV', 'Mulatto', 71);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CV', 'African', 28);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CV', 'European', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('STP', 'African', 100);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SY', 'Seychellois', 90);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SY', 'Indian', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('COM', 'Arab-African', 99);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MYT', 'Arab-African', 98);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'Merina', 26);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'Betsimisaraka', 14.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'Tsimihety', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'Sakalava', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'European', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'Comoran', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RM', 'Indian', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MS', 'Indo-Mauritian', 62);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MS', 'Mulatto', 27);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MS', 'Tamil', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MS', 'Sino-Mauritian', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MS', 'Franco-Mauritian', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RE', 'Creoles', 45);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RE', 'European', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RE', 'Tamil', 14);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RE', 'Telugu', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RE', 'Indian', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RE', 'Chinese', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HELX', 'African', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HELX', 'European', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HELX', 'Chinese', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GL', 'Inuit', 88);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GL', 'Danish', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SPM', 'European', 100);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BM', 'African', 52);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BM', 'European', 31);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BM', 'Mulatto', 9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BM', 'Asian', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'English', 18);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'French', 18);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Scot', 13);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Irish', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'German', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Chinese', 7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Indian', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Italian', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Ukrainian', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Dutch', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Polish', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Arab', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Cree', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Ojibwe', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Inuit', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CDN', 'Dakota', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Mestizo', 16.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'African', 13.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'German', 13.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'English', 11.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Irish', 9.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Spanish', 5.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Italian', 5.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'French', 3.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Polish', 2.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Scot', 2.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Jewish', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Norwegian', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Dutch', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Chinese', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Filipino', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Indian', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Arab', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Vietnamese', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Korean', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Japanese', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Cherokee', 0.26);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Hawaiian', 0.17);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Navajo', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Dakota', 0.01);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('USA', 'Yupik', 0.01);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEX', 'European', 47);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEX', 'Mestizo', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEX', 'Amerindian', 21.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEX', 'African', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MEX', 'Arab', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Mestizo', 52.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Mulatto', 25.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Garifuna', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Qeqchi', 5.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'German', 3.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Mopan', 3.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Yucatec', 2.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'European', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'Asian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BZ', 'African', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Mestizo', 56);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Kiche', 11.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Qeqchi', 8.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Kaqchikel', 7.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Mam', 5.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Qanjobal', 2.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Xinca', 1.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Poqomchi', 1.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GCA', 'Garifuna', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ES', 'Mestizo', 86.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ES', 'Spanish', 12.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ES', 'Lenca', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'Mestizo', 90);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'Lenca', 4.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'African', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'European', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'Miskito', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'Garifuna', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'Chorti', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('HN', 'Arab', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'Mestizo', 69);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'European', 17);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'African', 9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'Miskito', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'Matagalpa', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'Chorotega', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('NIC', 'Garifuna', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Mestizo', 74);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'European', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Mulatto', 6.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'African', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Amerindian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Han Chinese', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Cabecar', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Bribri', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CR', 'Ngäbe', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'Mestizo', 65);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'African', 9.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'Ngäbe', 7.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'Mulatto', 6.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'European', 6.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'Kuna', 2.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'Embera', 0.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PA', 'Bugle', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BS', 'African', 90.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BS', 'European', 4.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BS', 'Mulatto', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUCA', 'African', 87.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUCA', 'European', 7.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUCA', 'Mulatto', 2.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TUCA', 'Indian', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CYM', 'Mulatto', 40);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CYM', 'Black', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CYM', 'European', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('C', 'European', 58);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('C', 'Mulatto', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('C', 'Mestizo', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('C', 'African', 9.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('C', 'Chinese', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JA', 'African', 92.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JA', 'Mulatto', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JA', 'Indian', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JA', 'European', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('JA', 'Chinese', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RH', 'African', 95);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RH', 'Mulatto', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RH', 'European', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DOM', 'Mestizo', 58);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DOM', 'African', 15.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DOM', 'European', 13.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('DOM', 'Mulatto', 12.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PR', 'European', 75.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PR', 'African', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PR', 'Mulatto', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PR', 'Asian', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VIRG', 'African', 76);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VIRG', 'European', 15.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VIRG', 'Mulatto', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('VIRG', 'Asian', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BVI', 'Black', 76.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BVI', 'Mulatto', 10.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BVI', 'European', 5.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BVI', 'Indian', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AXA', 'Black', 85.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AXA', 'Mulatto', 8.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AXA', 'European', 3.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AXA', 'Indian', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KN', 'African', 92.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KN', 'Mulatto', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KN', 'European', 2.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('KN', 'Indian', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AG', 'African', 87.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AG', 'Mulatto', 7.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AG', 'Indian', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('AG', 'European', 1.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNTS', 'African', 88.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNTS', 'Mulatto', 6.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNTS', 'European', 2.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MNTS', 'Indian', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GP', 'African', 85);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GP', 'Mulatto', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GP', 'European', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GP', 'Indian', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WD', 'African', 75);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WD', 'Mulatto', 19);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WD', 'Carib', 2.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WD', 'European', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MQ', 'African', 70);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MQ', 'Mulatto', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MQ', 'Indian', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('MQ', 'European', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WL', 'African', 85.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WL', 'Mulatto', 10.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WL', 'Indian', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WL', 'European', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BDS', 'African', 92.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BDS', 'Mulatto', 3.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BDS', 'European', 2.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BDS', 'Indian', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WV', 'African', 71.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WV', 'Mulatto', 23);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WV', 'Carib', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WV', 'European', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WV', 'Indian', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WG', 'African', 82.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WG', 'Mulatto', 13.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WG', 'Indian', 2.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WG', 'European', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('WG', 'Carib', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'Indian', 37.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'African', 36.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'Dougla', 22.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'European', 0.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'Chinese', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'Arab', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('TT', 'Carib', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CUR', 'African', 45);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CUR', 'Mulatto', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CUR', 'Mestizo', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CUR', 'European', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARU', 'Mestizo', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARU', 'Mulatto', 25);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARU', 'African', 15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARU', 'European', 10);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ARU', 'Asian', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YV', 'Mestizo', 51.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YV', 'European', 43.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YV', 'African', 2.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YV', 'Chinese', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('YV', 'Wayuu', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'Indian', 39.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'African', 29.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'Dougla', 20);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'Kapong', 3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'Macushi', 1.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'Wapishana', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'European', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GUY', 'Chinese', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'Indian', 27.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'African', 21.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'Mulatto', 15.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'Javanese', 13.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'Dougla', 13.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'Chinese', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'Carib', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('SME', 'European', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GF', 'Mulatto', 50);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GF', 'African', 30);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GF', 'French', 12);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GF', 'Chinese', 4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GF', 'Hmong', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('GF', 'Carib', 1.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CO', 'Mestizo', 49);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CO', 'European', 37);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CO', 'African', 10.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CO', 'Wayuu', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CO', 'Paez', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('CO', 'Embera', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EC', 'Mestizo', 79.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EC', 'European', 6.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EC', 'African', 5.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EC', 'Quechua', 4.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EC', 'Mulatto', 1.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('EC', 'Shuar', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'Mestizo', 60.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'Quechua', 22.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'European', 5.9);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'African', 3.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'Aymara', 2.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'Ashaninka', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PE', 'Aguaruna', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'Mestizo', 60);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'Quechua', 18);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'Aymara', 16);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'European', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'African', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'Guarani', 0.8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BOL', 'Moxo', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCH', 'European', 52);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCH', 'Mestizo', 39);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCH', 'Mapuche', 4.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCH', 'Aymara', 1.0);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RCH', 'Quechua', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'European', 85);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Arab', 6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Mestizo', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Mapuche', 0.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Guarani', 0.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Toba', 0.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Quechua', 0.2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'African', 0.15);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Wichi', 0.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('RA', 'Aymara', 0.05);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PY', 'Mestizo', 90);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PY', 'German', 5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PY', 'Guarani', 1.5);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('PY', 'African', 1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROU', 'European', 87);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROU', 'African', 8);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROU', 'Mestizo', 2.4);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('ROU', 'Charrua', 2);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BR', 'European', 47.7);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BR', 'Mestizo', 22.3);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BR', 'Mulatto', 20.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BR', 'African', 7.6);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BR', 'Asian', 1.1);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('BR', 'Guarani', 0.025);

INSERT INTO ethnicgroup (country, name, percentage) VALUES ('FALK', 'British', 95);
