CREATE KEYSPACE IF NOT EXISTS mondial WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

USE mondial;



CREATE TABLE IF NOT EXISTS river (

    name TEXT,

    river TEXT,

    lake TEXT,

    sea TEXT,

    length DECIMAL,

    area DECIMAL,

    source TEXT,

    mountains TEXT,

    sourceelevation DECIMAL,

    estuary TEXT,

    estuaryelevation DECIMAL,

    PRIMARY KEY (name)

);



INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Thjorsa', '', '', 'Atlantic Ocean', 230, 7530, '(65,-18)', '', 0, '(63.9,-20.8)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jökulsa a Fjöllum', '', '', 'Greenland Sea', 206, 7380, '(64.8,-16.5)', '', 0, '(66.2,-16.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Thames', '', '', 'North Sea', 346, 12935, '(51.70,-2.03)', '', 105, '(51.50,0.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Severn', '', '', 'Atlantic Ocean', 354, 12935, '(52.49,-3.73)', '', 610, '(51.61,-2.63)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Avon', 'Severn', '', '', 123, 2308, '(51.34,-2.27)', '', 150, '(51.50,-2.72)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Test', '', '', 'The Channel', 64, 1260, '(51.25,-1.24)', '', 90, '(50.93,-1.48)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Great Ouse', '', '', 'North Sea', 64, 1260, '(52.09,-1.09)', '', 150, '(52.80,-0.36)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Trent', '', '', 'North Sea', 298, 10435, '(53.12,-2.14)', '', 275, '(53.70,-0.69)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ouse', '', '', 'North Sea', 208, 4133, '(54.37,-2.30)', '', 640, '(53.71,-0.70)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aire', 'Ouse', '', '', 123, 2308, '(54.10,-2.19)', 'Pennines', 405, '(53.72,-0.90)', 5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Clyde', '', '', 'Irish Sea', 176, 4000, '(55.41,-3.65)', '', 278, '(55.96,-4.71)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Leven', 'Clyde', '', '', 10, 730, '(56.01,-4.59)', '', 7.9, '(55.94,-4.57)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ness', '', '', 'North Sea', 12, 1850, '(57.41,-4.33)', '', 16, '(57.49,-4.22)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bann', '', '', 'Atlantic Ocean', 129, 5775, '(54.19,-6.08)', 'Mourne Mountains', 177, '(55.17,-6.77)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Shannon', '', '', 'Atlantic Ocean', 360, 15695, '(54.23,-7.93)', '', 76, '(52.57,-9.70)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gudenå', '', '', 'Kattegat', 158, 2643, '(55.90,9.40)', '', 65, '(56.48,10.21)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Glomma', '', '', 'Skagerrak', 621, 42000, '(62.6,12)', '', 860, '(59.20,10.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lågen', 'Glomma', '', '', 204, 11459, '(62.19,8.45)', '', 611, '(61.10,11.45)', 123);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Götaälv', '', '', 'Kattegat', 93, 50180, '(58.4,12.34)', '', 44, '(57.7,11.9)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Motala Ström', '', '', 'Baltic Sea', 100, 15481, '(58.54,15.00)', '', 88, '(58.62,16.25)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Klarälv', '', 'Vänern', '', 460, 11847, '(62.2,11.9)', '', 662, '(59.4,13.5)', 44);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dalälv', '', '', 'Baltic Sea', 520, 28953.8, '(60.55,15.1)', '', 150, '(60.7,17.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Västerdalälv', 'Dalälv', '', '', 320, 8640, '(61.8,12.6)', '', 661.6, '(60.55,15.1)', 150);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Österdalälv', 'Dalälv', '', '', 241, 12430, '(61.85,12.7)', '', 442.5, '(60.55,15.1)', 150);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Umeälv', '', '', 'Baltic Sea', 470, 26814, '(66.1,14.8)', '', 525, '(63.5,20.1)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Paatsjoki', '', '', 'Barents Sea', 145, 18404, '(68.95,28.3)', '', 119, '(60.75,30.05)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Torneälv', '', '', 'Baltic Sea', 631, 40131, '(68.27,18.13)', '', 1189, '(65.81,24.35)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ounasjoki', 'Kemijoki', '', '', 300, 13968, '(68.6,23.8)', '', 287, '(66.3,24.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kemijoki', '', '', 'Baltic Sea', 550, 51127, '(67.96,28.9525)', '', 230, '(65.77,24.45)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oulujoki', '', '', 'Baltic Sea', 107, 22841, '(64.3,27.25)', '', 123, '(65.3,25.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kymijoki', '', '', 'Baltic Sea', 203, 37159, '(61.5,25.4)', '', 78, '(60.3,26.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kokemäenjoki', '', '', 'Baltic Sea', 121, 27046, '(61.3,23)', '', 57.5, '(61.3,21.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vuoksi', '', 'Ozero Ladoga', '', 162, 52400, '(61.2,28.75)', '', 75.7, '(60.81,31.54)', 4);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Memel', '', '', 'Baltic Sea', 937, 98200, '(53.25,27.31)', '', 176, '(55.34,21.25)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Neris', 'Memel', '', '', 510, 25100, '(54.69,27.87)', '', 177, '(54.90,23.87)', 21);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Weichsel', '', '', 'Baltic Sea', 1047, 194424, '(49.61,19.01)', 'Beskides', 1100, '(54.36,18.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Narew', 'Weichsel', '', '', 484, 75175, '(52.87,24.23)', '', 159, '(52.43,20.67)', 67);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Western Bug', 'Narew', '', '', 772, 39400, '(49.09,25.06)', '', 345, '(52.50,21.08)', 75);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dunajec', 'Weichsel', '', '', 247, 6796, '(49.20,19.86)', 'Western Carpathians', 1820, '(50.24,20.73)', 175);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('San', 'Weichsel', '', '', 433, 16861, '(49.00,22.87)', 'Wooded Carpathians', 850, '(50.74,21.85)', 170);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Poprad', 'Dunajec', '', '', 174, 2081, '(49.18,20.06)', 'Western Carpathians', 1946, '(49.59,20.65)', 292);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oder', '', '', 'Baltic Sea', 866, 118861, '(49.61,17.52)', 'Sudety Mountains', 634, '(53.60,14.59)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Neiße', 'Oder', '', '', 254, 4403, '(50.73,15.23)', 'Sudety Mountains', 655, '(52.07,14.76)', 32);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Warta', 'Oder', '', '', 808, 54529, '(50.49,19.49)', '', 379, '(52.60,14.60)', 9);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Elbe', '', '', 'North Sea', 1091, 148268, '(50.78,15.54)', 'Sudety Mountains', 1386, '(53.89,8.71)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Havel', 'Elbe', '', '', 334, 24096, '(53.47,12.95)', '', 65, '(52.91,11.88)', 22);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Spree', 'Havel', '', '', 400, 10100, '(51.01,14.65)', '', 478, '(52.53,13.21)', 29);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saale', 'Elbe', '', '', 413, 24167, '(50.12,11.83)', 'Fichtelgebirge', 728, '(51.95,11.91)', 49);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Weiße Elster', 'Saale', '', '', 257, 5154, '(50.2,12.27)', '', 724, '(51.43,11.95)', 80);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mulde', 'Elbe', '', '', 314, 7400, '(50.41,12.40)', 'Erzgebirge', 770, '(51.87,12.23)', 57);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Eger', 'Elbe', '', '', 316, 5614, '(50.07,11.82)', '', 752, '(50.53,14.13)', 136);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Moldau', 'Elbe', '', '', 440, 28000, '(48.97,13.56)', 'Bohemian Mountains', 1174, '(50.35,14.47)', 155);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Berounka', 'Moldau', '', '', 241, 8708, '(49.85,12.47)', '', 710, '(50.00,14.40)', 187);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Weser', '', '', 'North Sea', 440, 41094, '(51.4,9.65)', '', 116.5, '(53.5,8.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aller', 'Weser', '', '', 211, 15744, '(52.10,11.23)', '', 130, '(52.94,9.18)', 10);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oker', 'Aller', '', '', 128, 1822, '(51.77,10.49)', 'Harz', 910, '(52.52,10.36)', 45);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Leine', 'Aller', '', '', 281, 6512, '(51.39,10.32)', '', 340, '(52.72,9.59)', 25);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Werra', 'Weser', '', '', 292, 5496, '(50.5,10.96)', 'Thüringer Wald', 797, '(51.4,9.65)', 116.5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Fulda', 'Weser', '', '', 221, 6947, '(50.5,9.9)', 'Rhön', 850, '(51.4,9.65)', 116.5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ems', '', '', 'North Sea', 371, 13160, '(51.86,8.70)', '', 129, '(53.45,6.88)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hase', 'Ems', '', '', 170, 3086, '(52.63,8.27)', '', 163, '(52.70,7.29)', 11);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rhein', '', '', 'North Sea', 1324, 198735, '(46.6,8.7)', 'Alps', 2345, '(51.9,4.00)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lippe', 'Rhein', '', '', 220, 4890, '(51.78,8.82)', '', 140, '(51.65,6.60)', 15);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Emscher', 'Rhein', '', '', 83, 775, '(51.49,7.61)', '', 147, '(51.56,6.69)', 18);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ruhr', 'Rhein', '', '', 219, 4485, '(51.21,8.56)', 'Rothaargebirge', 674, '(51.45,6.72)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Wupper', 'Rhein', '', '', 116.5, 813, '(51.1,7.6)', 'Rothaargebirge', 444, '(51.04,6.95)', 37);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sieg', 'Rhein', '', '', 155, 2857, '(50.92,8.25)', 'Rothaargebirge', 603, '(50.47,7.07)', 45);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lahn', 'Rhein', '', '', 246, 5925, '(50.89,8.24)', 'Rothaargebirge', 603, '(50.31,7.59)', 69);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Main', 'Rhein', '', '', 524, 27292, '(50.1,11.4)', 'Fichtelgebirge', 887, '(49.99,8.29)', 82);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Regnitz', 'Main', '', '', 59, 7523, '(49.49,10.99)', '', 283, '(49.91,10.83)', 231);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rednitz', 'Regnitz', '', '', 124, 2118, '(49.43,10.40)', '', 452, '(49.49,10.99)', 283);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pegnitz', 'Regnitz', '', '', 113, 1230, '(49.76,11.54)', '', 426, '(49.49,10.99)', 283);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nidda', 'Main', '', '', 89.7, 1923, '(50.53,9.23)', '', 720, '(50.10,8.55)', 95);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mosel', 'Rhein', '', '', 544, 28286, '(47.89,6.89)', 'Vogesen', 715, '(50.37,7.61)', 60);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sauer', 'Mosel', '', '', 173, 4259, '(49.92,5.4)', 'Ardennes', 510, '(49.71,6.51)', 133);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Alzette', 'Sauer', '', '', 73, 1172, '(49.48,5.96)', '', 305, '(49.85,6.1)', 192);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saar', 'Mosel', '', '', 227, 7431, '(48.5,7.15)', 'Vogesen', 640, '(49.7,6.6)', 130);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Meurthe', 'Mosel', '', '', 161, 3085, '(48.06,7.02)', 'Vogesen', 1185, '(48.78,6.14)', 189);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Neckar', 'Rhein', '', '', 367, 14000, '(48.05,8.5)', '', 706, '(49.51,8.44)', 88);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Enz', 'Neckar', '', '', 105, 2228, '(48.61,8.45)', 'Black Forest', 822, '(49.01,9.15)', 170);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ill', 'Rhein', '', '', 217, 4760, '(47.46,7.26)', 'Jura', 560, '(48.70,7.93)', 127);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Elz', 'Rhein', '', '', 121, 1539, '(48.102,8.164)', 'Black Forest', 1038, '(48.56,7.81)', 137);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Birs', 'Rhein', '', '', 75, 897, '(47.21,7.18)', 'Jura', 762, '(47.56,7.62)', 246);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aare', 'Rhein', '', '', 288, 17620, '(46.55,8.2)', 'Alps', 2310, '(47.61,8.22)', 311);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saane', 'Aare', '', '', 126, 1893, '(46.33,7.27)', 'Alps', 2315, '(46.98,7.26)', 461);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Zihl', '', 'Bielersee', '', 8.5, 2695, '(47.00,7.02)', '', 429, '(47.05,7.07)', 428);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Orbe', '', 'Lac de Neuchâtel', '', 72, 476, '(46.49,6.06)', 'Jura', 1100, '(46.79,6.66)', 429);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Reuss', 'Aare', '', '', 164, 3425, '(46.56,8.54)', 'Alps', 2431, '(47.4921,8.2371)', 329);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Limmat', 'Aare', '', '', 36.3, 2416, '(47.23,8.64)', '', 406, '(47.50,8.24)', 328);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Thur', 'Rhein', '', '', 135, 1760, '(47.24,9.35)', 'Alps', 2035, '(47.59,8.49)', 345);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bregenzer Ach', '', 'Bodensee', '', 67, 835, '(47.23,10.11)', 'Alps', 2200, '(47.50,9.69)', 395);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hinterrhein', 'Rhein', '', '', 72, 1693, '(46.50,9.04)', 'Alps', 2400, '(46.82,9.41)', 590);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Maas', 'Rhein', '', '', 925, 34548, '(47.97,5.63)', '', 409, '(51.73,4.73)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rur', 'Maas', '', '', 164.5, 2361, '(50.50,6.11)', '', 660, '(51.20,6.00)', 17);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Schelde', '', '', 'North Sea', 360, 21863, '(49.99,3.27)', '', 97, '(51.42,3.06)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Somme', '', '', 'The Channel', 245, 6550, '(49.91,3.60)', '', 86, '(50.19,1.62)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Seine', '', '', 'The Channel', 776, 75000, '(47.48,4.71)', '', 470, '(49.42,0.10)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Marne', 'Seine', '', '', 514, 12816, '(47.8,5.35)', '', 406, '(48.8,2.4)', 32);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vilaine', '', '', 'Atlantic Ocean', 218, 10882, '(48.23,-1.05)', '', 175, '(47.50,-2.38)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Loire', '', '', 'Atlantic Ocean', 1013, 117000, '(44.84,4.22)', 'Cevennes', 1408, '(47.27,-2.18)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Maine', 'Loire', '', '', 11, 22350, '(47.49,-0.54)', '', 15, '(47.61,-0.61)', 13);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sarthe', 'Maine', '', '', 314, 7864, '(48.63,-0.53)', '', 255, '(47.49,-0.54)', 15);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mayenne', 'Maine', '', '', 203, 5820, '(48.46,-0.13)', '', 343, '(47.49,-0.54)', 15);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vienne', 'Loire', '', '', 363, 21161, '(45.66,2.09)', 'Massif Central', 880, '(47.21,0.08)', 33);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cher', 'Loire', '', '', 365, 14000, '(45.92,2.47)', 'Massif Central', 715, '(47.34,0.48)', 38);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Allier', 'Loire', '', '', 421, 14350, '(44.59,3.79)', 'Cevennes', 1503, '(46.96,3.08)', 167);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Garonne', '', '', 'Atlantic Ocean', 647, 55000, '(42.6,0.98)', 'Pyrenees', 1872, '(45.0,-0.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rhone', '', '', 'Mediterranean Sea', 812, 100000, '(46.57,8.38)', 'Alps', 1753, '(43.33,4.84)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saone', 'Rhone', '', '', 473, 29900, '(48.1,6.2)', 'Vogesen', 405, '(45.7,4.8)', 165);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Doubs', 'Saone', '', '', 453, 7710, '(46.7,6.21)', 'Jura', 937, '(46.9,5.0)', 175);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Isere', 'Rhone', '', '', 286, 11890, '(45.4,7.0)', 'Alps', 2815, '(45.0,4.85)', 108);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Durance', 'Rhone', '', '', 323, 14342, '(44.89,6.72)', 'Alps', 2325, '(43.92,4.74)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mino', '', '', 'Atlantic Ocean', 308, 12486, '(43.19,-7.53)', 'Cordillera Cantabrica', 695, '(41.87,-8.87)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Douro', '', '', 'Atlantic Ocean', 897, 98400, '(42,-3)', 'Cordillera Iberica', 2160, '(41.15,-8.66)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mondego', '', '', 'Atlantic Ocean', 234, 6644, '(40.43,-7.57)', 'Cordillera Iberica Central', 1425, '(40.15,-8.88)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tejo', '', '', 'Atlantic Ocean', 1007, 80600, '(40.32,-1.70)', 'Cordillera Iberica', 1580, '(38.7,-9.3)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jarama', 'Tejo', '', '', 190, 11597, '(41.15,-3.53)', 'Cordillera Iberica Central', 2119, '(40.03,-3.65)', 482);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sado', '', '', 'Atlantic Ocean', 180, 7640, '(37.64,-8.26)', '', 230, '(38.49,-8.93)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Guadiana', '', '', 'Atlantic Ocean', 742, 67733, '(42,-3)', 'Cordillera Iberica', 608, '(37.35,-7.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Guadalquivir', '', '', 'Atlantic Ocean', 657, 56978, '(37.83,-2.98)', 'Cordillera Betica', 1400, '(36.79,-6.36)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Genil', 'Guadalquivir', '', '', 358, 8278, '(37.11,-3.34)', 'Cordillera Betica', 1480, '(37.69,-5.32)', 44);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Segura', '', '', 'Mediterranean Sea', 325, 18870, '(38.05,-2.70)', 'Cordillera Betica', 1680, '(38.11,-0.64)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Júcar', '', '', 'Mediterranean Sea', 500, 21600, '(40.40,-1.84)', 'Cordillera Iberica', 1570, '(39.15,-0.24)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Turia', '', '', 'Mediterranean Sea', 280, 6393.6, '(40.40,-1.73)', 'Cordillera Iberica', 1670, '(39.42,-0.33)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ebro', '', '', 'Mediterranean Sea', 925, 83093, '(43.0375,-4.37)', 'Cordillera Cantabrica', 1600, '(40.8,0.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Segre', 'Ebro', '', '', 265, 20000, '(43.40,-2.11)', 'Pyrenees', 2300, '(41.36,0.30)', 58);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Valira', 'Segre', '', '', 44, 592, '(42.51,1.54)', 'Pyrenees', 1050, '(42.35,1.44)', 690);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Po', '', '', 'Mediterranean Sea', 652, 75000, '(44.70,7.09)', 'Alps', 2022, '(44.95,12.43)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tresa', '', 'Lago Maggiore', '', 15, 754, '(45.97,8.86)', 'Alps', 271, '(46.00,8.73)', 193);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ticino', 'Po', '', '', 248, 7228, '(46.475,8.42)', 'Alps', 2536, '(45.14,9.235)', 50);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Moesa', 'Ticino', '', '', 46, 475, '(46.50,9.06)', 'Alps', 2250, '(46.22,9.04)', 233);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lambro', 'Po', '', '', 130, 1350, '(45.92,9.24)', '', 942, '(45.14,9.55)', 49);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dora Baltea', 'Po', '', '', 160, 3920, '(45.81,6.96)', 'Alps', 1400, '(45.18,8.05)', 158);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tanaro', 'Po', '', '', 276, 8324, '(44.12,7.72)', 'Alps', 1360, '(45.00,8.77)', 75);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Adda', 'Po', '', '', 313, 7979, '(46.55,10.3)', 'Alps', 2235, '(45.13,9.88)', 32);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mera', '', 'Lago di Como', '', 50, 0, '(46.40,9.57)', 'Alps', 2791, '(46.20,9.38)', 197);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mincio', 'Po', '', '', 75, 2859, '(45.4,10.7)', 'Alps', 65, '(45.1,10.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Etsch', '', '', 'Mediterranean Sea', 415, 12200, '(46.7,10.5)', 'Alps', 1525, '(44.8,7.09)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tevere', '', '', 'Mediterranean Sea', 405, 17375, '(43.77,12.08)', 'Apennin', 1348, '(41.74,12.23)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Marta', '', '', 'Mediterranean Sea', 54, 0, '(42.53,12.93)', '', 335, '(42.23,11.70)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Arrone', '', '', 'Mediterranean Sea', 35, 125, '(42.09,12.28)', '', 160, '(41.87,12.18)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Arno', '', '', 'Mediterranean Sea', 240, 8200, '(43.9,11.7)', 'Apennin', 1385, '(43.7,10.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Imera Meridionale', '', '', 'Mediterranean Sea', 144, 2122, '(37.83,14.15)', '', 1160, '(37.11,13.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tirso', '', '', 'Mediterranean Sea', 152, 3375, '(40.51,9.34)', '', 770, '(39.89,8.54)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Donau', '', '', 'Black Sea', 2845, 795686, '(47.95,8.52)', 'Black Forest', 686, '(45.16,29.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Breg', 'Donau', '', '', 45.9, 291.2, '(48.100,8.172)', 'Black Forest', 1078, '(47.95,8.52)', 686);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Brigach', 'Donau', '', '', 43, 195, '(48.11,8.28)', 'Black Forest', 940, '(47.95,8.52)', 686);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Iller', 'Donau', '', '', 147, 2152, '(47.43,10.27)', 'Alps', 783, '(48.38,9.97)', 468);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lech', 'Donau', '', '', 264, 3926, '(47.17,10.0)', 'Alps', 1840, '(48.73,10.93)', 392);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Isar', 'Donau', '', '', 295, 8370, '(47.37,11.40)', 'Alps', 1160, '(48.80,12.98)', 310);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ammer', 'Isar', '', '', 168, 3221, '(47.57,11.05)', 'Alps', 850, '(48.50,11.96)', 407);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Würm', 'Ammer', '', '', 35, 429, '(48.00,11.35)', '', 596, '(48.30,11.5)', 482);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Inn', 'Donau', '', '', 517, 25700, '(46.41,9.67)', 'Alps', 2484, '(48.57,13.47)', 291);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ilz', 'Donau', '', '', 62, 850, '(48.94,13.41)', 'Bayrischer Wald', 1300, '(48.57,13.47)', 291);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Regen', 'Donau', '', '', 190, 2953, '(49.17,13.25)', 'Bayrischer Wald', 1053, '(49.02,12.11)', 325);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Naab', 'Donau', '', '', 197, 5514, '(49.76,12.4)', 'Bayrischer Wald', 775, '(49.02,12.02)', 333);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Alz', 'Inn', '', '', 150, 2197, '(47.3,12.35)', 'Alps', 1797, '(48.3,12.8)', 360);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Salzach', 'Inn', '', '', 225, 6700, '(47.30,12.11)', 'Alps', 2300, '(48.21,12.92)', 344);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Enns', 'Donau', '', '', 254, 5940, '(47.33,13.35)', 'Alps', 1375, '(48.24,14.52)', 245);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('March', 'Donau', '', '', 358, 27633, '(50.21,16.85)', 'Sudety Mountains', 1380, '(48.17,16.98)', 135);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Thaya', 'March', '', '', 310, 12772, '(48.66,15.04)', '', 657, '(48.62,16.94)', 147);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Svratka', 'Thaya', '', '', 174, 7116, '(49.64,16.00)', '', 772, '(48.91,16.61)', 163);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jihlava', 'Svratka', '', '', 184, 3117, '(49.26,15.28)', '', 630, '(48.91,16.61)', 164);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Raab', 'Donau', '', '', 250, 1020, '(47.35,15.52)', 'Alps', 1150, '(47.69,17.63)', 118);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Waag', 'Donau', '', '', 403, 10640, '(49.02,19.81)', 'Western Carpathians', 664, '(47.75,18.15)', 106);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Orava', 'Waag', '', '', 62, 1192, '(49.38,19.56)', 'Western Carpathians', 601, '(49.15,19.14)', 430);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Czarna Orava', '', 'Orava Reservoir', '', 29, 0, '(49.52,19.82)', 'Western Carpathians', 912, '(49.47,19.63)', 601);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Biela Orava', '', 'Orava Reservoir', '', 35.4, 469.2, '(49.32,19.19)', 'Western Carpathians', 1090, '(49.40,19.48)', 601);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nitra', 'Waag', '', '', 166, 4499, '(48.96,18.60)', '', 910, '(47.96,18.02)', 110);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hron', 'Donau', '', '', 298, 5453, '(48.86,20.22)', 'Western Carpathians', 935, '(47.82,18.74)', 100);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Drau', 'Donau', '', '', 749, 40120, '(46.73,12.26)', 'Alps', 1450, '(45.54,18.93)', 90);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gail', 'Drau', '', '', 122, 1414, '(46.72,12.54)', 'Alps', 1518, '(46.61,13.88)', 484);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mur', 'Drau', '', '', 453, 14108, '(47.13,13.35)', 'Alps', 1898, '(46.30,16.88)', 130);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tisza', 'Donau', '', '', 1308, 146500, '(48.1,24.25)', 'Wooded Carpathians', 460, '(45.05,20.3)', 80);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Somes', 'Tisza', '', '', 596, 15015, '(46.64,22.73)', '', 1160, '(48.12,22.34)', 120);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sajó', 'Tisza', '', '', 229, 11900, '(48.79,20.21)', 'Western Carpathians', 1200, '(47.94,21.11)', 90);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hernad', 'Sajó', '', '', 286, 5500, '(48.94,20.18)', 'Western Carpathians', 750, '(47.99,20.93)', 95);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Torysa', 'Hernad', '', '', 129, 1349, '(49.11,20.64)', 'Western Carpathians', 1000, '(48.64,21.36)', 170);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mureș', 'Tisza', '', '', 776, 27832, '(46.62,25.62)', 'Eastern Carpathians', 850, '(46.25,20.19)', 75);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Argeș', 'Donau', '', '', 350, 12550, '(45.55,24.6)', 'Southern Carpathians', 2140, '(44.06,26.62)', 12);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dâmbovița', 'Argeș', '', '', 237, 2837, '(45.5,24.94)', 'Southern Carpathians', 2100, '(44.23,26.47)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ialomița', 'Donau', '', '', 414, 8900, '(45.42,24.44)', 'Southern Carpathians', 2160, '(44.70,27.85)', 5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Save', 'Donau', '', '', 945, 95419, '(46.2,13.6)', 'Alps', 0, '(44.8,20.4667)', 68);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bosna', 'Save', '', '', 271, 10457, '(43.82,18.27)', 'Dinaric Alps', 560, '(45.07,18.47)', 89);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Drina', 'Save', '', '', 346, 19926, '(43.35,18.8)', 'Dinaric Alps', 441, '(44.9,19.35)', 90);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tara', 'Drina', '', '', 140, 2006, '(42.6,19.57)', 'Dinaric Alps', 2000, '(43.35,18.8)', 441);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Piva', 'Drina', '', '', 120, 1270, '(43.11,18.82)', 'Dinaric Alps', 0, '(43.35,18.8)', 441);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Morava', 'Donau', '', '', 185, 37444, '(43.7,21.4)', 'Dinaric Alps', 132, '(44.6,21.1)', 65);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Southern Morava', 'Morava', '', '', 295, 15469, '(42.1,21.4)', '', 0, '(43.7,21.4)', 132);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Zapadna Morava', 'Morava', '', '', 308, 15849, '(43.85,20.06)', 'Dinaric Alps', 0, '(43.7,21.4)', 132);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ibar', 'Zapadna Morava', '', '', 276, 8059, '(42.80,20.09)', 'Dinaric Alps', 1280, '(43.73,20.75)', 190);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Iskar', 'Donau', '', '', 368, 8600, '(42.19,22.33)', 'Vitosha', 2500, '(43.73,24.44)', 65);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ossam', 'Donau', '', '', 314, 2820, '(42.72,24.77)', 'Balkan', 1821, '(43.70,24.85)', 40);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Timiş', 'Donau', '', '', 340, 13085, '(45.29,22.59)', 'Southern Carpathians', 1700, '(44.85,20.63)', 72);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jiu', 'Donau', '', '', 385, 10070, '(45.28,22.82)', 'Southern Carpathians', 1320, '(43.78,23.81)', 23);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Olt', 'Donau', '', '', 615, 24010, '(46.65,25.8)', 'Eastern Carpathians', 1280, '(43.7,24.8)', 21);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Siret', 'Donau', '', '', 726, 44835, '(48.00,25.28)', 'Wooded Carpathians', 1238, '(45.41,28.02)', 5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pruth', 'Donau', '', '', 953, 27500, '(48.16,24.55)', 'Wooded Carpathians', 0, '(45.47,28.21)', 4);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Moraca', '', 'Lake Skutari', '', 99.5, 1600, '(42.85,19.25)', 'Dinaric Alps', 1600, '(42.25,19.15)', 7);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Neretva', '', '', 'Mediterranean Sea', 218, 5581, '(43.28,18.55)', 'Dinaric Alps', 1095, '(43.02,17.44)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Buna', '', '', 'Mediterranean Sea', 44, 5187, '(42.05,19.5)', '', 1, '(41.85,19.35)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Drin', '', '', 'Mediterranean Sea', 285, 19686, '(42.15,20.4)', 'Dinaric Alps', 0, '(41.8,19.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('White Drin', 'Drin', '', '', 136, 4964, '(42.7,20.2)', 'Dinaric Alps', 0, '(42.1,20.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Black Drin', 'Drin', '', '', 149, 3504, '(41.0,20.7)', '', 695, '(42.1,20.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vjosa', '', '', 'Mediterranean Sea', 272, 6706, '(39.79,21.15)', 'Pindos', 1400, '(40.64,19.82)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Acheloos', '', '', 'Mediterranean Sea', 217, 6329, '(39.67,21.15)', 'Pindos', 1550, '(38.33,21.10)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aliakmonas', '', '', 'Mediterranean Sea', 297, 8813, '(40.36,20.79)', 'Pindos', 2270, '(40.47,22.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vardar', '', '', 'Mediterranean Sea', 388, 24438, '(41.76,20.83)', '', 683, '(40.51,22.71)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Struma', '', '', 'Mediterranean Sea', 415, 17330, '(42.55,23.28)', 'Vitosha', 2180, '(40.79,23.85)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Maritsa', '', '', 'Mediterranean Sea', 525, 52900, '(42.16,23.64)', 'Rila', 2378, '(40.74,26.03)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tundzha', 'Maritsa', '', '', 365, 8430, '(42.73,24.97)', 'Balkan', 1940, '(41.66,26.56)', 40);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nachal HaKishon', '', '', 'Mediterranean Sea', 70, 1100, '(33.7,35.7)', '', 100, '(32.82,35.03)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nachal Sorek', '', '', 'Mediterranean Sea', 65, 722, '(31.88,35.19)', '', 750, '(31.94,34.71)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nachal HaBesor', '', '', 'Mediterranean Sea', 111, 3700, '(30.81,34.73)', '', 600, '(31.46,34.37)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jordan', '', 'Dead Sea', '', 251, 18000, '(33.7,35.7)', 'Jabal Lubnan', 80, '(31.3,35.5)', -422);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Litani', '', '', 'Mediterranean Sea', 140, 2290, '(34.01,36.10)', 'Jabal Lubnan', 1000, '(33.33,35.24)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Orontes', '', '', 'Mediterranean Sea', 571, 22300, '(34.2,36.35)', 'Jabal Lubnan', 910, '(36.04,35.96)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Seyhan', '', '', 'Mediterranean Sea', 516, 20700, '(37.92,35.53)', 'Taurus', 1750, '(36.72,34.91)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sakarya', '', '', 'Black Sea', 824, 53800, '(39.35,31.06)', 'Taurus', 1000, '(41.12,30.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kızılırmak', '', '', 'Black Sea', 1355, 78180, '(39.85,38.40)', '', 2250, '(41.74,35.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rioni', '', '', 'Black Sea', 327, 13400, '(42.87,43.36)', 'Caucasus', 2800, '(42.18,41.63)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Terek', '', 'Caspian Sea', '', 623, 43200, '(42.62,44.25)', 'Caucasus', 3200, '(43.59,47.36)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Samur', '', 'Caspian Sea', '', 213, 7330, '(41.88,46.79)', 'Caucasus', 3200, '(41.91,49.49)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kura', '', 'Caspian Sea', '', 1364, 218906, '(40.7,42.76)', 'Kurdistan', 2650, '(39.28,49.43)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aras', 'Kura', '', '', 1072, 102000, '(39.40,41.29)', 'Kurdistan', 2460, '(40.02,48.45)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hrazdan', 'Aras', '', '', 141, 2560, '(40.55,44.09)', '', 1904, '(39.99,44.45)', 797);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Schatt al Arab', '', '', 'Persian Gulf', 193, 950000, '(31.00,47.44)', '', 20, '(29.9,48.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tigris', 'Schatt al Arab', '', '', 1900, 375000, '(38.3,41.0)', 'Antitaurus', 0, '(31.00,47.44)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Euphrat', 'Schatt al Arab', '', '', 2736, 500000, '(38.8,38.75)', '', 820, '(31.00,47.44)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Murat', '', 'Lake Keban', '', 720, 40000, '(39.55,44.1)', 'Kurdistan', 2720, '(38.8,38.75)', 820);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Karasu', '', 'Lake Keban', '', 470, 22000, '(40.9,41.3)', 'Kurdistan', 1950, '(38.8,38.75)', 820);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Karun', 'Schatt al Arab', '', '', 950, 65230, '(32.35,50.1)', 'Zagros', 0, '(30.43,48.17)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sefid-Rud', '', 'Caspian Sea', '', 670, 13450, '(35.65,46.63)', 'Zagros', 2480, '(37.47,49.94)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Atrek', '', 'Caspian Sea', '', 669, 27300, '(37.17,58.78)', '', 1600, '(37.15,54.0)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Helmand', '', 'Lake Hamun', '', 1125, 386000, '(34.64,68.67)', 'Koh-e-Baba', 3800, '(31,61.25)', 500);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Northern Dwina', '', '', 'White Sea', 740, 357052, '(60.73,39.80)', '', 50, '(64.55,40.5333)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Suchona', 'Northern Dwina', '', '', 926, 50300, '(60.95,40.23)', '', 200, '(60.73,39.80)', 50);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vychegda', 'Northern Dwina', '', '', 1130, 121000, '(62.33,55.55)', '', 220, '(61.28,46.60)', 75);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pechora', '', '', 'Barents Sea', 1809, 322000, '(62,59)', 'Ural', 0, '(68.5,54)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Newa', '', '', 'Baltic Sea', 74, 281000, '(60.82,31.53)', '', 4, '(59.95,30.17)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Swir', '', 'Ozero Ladoga', '', 224, 84400, '(60.99,35.49)', '', 33, '(60.51,32.79)', 4);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Wyg', '', '', 'White Sea', 314, 27100, '(62.75,36.52)', '', 0, '(64.52,34.78)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Narva', '', '', 'Baltic Sea', 78, 56200, '(58.68,27.49)', '', 30, '(59.46,28.04)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Daugava', '', '', 'Baltic Sea', 1020, 87900, '(56,34)', 'Waldai Hills', 228, '(57,24.1)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dnister', '', '', 'Black Sea', 1352, 72100, '(49.2,22.93)', 'Wooded Carpathians', 1000, '(46.35,30.23)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('SouthernBug', '', '', 'Black Sea', 857, 63740, '(49.63,26.43)', '', 290, '(46.65,31.94)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Inhul', 'SouthernBug', '', '', 354, 9890, '(48.76,32.03)', '', 155, '(46.99,31.98)', 2);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dnepr', '', '', 'Black Sea', 2201, 531817, '(55.5,34)', 'Waldai Hills', 220, '(46.5257,32.252)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Berezina', 'Dnepr', '', '', 613, 24500, '(55.03,27.73)', '', 190, '(52.55,30.25)', 125);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sozh', 'Dnepr', '', '', 648, 42140, '(54.71,32.02)', '', 205, '(51.95,30.81)', 120);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Svislach', 'Berezina', '', '', 327, 5160, '(54.04,27.17)', '', 290, '(52.55,30.25)', 140);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Prypjat', '', 'Kiev Reservoir', '', 775, 114300, '(51.47,24.3)', '', 200, '(51.15,30.5)', 110);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Styr', 'Prypjat', '', '', 494, 13100, '(49.96,25.17)', '', 270, '(52.11,26.58)', 135);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Teteriv', '', 'Kiev Reservoir', '', 385, 15300, '(49.77,27.92)', '', 300, '(51.03,30.28)', 100);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Desna', 'Dnepr', '', '', 1130, 88900, '(54.59,33.30)', '', 240, '(50.55,30.54)', 95);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Seym', 'Desna', '', '', 748, 27500, '(51.16,37.23)', '', 178, '(51.46,32.56)', 112);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Psel', 'Dnepr', '', '', 717, 22800, '(51.14,36.75)', '', 220, '(49.02,33.53)', 104);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vorskla', 'Dnepr', '', '', 464, 14700, '(50.91,36.45)', '', 195, '(48.92,34.12)', 103);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Inhulets', 'Dnepr', '', '', 557, 14460, '(50.91,36.45)', '', 175, '(46.68,32.81)', 40);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kalmius', '', '', 'Sea of Azov', 209, 5070, '(48.12,37.87)', '', 220, '(47.08,37.58)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Don', '', '', 'Sea of Azov', 1870, 425600, '(54.0,38.26)', '', 180, '(47.1,39.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Donets', 'Don', '', '', 1053, 98900, '(50.95,36.90)', '', 200, '(47.60,40.90)', 6);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Manych', 'Don', '', '', 420, 35400, '(45.71,44.11)', '', 27, '(47.25,40.25)', 2);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('East Manych', '', 'Caspian Sea', '', 220, 12500, '(45.62,44.19)', '', 27, '(44.76,46.99)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oskol', 'Donets', '', '', 472, 14800, '(51.60,37.22)', '', 200, '(49.01,37.41)', 60);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kuban', '', '', 'Sea of Azov', 870, 57900, '(43.33,42.39)', '', 3400, '(45.34,37.40)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Volga', '', 'Caspian Sea', '', 3531, 1410000, '(57,33)', 'Waldai Hills', 228, '(46.733333333333,47.85)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oka', 'Volga', '', '', 1480, 245000, '(52.35,36.2)', '', 226, '(56.3,44)', 67);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Moskva', 'Oka', '', '', 502, 17600, '(55.49,35.40)', '', 270, '(55.07,38.85)', 100);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kama', '', 'Kuybyshev Reservoir', '', 1805, 507000, '(58.2,53.75)', '', 336, '(55.4,50.3)', 53);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vyatka', 'Kama', '', '', 1314, 129000, '(58.45,52.17)', '', 240, '(55.59,51.50)', 60);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chusovaya', '', 'Kama Reservoir', '', 592, 23000, '(56.16,60.35)', 'Ural', 356, '(58.16,56.39)', 108.5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Belaya', '', 'Lower Kama Reservoir', '', 1430, 142000, '(54.55,59.05)', 'Ural', 336, '(55.92,53.53)', 53);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ural', '', 'Caspian Sea', '', 2428, 244280, '(54.7,59.4)', 'Ural', 0, '(47.1,51.9)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Emba', '', 'Caspian Sea', '', 712, 40400, '(49.17,58.75)', '', 0, '(46.63,53.32)', -28);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ob', '', '', 'Kara Sea', 3650, 2972497, '(52.43,85.00)', '', 162, '(66.48,71.35)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Irtysh', 'Ob', '', '', 4248, 1673470, '(47.9,90.0)', 'Altai', 2930, '(61.07,68.93)', 23);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tobol', 'Irtysh', '', '', 1591, 426000, '(51.5,61.0)', 'Ural', 273, '(58.2,68.25)', 35);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tura', 'Tobol', '', '', 1030, 80400, '(58.39,59.40)', '', 400, '(57.21,66.95)', 42);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tagil', 'Tobol', '', '', 414, 10100, '(57.22,59.98)', '', 550, '(58.52,62.48)', 80);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Isset', 'Tobol', '', '', 606, 58900, '(56.95,60.40)', '', 250, '(56.60,66.29)', 51);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Miass', 'Isset', '', '', 658, 21800, '(54.77,59.62)', '', 600, '(56.09,64.50)', 66);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ishim', 'Irtysh', '', '', 2450, 177000, '(52,71.5)', '', 0, '(58,71.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Katun', 'Ob', '', '', 688, 60900, '(49.75,86.56)', 'Altai', 2000, '(52.43,85.00)', 162);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chulym', 'Ob', '', '', 2023, 134000, '(54.11,89.11)', '', 1200, '(57.73,83.82)', 65);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tom', 'Ob', '', '', 827, 62000, '(53.61,89.68)', '', 903, '(56.83,84.49)', 67);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yenissey', '', '', 'Kara Sea', 4092, 2554482, '(52.33,97.5)', 'Sayan Mountains', 1591, '(51.06,100.02)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Little Yenissey', 'Yenissey', '', '', 563, 58700, '(51.40,99.30)', '', 1538, '(51.73,94.35)', 619);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nizhnyaya Tunguska', 'Yenissey', '', '', 2989, 473000, '(58.04,105.68)', '', 565, '(65.78,87.96)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chantaika', 'Yenissey', '', '', 174, 30700, '(68.48,92.97)', 'Putorana Mountains', 800, '(68.11,86.55)', 18);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Angara', 'Yenissey', '', '', 2830, 1039000, '(56.6,113.75)', '', 1600, '(58.2,92.5)', 76);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Selenge', '', 'Ozero Baikal', '', 992, 447000, '(52,106)', 'Khangai Range', 1176, '(58.2,92.5)', 455);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Egiin Gol', 'Selenge', '', '', 535, 41800, '(50.42,100.15)', 'Sayan Mountains', 1624, '(49.39,103.62)', 823);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Orchon', 'Selenge', '', '', 1124, 132835, '(46.75,101.15)', 'Khangai Range', 0, '(50.25,106.15)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tuul', 'Orchon', '', '', 819, 49840, '(48.5,108.2)', 'Khentii Mountains', 1850, '(48.96,104.8)', 780);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pyasina', '', '', 'Kara Sea', 1000, 182000, '(68.94,92.39)', 'Putorana Mountains', 360, '(73.90,87.49)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Taimyra', '', '', 'Kara Sea', 840, 124000, '(74.15,94.13)', '', 150, '(76.11,99.79)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chatanga', '', '', 'Laptev Sea', 1636, 275000, '(69.07,94.87)', 'Putorana Mountains', 1220, '(73,115)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Olenyok', '', '', 'Laptev Sea', 2292, 219000, '(67.59,105.16)', '', 250, '(73.00,105.16)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lena', '', '', 'Laptev Sea', 4400, 2306772, '(53.99,107.88)', '', 1465, '(72.40,126.7)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vilyuy', 'Lena', '', '', 2650, 454000, '(65.96,103.51)', '', 520, '(64.33,126.41)', 54);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aldan', 'Lena', '', '', 2273, 729000, '(56.42,123.79)', 'Stanovoy Highlands', 0, '(63.44,129.55)', 72);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vitim', 'Lena', '', '', 1837, 225000, '(54.34,112.42)', 'Stanovoy Highlands', 1171, '(59.45,112.60)', 176);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Indigirka', '', '', 'East Sibirian Sea', 1726, 360000, '(61.90,142.44)', '', 790, '(70.82,148.90)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kolyma', '', '', 'East Sibirian Sea', 2513, 647000, '(62.3,147.7)', '', 0, '(69.63,161.49)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Anadyr', '', '', 'Bering Sea', 1150, 191000, '(67.05,170.84)', '', 0, '(64.73,177.52)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kamchatka', '', '', 'Pacific Ocean', 758, 55900, '(54.25,157.53)', '', 1050, '(56.20,162.48)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Amur', '', '', 'Sea of Okhotsk', 2824, 1855000, '(53.33,121.48)', '', 305, '(53.1,140.73)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Schilka', 'Amur', '', '', 560, 206000, '(51.7,115.84)', '', 498, '(53.33,121.48)', 305);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ingoda', 'Schilka', '', '', 708, 37200, '(49.7,111.05)', '', 2000, '(51.7,115.84)', 498);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Onon', 'Schilka', '', '', 1032, 96200, '(48.84,108.8)', 'Khentii Mountains', 0, '(51.7,115.84)', 498);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Argun', 'Amur', '', '', 1620, 164000, '(49.94,122.46)', '', 1200, '(53.33,121.48)', 305);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Songhua', 'Amur', '', '', 1927, 550000, '(42.62,127.2)', 'Changbai', 0, '(47.7,132.52)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sungacha', 'Ussuri', '', '', 180, 25600, '(45.06,132.85)', '', 70, '(45.57,133.41)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ussuri', 'Amur', '', '', 897, 193000, '(43.75,134.44)', 'Sikhote-Alin', 1300, '(48.45,135.06)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kherlen', '', 'Hulun Nur', '', 1264, 116400, '(48.8,109.2)', 'Khentii Mountains', 0, '(48.75,117.05)', 539);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Syrdarja', '', 'North Aral Sea', '', 2212, 782669, '(40.9,71.75)', '', 400, '(46,60.5)', 40);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Naryn', 'Syrdarja', '', '', 678, 59100, '(41.8,77.5)', 'Tian Shan', 0, '(40.9,71.75)', 400);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Amudarja', '', '', '', 1415, 465000, '(37.1,68.3)', '', 310, '(44,59)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vakhsh', 'Amudarja', '', '', 786, 39100, '(39.74,73.63)', 'Pamir', 3500, '(37.1,68.3)', 310);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pjandsh', 'Amudarja', '', '', 921, 114000, '(37.28,73.67)', 'Pamir', 4520, '(37.1,68.3)', 310);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bartang', 'Pjandsh', '', '', 528, 24700, '(37.35,74.4)', 'Pamir', 4015, '(37.9,71.6)', 1979);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ili', '', 'Ozero Balchash', '', 1001, 140000, '(43.58,82.55)', '', 800, '(45.4,74.14)', 340);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Künes', 'Ili', '', '', 220, 3532, '(43.21,84.85)', 'Tian Shan', 2800, '(43.58,82.55)', 800);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tekes', 'Ili', '', '', 438, 29600, '(42.55,79.65)', 'Tian Shan', 3300, '(43.58,82.55)', 800);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tarim-Yarkend', '', 'Lop Nor', '', 3260, 951500, '(33.5,80.5)', 'Karakorum', 0, '(40.2,90.6)', 780);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tumen', '', '', 'Sea of Japan', 521, 41200, '(41.97,128.2)', 'Changbai', 2000, '(42.43,130.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yalu', '', '', 'Yellow Sea', 813, 30000, '(42.0,128.1)', 'Changbai', 2500, '(39.8,124.3)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Taedong', '', '', 'Yellow Sea', 439, 20344, '(40.33,126.93)', '', 1700, '(38.69,125.21)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nakdonggang', '', '', 'Sea of Japan', 526, 23384, '(37.09,129.04)', 'Taebaek', 540, '(35.05,128.93)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Namhangang', '', '', 'Yellow Sea', 494, 35770, '(37.23,128.98)', 'Taebaek', 850, '(37.75,126.18)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bukhangang', 'Namhangang', '', '', 325, 11343, '(38.65,128.11)', 'Taebaek', 1120, '(37.53,127.31)', 30);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Geumgang', '', '', 'Yellow Sea', 401, 9859, '(35.59,127.50)', '', 530, '(36.00,126.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ishikari', '', '', 'Pacific Ocean', 268, 14330, '(43.54,143.00)', '', 1400, '(43.27,141.38)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Shinano', '', '', 'Sea of Japan', 367, 11900, '(35.91,138.72)', '', 2180, '(34.68,135.42)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tone', '', '', 'Pacific Ocean', 322, 16840, '(37.05,139.10)', '', 1600, '(35.74,140.85)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kitakami', '', '', 'Pacific Ocean', 249, 10150, '(40.07,141.16)', '', 720, '(38.41,141.31)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yodo', '', '', 'Seto Inland Sea', 75, 8240, '(34.99,135.91)', '', 85, '(34.68,135.42)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kushiro', '', '', 'Pacific Ocean', 154, 2510, '(43.56,144.33)', '', 121, '(42.98,144.37)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tamsui', '', '', 'East China Sea', 159, 2726, '(24.43,121.27)', '', 3300, '(25.18,121.41)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gaoping', '', '', 'South China Sea', 171, 3257, '(23.48,120.04)', '', 3400, '(22.49,120.58)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Liao He', '', '', 'Yellow Sea', 1390, 232000, '(42.9,116.95)', '', 0, '(40.91,121.81)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Huang He', '', '', 'Yellow Sea', 4845, 752000, '(35.31,96.23)', 'Kunlun', 4500, '(37.74,119.14)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Wei He', 'Huang He', '', '', 818, 107000, '(35.0,104.04)', '', 0, '(34.6,110.3)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Huai', '', '', 'Yellow Sea', 1110, 174000, '(32.4,113.3)', 'Qin Ling', 0, '(34.25,120.27)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yangtze', '', '', 'East China Sea', 6380, 1722155, '(33.5,91.2)', 'Tanggula Shan', 5405, '(32,121.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Han', 'Yangtze', '', '', 1532, 174300, '(33.14,106.82)', 'Qin Ling', 580, '(30.55,114.3)', 75);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gan Jiang', 'Yangtze', '', '', 758, 81600, '(24.50,114.42)', 'Nanling', 850, '(29.75,116.21)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Xiang Jiang', '', 'Dongting Hu', '', 856, 96400, '(26.61,110.61)', 'Nanling', 500, '(29.44,113.14)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yuan Jiang', '', 'Dongting Hu', '', 1033, 89163, '(26.31,107.33)', 'Nanling', 1700, '(28.85,112.24)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pearl River', '', '', 'South China Sea', 170, 453700, '(23.25,113.2)', '', 1, '(22.1,113.75)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Dong Jiang', 'Pearl River', '', '', 523, 32000, '(24.4,115.2)', '', 0, '(23.04,113.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bei Jiang', 'Xi Jiang', '', '', 468, 46700, '(24.8,113.6)', 'Nanling', 0, '(23.15,112.8)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Xi Jiang', '', '', 'South China Sea', 2197, 353100, '(25.77,103.9)', '', 2000, '(22.05,113.48)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hong He', '', '', 'South China Sea', 1149, 170977, '(25.8,101.3)', '', 1776, '(20.27,106.55)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mekong', '', '', 'South China Sea', 4350, 795000, '(33.75,94.66)', 'Tanggula Shan', 5374, '(10.19,106.75)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tonle Sap River', 'Mekong', '', '', 120, 0, '(12.50,104.56)', '', 0.5, '(11.56,104.94)', 0.3);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mae Nam Chao Phraya', '', '', 'Gulf of Thailand', 372, 160000, '(15.7,100.14)', '', 33, '(13.54,100.59)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mae Nam Ping', 'Mae Nam Chao Phraya', '', '', 658, 44688, '(19.81,98.83)', 'Shan Highlands', 1350, '(15.7,100.14)', 33);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mae Nam Nan', 'Mae Nam Chao Phraya', '', '', 740, 57947, '(19.3,101.2)', 'Shan Highlands', 1240, '(15.7,100.14)', 33);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saluen', '', '', 'Andaman Sea', 2980, 320000, '(32.5,91.9)', 'Tanggula Shan', 5450, '(17,97.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Irawaddy', '', '', 'Andaman Sea', 2170, 413674, '(29,98)', 'Hengduan Shan', 4300, '(17,96)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ganges', '', '', 'Gulf of Bengal', 2620, 1750000, '(30.93,79.06)', 'Himalaya', 3892, '(22,90)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ghaghara', 'Ganges', '', '', 1080, 127950, '(30.56,80.68)', 'Himalaya', 5400, '(25.74,84.68)', 35);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gandaki', 'Ganges', '', '', 400, 46300, '(27.74,84.42)', 'Himalaya', 190, '(25.65,85.18)', 44);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kali Gandaki', 'Gandaki', '', '', 350, 11863, '(29.29,83.82)', 'Himalaya', 6268, '(27.74,84.42)', 190);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Trishuli', 'Gandaki', '', '', 300, 11688, '(28.43,85.16)', 'Himalaya', 4100, '(27.74,84.42)', 190);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Koshi', 'Ganges', '', '', 300, 86900, '(26.91,87.16)', 'Himalaya', 150, '(25.4,87.26)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sunkoshi', 'Koshi', '', '', 430, 18182, '(28.46,86.32)', 'Himalaya', 0, '(26.91,87.16)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Arun', 'Koshi', '', '', 500, 33578, '(28.68,85.88)', 'Himalaya', 4700, '(26.91,87.16)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yamuna', 'Ganges', '', '', 1376, 366223, '(31.0,78.45)', 'Himalaya', 6246, '(25.4,81.86)', 74);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lualaba', 'Congo', '', '', 0, 0, '(-12,27)', '', 1400, '(0.5,25.2)', 401);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chambal', 'Yamuna', '', '', 960, 132508, '(22.47,75.63)', 'Vindhya Range', 854, '(26.5,79.25)', 122);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Brahmaputra', 'Ganges', '', '', 2896, 651334, '(31.06,81.33)', 'Himalaya', 5750, '(23.8,89.8)', 6);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Raidak', 'Brahmaputra', '', '', 370, 15300, '(27.69,89.44)', 'Himalaya', 4900, '(25.98,89.81)', 36);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jaldhaka', 'Brahmaputra', '', '', 250, 4800, '(27.33,88.89)', 'Himalaya', 4300, '(25.75,89.71)', 26);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tista', 'Brahmaputra', '', '', 430, 12540, '(28.00,88.81)', 'Himalaya', 5303, '(25.47,89.67)', 16);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Meghna', 'Ganges', '', '', 910, 82000, '(25.47,94.29)', 'Patkai Mountains', 2060, '(23.24,90.63)', 0.5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Godavari', '', '', 'Gulf of Bengal', 1465, 313390, '(13.93,73.53)', 'Western Ghats', 1200, '(16.74,82.35)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mahanadi', '', '', 'Gulf of Bengal', 851, 141600, '(20.19,81.96)', '', 442, '(20.29,86.71)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Krishna', '', '', 'Gulf of Bengal', 1291, 258950, '(17.9,73.4)', 'Western Ghats', 1337, '(15.71,80.93)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Narmada', '', '', 'Arabian Sea', 1312, 98800, '(22.76,81.75)', 'Satpura Range', 1057, '(21.57,72.70)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Indus', '', '', 'Arabian Sea', 3180, 980000, '(32.45,79.7)', 'Transhimalaya', 5300, '(24,67.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kabul', 'Indus', '', '', 71, 70500, '(34.35,68.5)', '', 3230, '(33.9,72.23)', 280);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Panjnad', 'Indus', '', '', 71, 540000, '(29.35,71.02)', '', 120, '(29.11,70.7)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Satluj', 'Panjnad', '', '', 1500, 395000, '(30.67,81.47)', 'Transhimalaya', 4586, '(29.35,71.02)', 120);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chanab', 'Panjnad', '', '', 1242, 138000, '(32.55,76.98)', 'Himalaya', 2286, '(29.35,71.02)', 120);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jhelum', 'Chanab', '', '', 720, 55300, '(33.75,75.38)', 'Himalaya', 3400, '(31.17,72.15)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ravi', 'Chanab', '', '', 725, 0, '(32.38,77.02)', 'Himalaya', 4100, '(30.62,71.82)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mahaweli', '', '', 'Gulf of Bengal', 335, 10448, '(6.89,80.58)', '', 1280, '(8.46,81.23)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Asahan', '', '', 'Malakka Strait', 147, 3741, '(2.7,98.7)', 'Barisan Mountains', 905, '(3.1,99.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Batang Hari', '', '', 'South China Sea', 800, 46504, '(-1.1,100.78)', 'Barisan Mountains', 1531, '(-1.06,104.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Solo', '', '', 'Java Sea', 600, 16100, '(-7.74,111.15)', '', 1230, '(-6.85,112.55)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rajang', '', '', 'South China Sea', 563, 50000, '(2.45,115.09)', 'Iran Mountains', 1050, '(2.13,113.22)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kapuas', '', '', 'South China Sea', 1143, 98749, '(1.39,114.16)', 'Müller-Schwaner Range', 1180, '(-9.55,109.09)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mahakam', '', '', 'Java Sea', 980, 77100, '(1.36,114.59)', 'Müller-Schwaner Range', 1200, '(-0.80,117.46)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Barito', '', '', 'Java Sea', 1090, 81675, '(0.73,114.97)', 'Müller-Schwaner Range', 950, '(-3.40,114.23)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pansipit River', '', '', 'South China Sea', 9, 0, '(13.93,120.93)', '', 5, '(13.88,120.91)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pasig River', '', '', 'South China Sea', 27, 4678, '(14.53,121.11)', '', 1, '(14.58,120.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Agus River', '', '', 'Sulu Sea', 37, 1645, '(7.89,124.25)', '', 700, '(8.20,124.19)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mamberano', '', '', 'Pacific Ocean', 1112, 78992, '(-4.64,140.80)', 'Maoke Range', 1900, '(-1.47,137.90)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Digul', '', '', 'Arafura Sea', 853, 45900, '(-4.65,140.29)', 'Maoke Range', 3660, '(-7.12,138.70)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sepik', '', '', 'Pacific Ocean', 1126, 100243, '(-5.22,141.82)', 'Maoke Range', 2170, '(-3.84,144.54)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Fly River', '', '', 'Coral Sea', 1120, 76000, '(-5.30,141.52)', 'Maoke Range', 0, '(-8.53,143.52)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ruggles River', '', '', 'Arctic Ocean', 22, 0, '(81.75,-71.05)', '', 668, '(81.7,-69.3)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Koukdjuak River', '', '', 'Arctic Ocean', 80, 108000, '(66.58,-71.36)', '', 30, '(66.74,-73.06)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yukon River', '', '', 'Bering Sea', 3185, 854700, '(60.54,-134.5)', '', 668, '(62.57,-163.98)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Newhalen River', '', 'Iliamna Lake', '', 40, 9000, '(59.95,-154.86)', 'Alaska Range', 77, '(59.71,-154.89)', 14);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kvichak River', '', '', 'Bering Sea', 97, 16830, '(59.83,-155.88)', 'Alaska Range', 14, '(58.88,-157.04)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Fraser River', '', '', 'Pacific Ocean', 1375, 248035, '(52.52,-118.32)', 'Rocky Mountains', 2145, '(49.12,-123.19)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mackenzie River', '', '', 'Arctic Ocean', 1903, 1805200, '(61.7,-113.9)', '', 156, '(69.20,-135.02)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Great Bear River', 'Mackenzie River', '', '', 113, 156500, '(65.13,-123.51)', '', 186, '(64.91,-125.60)', 60);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Slave River', '', 'Great Bear Lake', '', 434, 616400, '(59.00,-114.41)', '', 213, '(61.28,-113.59)', 186);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Athabasca River', '', 'Lake Athabasca', '', 1231, 95300, '(52.17,-117.43)', 'Rocky Mountains', 1520, '(58.62,-110.83)', 213);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Peace River', '', 'Lake Athabasca', '', 1923, 95300, '(57.07,-126.89)', 'Rocky Mountains', 1140, '(59.00,-111.41)', 213);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Liard River', 'Mackenzie River', '', '', 1115, 277100, '(61.2,-131.6)', '', 1500, '(61.85,-121.3)', 120);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nelson River', '', '', 'Hudson Bay', 664, 1093442, '(52.77,-97.97)', '', 218, '(57.15,-92.33)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saskatchewan River', '', 'Lake Winnipeg', '', 547, 335900, '(53.24,-105.08)', '', 380, '(52.77,-97.97)', 218);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('North Saskatchewan River', 'Saskatchewan River', '', '', 1287, 122800, '(52.15,-117.18)', 'Rocky Mountains', 2080, '(53.24,-105.08)', 380);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('South Saskatchewan River', 'Saskatchewan River', '', '', 1392, 146100, '(51.64,-116.51)', 'Rocky Mountains', 1960, '(53.24,-105.08)', 380);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Red River of the North', '', 'Lake Winnipeg', '', 877, 287500, '(46.26,-96.60)', '', 290, '(50.40,-96.80)', 218);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Churchill River', '', '', 'Labrador Sea', 856, 93415, '(53.0,-66.25)', '', 529, '(53.36,-60.17)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saint Lawrence River', '', '', 'Atlantic Ocean', 1197, 1030000, '(44.2,-76.55)', '', 75, '(49.6,-64.8)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ottawa River', 'Saint Lawrence River', '', '', 1271, 146300, '(47.6,-75.8)', '', 430, '(45.45,-74.1)', 20);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Niagara River', '', 'Lake Ontario', '', 58, 684000, '(42.9,-78.9)', '', 174, '(43.25,-79.1)', 75);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Detroit River', '', 'Lake Erie', '', 200, 579000, '(42.1,-82.6)', '', 176, '(43,-82.2)', 174);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saint Marys River', '', 'Lake Huron', '', 120, 127700, '(46.5,-84.6)', '', 184, '(46.6,-83.9)', 176);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Manitou River', '', 'Lake Huron', '', 15, 0, '(45.70,-82.00)', '', 215, '(45.60,-82.10)', 176);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mindemoya River', '', 'Lake Huron', '', 8, 0, '(45.71,-82.23)', '', 200, '(45.67,-82.27)', 176);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Straits of Mackinac', '', 'Lake Huron', '', 0.1, 118000, '(45.8,-84.75)', '', 176, '(45.8,-84.75)', 176);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nipigon River', '', 'Lake Superior', '', 48, 25400, '(49.44,-88.21)', '', 260, '(48.96,-88.25)', 186);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Manicouagan River', 'Saint Lawrence River', '', '', 200, 45800, '(51.10,-68.71)', '', 350, '(49.18,-68.19)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Riviere Richelieu', 'Saint Lawrence River', '', '', 124, 23400, '(45,-73.3)', '', 30, '(46.0,-73.1)', 4);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Merrimack River', '', '', 'Atlantic Ocean', 177, 12900, '(43.4,-71.6)', '', 153, '(42.82,-70.81)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Connecticut River', '', '', 'Atlantic Ocean', 655, 29125, '(45.25,-71.21)', '', 667, '(41.27,-72.33)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hudson River', '', '', 'Atlantic Ocean', 493, 5405, '(44.1,-73.95)', 'Adirondacks', 1309, '(40.7,-74.0)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Delaware River', '', '', 'Atlantic Ocean', 735, 36568, '(42.45,-74.60)', 'Appalachian Mountains', 730, '(39.43,-75.43)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Susquehanna River', '', '', 'Atlantic Ocean', 715, 71225, '(42.7,-74.92)', 'Appalachian Mountains', 360, '(39.54,-76.08)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Potomac River', '', '', 'Atlantic Ocean', 652, 38073, '(39.2,-79.5)', 'Appalachian Mountains', 933, '(38.00,-76.25)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Savannah River', '', '', 'Atlantic Ocean', 560, 38073, '(34.44,-82.86)', 'Appalachian Mountains', 201, '(32.04,-80.85)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Caloosahatchee River', '', '', 'Gulf of Mexico', 108, 3570, '(26.96,-81.07)', '', 4, '(26.52,-82.03)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mississippi', '', '', 'Gulf of Mexico', 3778, 2981076, '(47.25,-95.2)', '', 512, '(29.15,-89.25)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Missouri', 'Mississippi', '', '', 4130, 1371010, '(45.9,-111.5)', '', 1232, '(38.81,-90.12)', 123);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Platte River', 'Missouri', '', '', 499, 233100, '(41.12,-100.68)', '', 845, '(41.06,-95.86)', 287);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('North Platte River', 'Platte River', '', '', 1094, 80031, '(40.68,-106.4)', 'Rocky Mountains', 2456, '(41.12,-100.68)', 845);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('South Platte River', 'Platte River', '', '', 711, 0, '(39.06,-105.78)', 'Rocky Mountains', 2675, '(41.12,-100.68)', 845);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Arkansas', 'Mississippi', '', '', 2334, 435122, '(39.25,-106.3)', '', 4260, '(34,-91)', 33);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ohio River', 'Mississippi', '', '', 1579, 490574, '(40.42,-80.0)', '', 222, '(36.98,-89.13)', 88);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Allegheny River', 'Ohio River', '', '', 523, 29992, '(41.9,-77.9)', 'Appalachian Mountains', 759, '(40.42,-80.0)', 222);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tennessee River', 'Ohio River', '', '', 1049, 105870, '(35.95,-83)', 'Appalachian Mountains', 248, '(37.07,-88.63)', 92);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Columbia River', '', '', 'Pacific Ocean', 1953, 668217, '(50.2,-115.85)', 'Rocky Mountains', 808, '(46.24,-124.06)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Clark Fork River', 'Columbia River', '', '', 708, 66800, '(46.19,-112.77)', 'Rocky Mountains', 1462, '(48.18,-116.27)', 626);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chelan River', 'Columbia River', '', '', 6.5, 2393, '(47.83,-120.01)', 'Rocky Mountains', 335, '(47.81,-119.98)', 217);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Snake River', 'Columbia River', '', '', 1735, 280000, '(44.13,-110.22)', 'Rocky Mountains', 2723, '(46.19,-119.03)', 104);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Salmon River', 'Snake River', '', '', 684, 36000, '(43.80,-114.75)', 'Rocky Mountains', 2810, '(45.86,-116.79)', 280);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Klamath River', '', '', 'Pacific Ocean', 423, 40632, '(42.19,-122.77)', 'Rocky Mountains', 1247, '(41.55,-124.08)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sacramento River', '', '', 'San Francisco Bay', 607, 69930, '(41.27,-122.41)', '', 1120, '(38.08,-121.85)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Feather River', 'Sacramento River', '', '', 350, 16000, '(40.36,-121.45)', '', 1657, '(38.78,-121.62)', 8);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('San Joaquin River', '', '', 'San Francisco Bay', 530, 83000, '(37.1,-118.74)', '', 3354, '(38.05,-121.85)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Truckee River', '', 'Pyramid Lake', '', 225, 7900, '(39,-120)', '', 1900, '(39.85,-119.43)', 1155);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Humboldt River', '', '', '', 467, 42994, '(41.12,-114.97)', '', 1713, '(39.99,-118.61)', 1187);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Amargosa River', '', '', '', 185, 14245, '(37.07,-116.69)', '', 368, '(36.24,-116.86)', -85);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bear River', '', 'Great Salt Lake', '', 563, 18200, '(40.87,-110.83)', '', 2594, '(41.46,-112.29)', 1284);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jordan River', '', 'Great Salt Lake', '', 82.7, 9920, '(40.36,-111.90)', '', 1368, '(40.90,-111.98)', 1284);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Colorado', '', '', 'Gulf of California', 2330, 629100, '(40.35,-105.7)', '', 2700, '(31.81,-114.80)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gila River', 'Colorado', '', '', 1044, 150737, '(33.18,-108.21)', '', 1692, '(32.72,-114.55)', 36);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Green River', 'Colorado', '', '', 1175, 124578, '(43.15,-109.67)', '', 1692, '(38.19,-109.49)', 1181);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Brazos River', '', '', 'Gulf of Mexico', 1352, 116000, '(33.27,-100.01)', '', 452, '(28.88,-95.38)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Grande del Norte', '', '', 'Gulf of Mexico', 3034, 607965, '(38,-107.5)', '', 3900, '(25.96,-97.18)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Lerma Santiago', '', '', 'Pacific Ocean', 1281, 72427, '(19,-99)', '', 2600, '(21.5,-105.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Usumacinta', '', '', 'Gulf of Mexico', 1000, 240000, '(14.98,-91.22)', 'Sierra Madre de Chiapas', 2140, '(18.59,-92.69)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Grijalva', 'Rio Usumacinta', '', '', 480, 134400, '(15.63,-91.75)', '', 2200, '(18.40,-92.65)', 0.5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Belize River', '', '', 'Caribbean Sea', 290, 5000, '(16.46,-89.22)', '', 800, '(17.53,-88.23)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Dulce', '', '', 'Caribbean Sea', 43, 3435, '(15.64,-88.99)', '', 1.5, '(15.82,-88.75)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Motagua', '', '', 'Caribbean Sea', 486, 12670, '(14.95,-91.01)', 'Sierra Madre de Chiapas', 1800, '(15.74,-88.26)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Lempa', '', '', 'Pacific Ocean', 422, 18246, '(14.69,-89.30)', 'Sierra Madre de Chiapas', 1200, '(13.25,-88.83)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Patuca', '', '', 'Caribbean Sea', 500, 23900, '(13.79,-86.47)', '', 1150, '(15.81,-84.30)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Coco', '', '', 'Caribbean Sea', 750, 24767, '(13.37,-86.81)', '', 1160, '(15.00,-83.14)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio San Juan', '', '', 'Caribbean Sea', 199, 35000, '(11.60,-85.35)', '', 31, '(10.9,-83.7)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Chepo', '', '', 'Pacific Ocean', 206, 5292, '(9.09,-78.13)', '', 260, '(9.00,-79.11)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Cauto', '', '', 'Caribbean Sea', 343, 8948, '(20.0,-76.2)', '', 600, '(20.55,-77.24)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Artibonito', '', '', 'Caribbean Sea', 343, 8948, '(18.76,-71.52)', '', 630, '(19.24,-72.78)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Guayas', '', '', 'Pacific Ocean', 389, 53299, '(-0.25,-80)', 'Cordillera Occidental', 200, '(-2.65,-79.91)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Magdalena', '', '', 'Caribbean Sea', 1538, 263858, '(1.93,-76.66)', 'Andes', 3685, '(10.95,-74.8)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Cauca', 'Rio Magdalena', '', '', 1180, 59840, '(2.12,-76.43)', 'Andes', 3350, '(8.89,-74.47)', 15);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Bogota', 'Rio Magdalena', '', '', 375, 5996, '(5.22,-76.43)', 'Andes', 3300, '(4.28,-73.52)', 260);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Catatumbo', '', '', 'Lago de Maracaibo', 500, 22317, '(7.85,-73.13)', 'Andes', 2000, '(9.35,-71.74)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Orinoco', '', '', 'Atlantic Ocean', 2010, 1000000, '(2.3,-63.35)', 'Sierra Parima', 1047, '(8.56,-60.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Arauca', 'Orinoco', '', '', 1050, 34000, '(6.69,-72.30)', '', 3970, '(7.50,-66.51)', 37);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Apure', 'Orinoco', '', '', 1038, 167000, '(7.43,-72.30)', '', 2400, '(7.60,-66.41)', 36);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Meta', 'Orinoco', '', '', 1200, 111000, '(4.76,-73.84)', '', 3500, '(6.20,-66.46)', 50);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Guaviare', 'Orinoco', '', '', 1497, 166000, '(2.58,-67.71)', '', 225, '(4.04,-67.71)', 65);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Essequibo', '', '', 'Atlantic Ocean', 1010, 156828, '(2.3,-63.35)', 'Sierra Parima', 265, '(7.03,-58.45)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Suriname', '', '', 'Atlantic Ocean', 480, 23100, '(-3.32,-56.21)', '', 200, '(5.92,-55.17)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oyapock', '', '', 'Atlantic Ocean', 370, 26820, '(-2.03,-53.13)', '', 270, '(4.29,-51.62)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Amazonas', '', '', 'Atlantic Ocean', 3778, 7050000, '(-4.44,-73.45)', '', 88, '(0,-50)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Negro', 'Amazonas', '', '', 2866, 720114, '(-2.00,-70.00)', '', 200, '(-3.1,-60)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Japura', 'Amazonas', '', '', 2816, 255700, '(1.8,-76.6)', 'Andes', 0, '(-3.17,-64.77)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Putumayo', 'Amazonas', '', '', 1813, 148000, '(0.93,-77)', 'Andes', 0, '(-3.14,-67.97)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Maranon', 'Amazonas', '', '', 1905, 382877, '(-10.00,-76.66)', 'Cordillera Blanca', 5800, '(-4.44,-73.45)', 88);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Huallaga', 'Maranon', '', '', 1138, 85000, '(-10.50,-76.3)', 'Andes', 5800, '(-5.1,-75.62)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ucayali', 'Amazonas', '', '', 1600, 337519, '(-10.7,-73.75)', 'Cordillera Vilcanota', 287, '(-4.44,-73.45)', 88);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Urubamba', 'Ucayali', '', '', 750, 60300, '(-14.48,-71.00)', 'Andes', 0, '(-10.7,-73.75)', 287);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tambo', 'Ucayali', '', '', 160, 135000, '(-11.15,-74.23)', 'Andes', 295, '(-10.7,-73.75)', 287);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Perene', 'Tambo', '', '', 165, 20550, '(-10.95,-75.27)', 'Andes', 650, '(-11.15,-74.23)', 295);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ene', 'Tambo', '', '', 180, 106150, '(-12.26,-73.97)', 'Andes', 400, '(-11.15,-74.23)', 295);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mantaro', 'Tambo', '', '', 724, 15410, '(-10.92,-76.27)', 'Andes', 4082, '(-12.26,-73.97)', 400);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Apurimac', 'Tambo', '', '', 730, 66100, '(-15.24,-71.84)', 'Andes', 5020, '(-12.26,-73.97)', 400);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jurua', 'Amazonas', '', '', 3283, 225828, '(-9.76,-72.06)', '', 260, '(-2.63,-65.75)', 36);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Purus', 'Amazonas', '', '', 3210, 371042, '(-10.9,-72.35)', '', 0, '(-3.68,-61.48)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Acre', 'Purus', '', '', 1000, 35400, '(-11,-70.7)', '', 0, '(-8.75,-67.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Madeira', 'Amazonas', '', '', 1450, 1420000, '(-10.64,-65.65)', '', 180, '(-3.4,-58.76)', 40);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Beni', 'Rio Madeira', '', '', 1600, 280000, '(-17.67,-66.8)', 'Andes', 4324, '(-10.4,-66.73)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Madre de Dios', 'Beni', '', '', 1210, 125287, '(-12.0,-72.15)', 'Cordillera Vilcanota', 4000, '(-11.0,-66.1)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Mamoré', 'Rio Madeira', '', '', 1170, 650000, '(-17.62,-64.97)', 'Cordillera Central', 3400, '(-10.38,-65.39)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Guapay', 'Rio Mamoré', '', '', 1438, 102600, '(-18.42,-65.34)', 'Cordillera Central', 3693, '(-15.80,-64.73)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Guaporé', 'Rio Mamoré', '', '', 1260, 341000, '(-14.60,-58.95)', '', 631, '(-11.89,-65.03)', 131);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tapajós', 'Amazonas', '', '', 810, 489600, '(-7.35,-58.03)', '', 95, '(-2.41,-54.71)', 1);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Juruena', 'Tapajós', '', '', 1240, 190940, '(-14.75,-59.06)', '', 600, '(-7.35,-58.03)', 95);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Teles Pires', 'Tapajós', '', '', 1431, 141472, '(-14.85,-54.53)', '', 780, '(-7.35,-58.03)', 95);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Xingu', 'Amazonas', '', '', 1980, 520292, '(-11.94,-53.55)', '', 275, '(-1.5,-51.87)', 0.5);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tocantins', '', '', 'Atlantic Ocean', 2450, 749200, '(-16,-49)', '', 1070, '(-1.73,-49.16)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Araguaia', 'Tocantins', '', '', 2198, 384800, '(-17.97,-53.07)', 'Brazilian Highlands', 760, '(-5.37,-48.73)', 89);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Parnaiba', '', '', 'Atlantic Ocean', 1716, 322823, '(-10.35,-46.0)', '', 700, '(-2.75,-41.82)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Sao Francisco', '', '', 'Atlantic Ocean', 2830, 617812, '(-20.3,-43)', 'Brazilian Highlands', 1200, '(-10.5,-36.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Paraiba do Sul', '', '', 'Atlantic Ocean', 1137, 56500, '(-23.2,-44.9)', 'Serra do Mar', 1560, '(-21.6,-41.0)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Parana', '', '', 'Atlantic Ocean', 2640, 2582672, '(-20.38,-51.35)', '', 328, '(-34.5,-58.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Paranaiba', '', 'Represa de Ilha Solteira', '', 1070, 34400, '(-19.22,-46.17)', 'Brazilian Highlands', 1148, '(-20.07,-51.0)', 328);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Grande', '', 'Represa de Ilha Solteira', '', 1360, 143000, '(-22.3,-44.6)', 'Brazilian Highlands', 1950, '(-20.07,-51.0)', 328);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tiete', 'Parana', '', '', 1130, 150000, '(-23.55,-45.8)', 'Serra do Mar', 860, '(-20.6,-51.55)', 280);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Paranapanema', 'Parana', '', '', 929, 0, '(-24.3,-48.3)', 'Serra do Mar', 800, '(-22.65,-53.1)', 233);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Iguacu', 'Parana', '', '', 1320, 62000, '(-25.4,-49.0)', 'Serra do Mar', 1200, '(-25.6,-54.6)', 110);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Paraguay', 'Parana', '', '', 2549, 1168540, '(-14.5,-56.5)', '', 208, '(-27.3,-58.4)', 50);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pilcomayo', 'Paraguay', '', '', 2425, 272000, '(-19.4,-66.2)', 'Cordillera Central', 3950, '(-25.27,-57.67)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Cuiabá', 'Paraguay', '', '', 980, 102750, '(-14.21,-55.07)', '', 530, '(-17.90,-57.46)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Salado', 'Parana', '', '', 2355, 124199, '(-24.43,-66.20)', 'Andes', 5959, '(-31.66,-60.74)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Uruguay', '', '', 'Atlantic Ocean', 1790, 297199, '(-27.5,-52)', '', 1800, '(-33.9,-58.4)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Sali', '', 'Laguna Mar Chiquita', '', 812, 89936, '(-26.12,-65.62)', 'Andes', 1920, '(-27.53,-64.89)', 71);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Colorado', '', '', 'Atlantic Ocean', 1114, 350000, '(-36.15,-70.40)', 'Andes', 1800, '(-39.71,-72.13)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Salado del Oeste', 'Río Colorado', '', '', 1498, 300000, '(-27.79,-68.60)', 'Andes', 5500, '(-38.82,-64.99)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Neuquen', '', '', 'Atlantic Ocean', 1030, 102000, '(-36.18,-70.57)', 'Andes', 2800, '(-41.03,-62.78)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Limay', 'Río Neuquen', '', '', 380, 61723, '(-41.04,-71.15)', 'Andes', 770, '(-43.34,-65.06)', 255);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Chubut', '', '', 'Atlantic Ocean', 820, 53801, '(-41.49,-71.14)', 'Andes', 173, '(-43.34,-65.06)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Deseado', '', '', 'Atlantic Ocean', 615, 14450, '(-46.22,-71.46)', 'Andes', 700, '(-47.76,-65.90)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Santa Cruz', '', '', 'Atlantic Ocean', 385, 29686, '(-50.23,-72.53)', 'Andes', 187, '(-50.13,-68.35)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Rimac', '', '', 'Pacific Ocean', 138, 3583, '(-11.58,-76.26)', 'Cordillera Occidental', 4700, '(-12.03,-77.15)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Desaguadero', '', 'Poopo', '', 383, 90000, '(-16.55,-69.0)', 'Cordillera Central', 3812, '(-18.55,-67.1)', 3686);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Loa', '', '', 'Pacific Ocean', 443, 33570, '(-21.07,-68.51)', 'Cordillera Volcanica', 4000, '(-21.43,-70.05)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Bío Bío', '', '', 'Pacific Ocean', 380, 24264, '(-38.69,-71.26)', 'Andes', 1160, '(-36.82,-73.17)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Baker', '', '', 'Pacific Ocean', 170, 26726, '(-47.02,-72.83)', 'Andes', 217, '(-47.79,-73.57)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Río Azopardo', '', '', 'Pacific Ocean', 11, 2910, '(-54.50,-68.81)', '', 140, '(-54.47,-68.98)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sebou', '', '', 'Mediterranean Sea', 450, 40000, '(33.34,-4.56)', 'Atlas', 1800, '(34.26,-6.68)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Moulouya', '', '', 'Mediterranean Sea', 550, 74000, '(32.69,-5.21)', 'Atlas', 1800, '(35.12,-2.34)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chelif', '', '', 'Mediterranean Sea', 700, 43700, '(33.92,1.75)', 'Atlas', 1380, '(36.04,0.13)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rhumel', '', '', 'Mediterranean Sea', 200, 0, '(36.2,5.85)', 'Atlas', 1090, '(36.87,6.1)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Medjerda', '', '', 'Mediterranean Sea', 460, 22000, '(36.32,8.4)', 'Atlas', 0, '(37.0,10.2)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Senegal', '', '', 'Atlantic Ocean', 1430, 337000, '(11.5,-12)', 'Fouta Djallon', 800, '(15.96,-16.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gambia', '', '', 'Atlantic Ocean', 1120, 69931, '(11.4,-12.25)', 'Fouta Djallon', 1030, '(13.5,-16.6)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rio Corubal', '', '', 'Atlantic Ocean', 560, 24000, '(11.32,-12.30)', 'Fouta Djallon', 980, '(11.72,-15.64)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rokel', '', '', 'Atlantic Ocean', 356, 10620, '(9.59,-11.09)', '', 460, '(8.57,-12.96)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Moa', '', '', 'Atlantic Ocean', 475, 19835, '(9.00,-9.55)', '', 930, '(6.98,-11.59)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Saint Paul River', '', '', 'Atlantic Ocean', 485, 20281, '(8.7,-9.18)', '', 960, '(6.38,-10.8)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bandama', '', '', 'Atlantic Ocean', 1050, 98500, '(10.22,-6.00)', '', 0, '(5.14,-5.00)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Comoé', '', '', 'Atlantic Ocean', 813, 82408, '(10.94,-4.48)', '', 0, '(5.19,-3.72)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Volta', '', '', 'Atlantic Ocean', 2850, 398390, '(11.05,-5.32)', '', 580, '(5.77,0.68)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oti', '', 'Lake Volta', '', 937, 72778, '(10.65,1.48)', '', 640, '(8.37,0.12)', 85);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ouémé', '', '', 'Atlantic Ocean', 510, 46990, '(9.86,1.54)', '', 500, '(6.35,2.44)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mono', '', '', 'Atlantic Ocean', 460, 25000, '(9.31,1.49)', '', 420, '(6.30,1.93)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Niger', '', '', 'Atlantic Ocean', 4184, 2261763, '(9.65,-10.87)', '', 490, '(5.32,6.42)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tinkisso', 'Niger', '', '', 570, 19430, '(10.37,-12.1)', 'Fouta Djallon', 0, '(11.35,-9.16)', 341);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bani', 'Niger', '', '', 430, 129400, '(12.60,-6.56)', '', 285, '(14.52,-4.2)', 264);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Baoulé', 'Bani', '', '', 490, 32700, '(9.33,-7.40)', '', 460, '(12.60,-6.56)', 285);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bagoé', 'Bani', '', '', 350, 43500, '(9.58,-7.08)', '', 591, '(12.60,-6.56)', 285);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sirba', 'Niger', '', '', 439, 39138, '(12.62,-0.81)', '', 370, '(13.77,1.66)', 190);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mékrou', 'Niger', '', '', 410, 10500, '(10.05,-1.76)', '', 410, '(12.41,2.82)', 175);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sokoto', 'Niger', '', '', 630, 193000, '(11.47,7.10)', '', 700, '(11.40,4.12)', 150);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kaduna', 'Niger', '', '', 575, 66300, '(9.87,8.87)', '', 1280, '(8.74,5.80)', 56);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Benue', 'Niger', '', '', 1400, 335035, '(7.58,12.58)', '', 1100, '(7.78,6.75)', 35);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Gongola', 'Benue', '', '', 531, 56000, '(9.75,8.87)', '', 1250, '(9.50,12.06)', 140);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Yobe', '', 'Chad Lake', '', 467, 148000, '(12.66,10.63)', '', 350, '(13.68,13.39)', 280);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Hadejia', 'Yobe', '', '', 630, 31650, '(11.51,7.34)', '', 700, '(12.66,10.63)', 350);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jamaare', 'Yobe', '', '', 650, 0, '(9.93,8.89)', '', 1160, '(12.66,10.63)', 350);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mayo Kebbi', 'Benue', '', '', 495, 30000, '(9.11,15.10)', '', 400, '(9.32,13.53)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Logone', 'Schari', '', '', 965, 78000, '(7.43,13.49)', '', 1060, '(12.10,16.47)', 298);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Schari', '', 'Chad Lake', '', 1400, 548747, '(8,21)', '', 0, '(13.2,14.0)', 250);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nile', '', '', 'Mediterranean Sea', 3090, 3254853, '(15.6,32.5)', '', 370, '(31.5,31)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Atbara', 'Nile', '', '', 1120, 112000, '(12.8,37.3)', 'Ethiopian Highlands', 0, '(17.68,33.97)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tekeze', 'Atbara', '', '', 608, 68000, '(12.12,39.12)', 'Ethiopian Highlands', 3400, '(14.34,35.85)', 480);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mareb', '', '', '', 440, 31000, '(15.25,38.91)', 'Ethiopian Highlands', 2250, '(16.14,36.32)', 480);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Blue Nile', 'Nile', '', '', 1783, 325000, '(12.0,37.3)', 'Ethiopian Highlands', 1830, '(15.6,32.5)', 370);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('White Nile', 'Nile', '', '', 950, 1588194, '(9.5,30.45)', '', 390, '(15.6,32.5)', 370);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sobat', 'White Nile', '', '', 740, 225000, '(8.45,33.2)', '', 404, '(9.37,31.55)', 394);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Pibor', 'Sobat', '', '', 320, 10000, '(7,33.5)', '', 0, '(8.45,33.2)', 404);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Baro', 'Sobat', '', '', 306, 41400, '(8.25,34.96)', '', 553, '(8.45,33.2)', 404);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bahr el-Djebel/Albert Nil', '', 'Lake No', '', 1156, 0, '(1.7,30.9)', 'East African Rift', 619, '(9.5,30.45)', 390);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Bahr el-Ghazal', '', 'Lake No', '', 716, 555428, '(5,28.5)', '', 0, '(9.5,30.43)', 390);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Semliki', '', 'Lake Sese Seko/Albertsee', '', 230, 0, '(-0.35,29.6)', 'East African Rift', 920, '(1.7,30.9)', 619);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Victoria Nile', '', 'Lake Sese Seko/Albertsee', '', 480, 0, '(0.43,33)', 'East African Rift', 1134, '(1.7,30.9)', 619);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kagera', '', 'Lake Victoria', '', 400, 60000, '(-2.4,30.8)', 'East African Rift', 1320, '(-0.95,31.8)', 1134);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rukurara-Nyabarongo', 'Kagera', '', '', 350, 0, '(-2.2,29.6)', 'East African Rift', 2428, '(-2.4,30.8)', 1320);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ruvuvu', 'Kagera', '', '', 480, 11840, '(-3.0,29.6)', 'East African Rift', 2240, '(-2.4,30.8)', 1320);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Luvironza', 'Ruvuvu', '', '', 110, 2046, '(-3.9,29.8)', 'East African Rift', 2040, '(-3.35,30.0)', 1410);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Simiyu', '', 'Lake Victoria', '', 180, 10800, '(-3.09,34.09)', 'East African Rift', 1680, '(-2.53,33.42)', 1134);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mara', '', 'Lake Victoria', '', 395, 13325, '(-0.3,36)', 'East African Rift', 2920, '(-1.51,33.93)', 1134);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Nzoia', '', 'Lake Victoria', '', 334, 12903, '(1.02,35.44)', 'East African Rift', 2704, '(0.05,33.95)', 1134);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tana', '', '', 'Indian Ocean', 1000, 126000, '(-0.27,37.22)', 'East African Rift', 2700, '(-2.60,40.34)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Jubba', '', '', 'Indian Ocean', 1658, 497626, '(7,39)', '', 0, '(-0.5,42.7)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Shabelle', 'Jubba', '', '', 1820, 336627, '(7,38.5)', '', 0, '(0.5,42.76)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sanaga', '', '', 'Atlantic Ocean', 918, 132990, '(5.3,13.4)', '', 628, '(3.55,9.65)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ntem', '', '', 'Atlantic Ocean', 460, 31000, '(2.00,12.5)', '', 600, '(2.35,9.82)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Komo', '', '', 'Atlantic Ocean', 260, 5000, '(0.02,11.75)', '', 700, '(0.42,9.41)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ogooué', '', '', 'Atlantic Ocean', 1200, 223856, '(-2.94,13.80)', '', 840, '(-1.02,8.88)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Congo', '', '', 'Atlantic Ocean', 4374, 3700000, '(0.5,25.2)', '', 401, '(-6,12)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Sanga', 'Congo', '', '', 785, 213400, '(3.5,16.05)', '', 379, '(-1.2,16.82)', 289);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kadei', 'Sanga', '', '', 552, 41000, '(5.9,14.55)', '', 1017, '(3.5,16.05)', 379);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mambere', 'Sanga', '', '', 488, 27900, '(6.24,14.72)', '', 1143, '(3.5,16.05)', 379);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ubangi', 'Congo', '', '', 1120, 754830, '(4.1,22.45)', '', 395, '(-0.8,17.7)', 295);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mbomou', 'Ubangi', '', '', 966, 156950, '(5.02,27.45)', '', 725, '(4.1,22.45)', 395);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Uelle', 'Ubangi', '', '', 1130, 135400, '(3.6,28.7)', 'East African Rift', 730, '(4.1,22.45)', 395);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Fimi', 'Kasai', '', '', 200, 140500, '(-2.7,18.2)', '', 0, '(3,16.9)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lukenie', 'Fimi', '', '', 900, 0, '(-6.8,24.5)', '', 0, '(3,16.9)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kasai', 'Congo', '', '', 2153, 881890, '(-10.96,19.3)', 'Bié Plateau', 0, '(3.3,17.4)', 270);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cuango', 'Cuilo', '', '', 1100, 263500, '(-11.5,14.2)', '', 502, '(3.3,17.4)', 298);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cuilo', 'Kasai', '', '', 970, 93250, '(-11.3,14.7)', '', 0, '(3.3,17.4)', 296);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lulua', 'Kasai', '', '', 970, 0, '(-10.99,23.7)', '', 0, '(-5.04,21.11)', 382);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Tshuapa', 'Congo', '', '', 1000, 173800, '(-3,24.5)', '', 0, '(0.05,18.26)', 370);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lomami', 'Congo', '', '', 1450, 103900, '(-8.7,24.7)', '', 1140, '(-0.8,24)', 395);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Aruwimi', 'Congo', '', '', 1287, 116100, '(-11.3,14.7)', '', 0, '(2.5,29.5)', 390);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lukuga', 'Lualaba', '', '', 350, 265000, '(-5.9,29.2)', 'East African Rift', 782, '(-5.64,26.91)', 590);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Ruzizi', '', 'Lake Tanganjika', '', 104, 13385, '(-1.8,29.2)', 'East African Rift', 1462, '(-3.4,29.3)', 782);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Malagarasi', '', 'Lake Tanganjika', '', 475, 130000, '(-3.91,30.26)', 'East African Rift', 1180, '(-5.25,29.8)', 782);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Luvua', 'Lualaba', '', '', 350, 265300, '(-9,28.7)', 'East African Rift', 931, '(-6.74,26.95)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Luapula', '', 'Lake Mweru', '', 740, 173386, '(-11.2,29.7)', '', 1140, '(-9,28.7)', 931);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Chambeshi', 'Luapula', '', '', 500, 44427, '(-9.10,31.52)', 'East African Rift', 1600, '(-11.88,29.80)', 1140);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Rufiji', '', '', 'Indian Ocean', 600, 138800, '(-9.46,34.66)', '', 2080, '(-7.75,39.36)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Zambezi', '', '', 'Indian Ocean', 2574, 1332574, '(-11,24.2)', '', 1500, '(-19,36)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cuando', 'Zambezi', '', '', 1500, 148994, '(-13.00,19.12)', 'Bié Plateau', 1460, '(-17.79,25.26)', 924);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Kafue', 'Zambezi', '', '', 402, 155805, '(-11.62,27.03)', '', 1350, '(-15.94,28.91)', 372);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Luangwa', 'Zambezi', '', '', 806, 159615, '(-9.97,33.35)', 'East African Rift', 2240, '(-15.62,30.42)', 327);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Shire', 'Zambezi', '', '', 402, 150000, '(-14.2,35.2)', 'East African Rift', 474, '(-17.70,35.32)', 27);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cuanza', '', '', 'Atlantic Ocean', 960, 157000, '(-13.82,17.32)', 'Bié Plateau', 1800, '(-9.35,13.15)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cunene', '', '', 'Atlantic Ocean', 1050, 110200, '(-12.76,16.00)', 'Bié Plateau', 1770, '(-17.25,11.75)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Okavango', '', '', '', 1700, 721258, '(-12.71,16.06)', 'Bié Plateau', 1850, '(-18.95,22.5)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Cuito', 'Okavango', '', '', 920, 57470, '(-12.69,18.36)', 'Bié Plateau', 1435, '(-18.02,20.80)', 1041);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Limpopo', '', '', 'Indian Ocean', 1750, 413000, '(-26,28)', '', 1800, '(-25.2,34)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Oranje', '', '', 'Atlantic Ocean', 2160, 973000, '(-28.90,29.02)', 'Drakensberge', 3150, '(-28.53,16.45)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Vaal', 'Oranje', '', '', 1251, 192000, '(-26,30)', 'Drakensberge', 0, '(-29.07,23.63)', 1241);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Mangoky', '', '', 'Indian Ocean', 714, 55750, '(-21.72,47.3)', '', 1080, '(-21.43,43.47)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Murchison River', '', '', 'Indian Ocean', 1131, 82000, '(-25.87,118.87)', '', 521, '(-27.71,114.16)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Roper River', '', '', 'Arafura Sea', 600, 81794, '(-13.87,133.20)', '', 393, '(-14.73,135.39)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Georgina River', '', 'Lake Eyre', '', 2060, 232000, '(-19.69,138.00)', '', 241, '(-27.92,127.7)', -15);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Murray River', '', '', 'Indian Ocean', 2508, 1061469, '(-36.80,148.20)', 'Snowy Mountains', 1430, '(-35.55,138.88)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Darling River', 'Murray River', '', '', 1472, 609283, '(-29.96,146.31)', 'Great Dividing Range', 119, '(-34.11,141.91)', 35);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Barwon River', 'Darling River', '', '', 700, 0, '(-29.96,146.31)', '', 166, '(-28.83,149.10)', 119);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Macintyre River', 'Barwon River', '', '', 470, 49470, '(-29.94,151.60)', 'Great Dividing Range', 1360, '(-29.96,146.31)', 119);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Weir River', 'Barwon River', '', '', 700, 0, '(-27.36,151.01)', 'Great Dividing Range', 358, '(-29.96,146.31)', 119);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Culgoa River', 'Darling River', '', '', 1625, 0, '(-28.24,152.47)', 'Great Dividing Range', 772, '(-29.96,146.31)', 119);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Murrumbidgee River', 'Murray River', '', '', 1579, 166340, '(-35.6,148.6)', 'Snowy Mountains', 1560, '(-34.73,143.22)', 55);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Lachlan River', 'Murrumbidgee River', '', '', 1440, 84700, '(-34.78,149.53)', 'Great Dividing Range', 699, '(-34.37,143.78)', 68);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Molonglo River', 'Murrumbidgee River', '', '', 115, 0, '(-35.67,149.50)', '', 1130, '(-34.24,148.97)', 440);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Eucumbene River', '', 'Lake Jindabyne', '', 83, 0, '(-35.8,148.5)', 'Snowy Mountains', 1380, '(-36.30,148.6)', 915);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Snowy River', '', '', 'Tasman Sea', 403, 15779, '(-36.5,148.3)', 'Snowy Mountains', 0, '(-37.6,148.55)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Waikato River', '', '', 'Tasman Sea', 425, 14260, '(-39.15,175.97)', '', 1400, '(-37.37,174.71)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Whangaehu River', '', '', 'Tasman Sea', 190, 0, '(-39.28,175.56)', '', 2560, '(-40.04,175.10)', 0);

INSERT INTO river (name, river, lake, sea, length, area, source, mountains, sourceelevation, estuary, estuaryelevation) VALUES ('Clutha River', '', '', 'Pacific Ocean', 338, 21960, '(-44.67,169.16)', 'New Zealand Southern Alps', 280, '(-46.34,169.81)', 0);
