CREATE KEYSPACE IF NOT EXISTS mondial WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

USE mondial;



CREATE TABLE IF NOT EXISTS spoken (

    country TEXT,

    language TEXT,

    percentage DECIMAL,

    PRIMARY KEY (country)

);



INSERT INTO spoken (country, language, percentage) VALUES ('AL', 'Albanian', 98.8);

INSERT INTO spoken (country, language, percentage) VALUES ('AL', 'Greek', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('AL', 'Roma', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('AL', 'Aromanian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('AL', 'Macedonian', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GR', 'Greek', 92);

INSERT INTO spoken (country, language, percentage) VALUES ('GR', 'Albanian', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('GR', 'Roma', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('GR', 'Macedonian', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('GR', 'Turkish', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('GR', 'Aromanian', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'Greek', 61);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'Turkish', 24);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'English', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'Romanian', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'Bulgarian', 1.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'Arabic', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CY', 'Filipino', 0.9);

INSERT INTO spoken (country, language, percentage) VALUES ('AD', 'Greek', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('AD', 'English', 40);

INSERT INTO spoken (country, language, percentage) VALUES ('MK', 'Macedonian', 66.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MK', 'Albanian', 25.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MK', 'Turkish', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MK', 'Roma', 1.9);

INSERT INTO spoken (country, language, percentage) VALUES ('MK', 'Serbo-Croatian', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MK', 'Aromanian', 0.35);

INSERT INTO spoken (country, language, percentage) VALUES ('SRB', 'Serbo-Croatian', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('SRB', 'Hungarian', 3.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SRB', 'Roma', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SRB', 'Slovak', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('SRB', 'Aromanian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SRB', 'Bulgarian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('MNE', 'Serbo-Croatian', 86.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MNE', 'Albanian', 5.3);

INSERT INTO spoken (country, language, percentage) VALUES ('MNE', 'Roma', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('KOS', 'Albanian', 94.5);

INSERT INTO spoken (country, language, percentage) VALUES ('KOS', 'Serbo-Croatian', 3.3);

INSERT INTO spoken (country, language, percentage) VALUES ('KOS', 'Roma', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('KOS', 'Turkish', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('AND', 'Catalan', 54.8);

INSERT INTO spoken (country, language, percentage) VALUES ('AND', 'Spanish', 16.1);

INSERT INTO spoken (country, language, percentage) VALUES ('AND', 'Portuguese', 13);

INSERT INTO spoken (country, language, percentage) VALUES ('AND', 'French', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('AND', 'Arabic', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('AND', 'Galician', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'French', 87.2);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Arabic', 3.6);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Berber', 3.4);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Spanish', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Italian', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Portuguese', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Occitan', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Alsatian', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'English', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Vietnamese', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Breton', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Turkish', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Kurdish', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Corsu', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Catalan', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('F', 'Basque', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Spanish', 69);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Catalan', 14.6);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Galician', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Arabic', 2.0);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Romanian', 1.8);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Basque', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Roma', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'Berber', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('E', 'English', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CZ', 'Czech', 95.4);

INSERT INTO spoken (country, language, percentage) VALUES ('CZ', 'Slovak', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SK', 'Slovak', 78.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SK', 'Hungarian', 9.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SK', 'Roma', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('SK', 'Ukrainian', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'German', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Turkish', 1.8);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Arabic', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Ukrainian', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Romanian', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Roma', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Russian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('D', 'Kurdish', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('H', 'Hungarian', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Italian', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Sardu', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Romanian', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Arabic', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Albanian', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'German', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Friulian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Chinese', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'French', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Occitan', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Slovenian', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Roma', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('I', 'Ladin', 0.06);

INSERT INTO spoken (country, language, percentage) VALUES ('CH', 'German', 62.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CH', 'French', 22.9);

INSERT INTO spoken (country, language, percentage) VALUES ('CH', 'Italian', 8.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CH', 'Romansh', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('FL', 'German', 91.5);

INSERT INTO spoken (country, language, percentage) VALUES ('FL', 'Portuguese', 1.9);

INSERT INTO spoken (country, language, percentage) VALUES ('FL', 'Italian', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('FL', 'Turkish', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('FL', 'Albanian', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'German', 92.6);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Serbo-Croatian', 4.2);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Turkish', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Hungarian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Polish', 0.35);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Albanian', 0.35);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Slovenian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('A', 'Arabic', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EST', 'Estonian', 68.5);

INSERT INTO spoken (country, language, percentage) VALUES ('EST', 'Russian', 29.6);

INSERT INTO spoken (country, language, percentage) VALUES ('EST', 'Ukrainian', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('LV', 'Latvian', 56.3);

INSERT INTO spoken (country, language, percentage) VALUES ('LV', 'Russian', 33.8);

INSERT INTO spoken (country, language, percentage) VALUES ('LT', 'Lithuanian', 82);

INSERT INTO spoken (country, language, percentage) VALUES ('LT', 'Russian', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('LT', 'Polish', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BY', 'Russian', 70.2);

INSERT INTO spoken (country, language, percentage) VALUES ('BY', 'Belorussian', 23.4);

INSERT INTO spoken (country, language, percentage) VALUES ('PL', 'Polish', 98.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PL', 'German', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Ukrainian', 67.5);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Russian', 29.6);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Romanian', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Belorussian', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Crimean Tatar', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Bulgarian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Hungarian', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Polish', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('UA', 'Yiddish', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Russian', 83);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Tatar', 3.8);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Ukrainian', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Chuvash', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Bashkir', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Chechen', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Armenian', 0.86);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Avaric', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Mongolian', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Circassian', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Azerbaijani', 0.44);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Dargwa', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Ossetian', 0.38);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Mari', 0.32);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Kazakh', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Yakut', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Ingush', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Lezgian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Erzya', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Buryat', 0.25);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Uzbek', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'German', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Udmurt', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Komi', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Kalmyk', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Evenki', 0.02);

INSERT INTO spoken (country, language, percentage) VALUES ('R', 'Khanty', 0.01);

INSERT INTO spoken (country, language, percentage) VALUES ('B', 'Dutch', 55);

INSERT INTO spoken (country, language, percentage) VALUES ('B', 'French', 39);

INSERT INTO spoken (country, language, percentage) VALUES ('B', 'Arabic', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('B', 'Italian', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('B', 'Turkish', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('B', 'German', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('L', 'Luxembourgish', 55.8);

INSERT INTO spoken (country, language, percentage) VALUES ('L', 'Portuguese', 15.7);

INSERT INTO spoken (country, language, percentage) VALUES ('L', 'French', 12.1);

INSERT INTO spoken (country, language, percentage) VALUES ('L', 'German', 3.1);

INSERT INTO spoken (country, language, percentage) VALUES ('L', 'Italian', 2.9);

INSERT INTO spoken (country, language, percentage) VALUES ('L', 'English', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Dutch', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Frisian', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Malay', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Arabic', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Turkish', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Polish', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Berber', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NL', 'Kurdish', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('SLO', 'Slovenian', 92);

INSERT INTO spoken (country, language, percentage) VALUES ('SLO', 'Serbo-Croatian', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SLO', 'Hungarian', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SLO', 'Albanian', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SLO', 'Italian', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SLO', 'Roma', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('HR', 'Serbo-Croatian', 96.8);

INSERT INTO spoken (country, language, percentage) VALUES ('HR', 'Roma', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('BIH', 'Serbo-Croatian', 98.3);

INSERT INTO spoken (country, language, percentage) VALUES ('BG', 'Bulgarian', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('BG', 'Turkish', 9.1);

INSERT INTO spoken (country, language, percentage) VALUES ('BG', 'Roma', 4.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Romanian', 91);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Hungarian', 6.3);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Roma', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Ukrainian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Turkish', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'German', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Russian', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Crimean Tatar', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RO', 'Aromanian', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('DK', 'Danish', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('DK', 'German', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('IS', 'Icelandic', 93.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IS', 'Lithuanian', 0.43);

INSERT INTO spoken (country, language, percentage) VALUES ('IS', 'English', 0.32);

INSERT INTO spoken (country, language, percentage) VALUES ('IS', 'German', 0.31);

INSERT INTO spoken (country, language, percentage) VALUES ('IS', 'Danish', 0.31);

INSERT INTO spoken (country, language, percentage) VALUES ('FO', 'Faroese', 93.8);

INSERT INTO spoken (country, language, percentage) VALUES ('FO', 'Danish', 3.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'English', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Polish', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Irish', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Lithuanian', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Romanian', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Latvian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Arabic', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Malayalam', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Yoruba', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IRL', 'Igbo', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Finnish', 87.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Swedish', 5.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Russian', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Estonian', 0.9);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Arabic', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Somali', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'English', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SF', 'Sami', 0.05);

INSERT INTO spoken (country, language, percentage) VALUES ('N', 'Norwegian', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('N', 'Sami', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('S', 'Swedish', 82);

INSERT INTO spoken (country, language, percentage) VALUES ('S', 'Arabic', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('S', 'Finnish', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('S', 'Polish', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('S', 'Sami', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MC', 'French', 50);

INSERT INTO spoken (country, language, percentage) VALUES ('MC', 'Italian', 22);

INSERT INTO spoken (country, language, percentage) VALUES ('MC', 'English', 8.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MC', 'German', 4.0);

INSERT INTO spoken (country, language, percentage) VALUES ('MC', 'Russian', 2.0);

INSERT INTO spoken (country, language, percentage) VALUES ('MC', 'Greek', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('V', 'Latin', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('V', 'Italian', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CEU', 'Spanish', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CEU', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CEU', 'Berber', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('MEL', 'Spanish', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('MEL', 'Berber', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('MEL', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RSM', 'Italian', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('M', 'Maltese', 88);

INSERT INTO spoken (country, language, percentage) VALUES ('M', 'Italian', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('M', 'English', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('GBM', 'English', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('MD', 'Romanian', 78.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MD', 'Russian', 14.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MD', 'Gagauz', 2.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MD', 'Ukrainian', 2.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MD', 'Bulgarian', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('MD', 'Roma', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('P', 'Portuguese', 97);

INSERT INTO spoken (country, language, percentage) VALUES ('P', 'Ukrainian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('P', 'Romanian', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SVA', 'Norwegian', 58);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'English', 88);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Scots', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Welsh', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Polish', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Punjabi', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Urdu', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Bengali', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Gujarati', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Arabic', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'French', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Chinese', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Portuguese', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Spanish', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Tamil', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Turkish', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Italian', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Somali', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Lithuanian', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Irish', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('GB', 'Scottish Gaelic', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('GBZ', 'Llanito', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GBZ', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GBZ', 'Spanish', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GBG', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GBJ', 'English', 94.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GBJ', 'Portuguese', 4.6);

INSERT INTO spoken (country, language, percentage) VALUES ('ARM', 'Armenian', 97.9);

INSERT INTO spoken (country, language, percentage) VALUES ('ARM', 'Kurdish', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('ARM', 'Russian', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GE', 'Georgian', 87.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GE', 'Azerbaijani', 6.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GE', 'Armenian', 3.9);

INSERT INTO spoken (country, language, percentage) VALUES ('GE', 'Abkhaz', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GE', 'Ossetian', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GE', 'Russian', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('AZ', 'Azerbaijani', 92.5);

INSERT INTO spoken (country, language, percentage) VALUES ('AZ', 'Lezgian', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('AZ', 'Armenian', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('AZ', 'Russian', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('TR', 'Turkish', 84.5);

INSERT INTO spoken (country, language, percentage) VALUES ('TR', 'Kurdish', 12.0);

INSERT INTO spoken (country, language, percentage) VALUES ('TR', 'Arabic', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('TR', 'Zaza', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('TR', 'Circassian', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('RL', 'Arabic', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('RL', 'Armenian', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('WB', 'Arabic', 83);

INSERT INTO spoken (country, language, percentage) VALUES ('WB', 'Hebrew', 17);

INSERT INTO spoken (country, language, percentage) VALUES ('GAZA', 'Arabic', 99.8);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'Hebrew', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'Arabic', 18);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'Russian', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'German', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'Amharic', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'Persian', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('IL', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SYR', 'Arabic', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('SYR', 'Kurdish', 9);

INSERT INTO spoken (country, language, percentage) VALUES ('SYR', 'Turkish', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('SYR', 'Circassian', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('JOR', 'Arabic', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('JOR', 'Armenian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('JOR', 'Circassian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Arabic', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Hindi', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Indonesian', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Mehri', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Filipino', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Malayalam', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Rohingya', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('SA', 'Urdu', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('BRN', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('Q', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('Q', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Arabic', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Malayalam', 11);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Filipino', 6.1);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Punjabi', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Tamil', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Pashto', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'Sindhi', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('UAE', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('OM', 'Arabic', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('OM', 'Mehri', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('OM', 'Shehri', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('YE', 'Arabic', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('YE', 'Soqotri', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('YE', 'Mehri', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('KWT', 'Arabic', 64);

INSERT INTO spoken (country, language, percentage) VALUES ('KWT', 'Persian', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('IRQ', 'Arabic', 70);

INSERT INTO spoken (country, language, percentage) VALUES ('IRQ', 'Kurdish', 15.5);

INSERT INTO spoken (country, language, percentage) VALUES ('IRQ', 'Turkish', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('IRQ', 'Luri', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Persian', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Azerbaijani', 16);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Kurdish', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Luri', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Turkmen', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Arabic', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Balochi', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Qashqai', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IR', 'Armenian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Dari', 41);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Pashto', 41);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Uzbek', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Turkmen', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Urdu', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Balochi', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Arabic', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('AFG', 'Shugni', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('TM', 'Turkmen', 86);

INSERT INTO spoken (country, language, percentage) VALUES ('TM', 'Russian', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('TM', 'Uzbek', 5.8);

INSERT INTO spoken (country, language, percentage) VALUES ('TM', 'Azerbaijani', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('TM', 'Balochi', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Uzbek', 74.3);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Russian', 14.2);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Dari', 4.4);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Kazakh', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Karakalpak', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Tatar', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Crimean Tatar', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('UZ', 'Uyghur', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('TJ', 'Dari', 84.4);

INSERT INTO spoken (country, language, percentage) VALUES ('TJ', 'Uzbek', 11.9);

INSERT INTO spoken (country, language, percentage) VALUES ('TJ', 'Shugni', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('TJ', 'Kyrgyz', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('TJ', 'Russian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('TJ', 'Tatar', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Kyrgyz', 71.4);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Uzbek', 14.4);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Russian', 9);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Dungan', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Uyghur', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Dari', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Kazakh', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('KG', 'Ukrainian', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Kazakh', 68);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Russian', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Uzbek', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Ukrainian', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Uyghur', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Tatar', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'German', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Dari', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('KZ', 'Dungan', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('MNG', 'Mongolian', 86);

INSERT INTO spoken (country, language, percentage) VALUES ('MNG', 'Oirat', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('MNG', 'Kazakh', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MNG', 'Buryat', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MV', 'Dhivehi', 84);

INSERT INTO spoken (country, language, percentage) VALUES ('MV', 'Bengali', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('MV', 'Filipino', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Punjabi', 50);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Sindhi', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Saraiki', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Pashto', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Urdu', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Balochi', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Brahui', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Gujarati', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Balti', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PK', 'Kashmiri', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Hindi', 37.5);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Bengali', 8.0);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Marathi', 6.9);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Telugu', 6.7);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Tamil', 5.7);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Gujarati', 4.6);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Urdu', 4.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Bhojpuri', 4.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Kannada', 3.6);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Odia', 3.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Malayalam', 2.9);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Punjabi', 2.7);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Magadhi', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Assamese', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Maithili', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Santali', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Kashmiri', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Awadhi', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Gondi', 0.25);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Nepali', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Chin', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Kurukh', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Meitei', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Khasi', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Mundari', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Sindhi', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Pashto', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('IND', 'Bodo', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Nepali', 44.6);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Maithili', 14.7);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Bhojpuri', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Tharu', 5.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Tamang', 5.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Newar', 3.2);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Magar', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Urdu', 2.6);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Awadhi', 1.9);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Sherpa', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Kurukh', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NEP', 'Central Tibetan', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('BHT', 'Nepali', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('BHT', 'Tshangla', 28);

INSERT INTO spoken (country, language, percentage) VALUES ('BHT', 'Dzongkha', 24);

INSERT INTO spoken (country, language, percentage) VALUES ('BHT', 'Kurukh', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BD', 'Bengali', 98.5);

INSERT INTO spoken (country, language, percentage) VALUES ('BD', 'Rohingya', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('BD', 'Santali', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('BD', 'Urdu', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Burmese', 80);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Tai Nuea', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Karen', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Rakhine', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Rohingya', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Jingpo', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Mon', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Lisu', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Chin', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Wa', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Hani', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('MYA', 'Lahu', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CL', 'Sinhala', 74.9);

INSERT INTO spoken (country, language, percentage) VALUES ('CL', 'Tamil', 24.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CL', 'English', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Mandarin', 71);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Hokkien', 6.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Wu', 6.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Cantonese', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Gan', 3.9);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Hakka', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Xiang', 3.0);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Uyghur', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Northern Zhuang', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Southern Zhuang', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Yi', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Mongolian', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Huizhou', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Bouyei', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Hmu', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Hmong', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Amdolese', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Kazakh', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Khams', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Kam', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Hani', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Iu-Mien', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Central Tibetan', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Tujia', 0.05);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Hlai', 0.05);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Tai Nuea', 0.05);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Lisu', 0.05);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Lahu', 0.04);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Wa', 0.03);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Dongxiang', 0.015);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Xibe', 0.014);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Jingpo', 0.01);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Kyrgyz', 0.01);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Salar', 0.01);

INSERT INTO spoken (country, language, percentage) VALUES ('CN', 'Oirat', 0.01);

INSERT INTO spoken (country, language, percentage) VALUES ('RC', 'Hokkien', 70);

INSERT INTO spoken (country, language, percentage) VALUES ('RC', 'Hakka', 16);

INSERT INTO spoken (country, language, percentage) VALUES ('RC', 'Mandarin', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('RC', 'Amis', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RC', 'Paiwan', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('HK', 'Cantonese', 88.9);

INSERT INTO spoken (country, language, percentage) VALUES ('HK', 'English', 4.3);

INSERT INTO spoken (country, language, percentage) VALUES ('HK', 'Hokkien', 3.0);

INSERT INTO spoken (country, language, percentage) VALUES ('HK', 'Mandarin', 1.9);

INSERT INTO spoken (country, language, percentage) VALUES ('MAC', 'Cantonese', 85.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MAC', 'Mandarin', 5.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MAC', 'Tagalog', 3.0);

INSERT INTO spoken (country, language, percentage) VALUES ('MAC', 'Hokkien', 3.0);

INSERT INTO spoken (country, language, percentage) VALUES ('MAC', 'English', 2.8);

INSERT INTO spoken (country, language, percentage) VALUES ('MAC', 'Portuguese', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('KP', 'Korean', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('ROK', 'Korean', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('J', 'Japanese', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('RP', 'Tagalog', 24.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RP', 'Cebuanu', 21.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RP', 'Ilokano', 8.8);

INSERT INTO spoken (country, language, percentage) VALUES ('RP', 'Hiligaynon', 8.4);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Vietnamese', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Tay', 2.0);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Khmer', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Hmong', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Nung', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Iu-Mien', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Jarai', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Bahnar', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Koho', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Rade', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Sedang', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Bouyei', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('VN', 'Cham', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('K', 'Khmer', 96);

INSERT INTO spoken (country, language, percentage) VALUES ('K', 'Cham', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('K', 'Jarai', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('K', 'Kuy', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('K', 'Vietnamese', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Thai', 56.2);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Khmu', 11);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Hmong', 9);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Bru', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'TaOi', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Tai Nuea', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Hani', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Vietnamese', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Kuy', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Iu-Mien', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('LAO', 'Lahu', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Thai', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Khmer', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Malay', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Karen', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Chinese', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Kuy', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Hmong', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Lisu', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Iu-Mien', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Lahu', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('THA', 'Mon', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Malay', 84);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Minangkabau', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Javanese', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Hokkien', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Hakka', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Tamil', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Malayalam', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Rohingya', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Cantonese', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Mandarin', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Teochew Chinese', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Kedayan', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Aslian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('MAL', 'Iban', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('BRU', 'Malay', 65.7);

INSERT INTO spoken (country, language, percentage) VALUES ('BRU', 'Kedayan', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('BRU', 'Chinese', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('SGP', 'English', 36.9);

INSERT INTO spoken (country, language, percentage) VALUES ('SGP', 'Mandarin', 34.9);

INSERT INTO spoken (country, language, percentage) VALUES ('SGP', 'Malay', 10.7);

INSERT INTO spoken (country, language, percentage) VALUES ('SGP', 'Hokkien', 4.0);

INSERT INTO spoken (country, language, percentage) VALUES ('SGP', 'Tamil', 3.3);

INSERT INTO spoken (country, language, percentage) VALUES ('SGP', 'Cantonese', 2.0);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Javanese', 45);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Indonesian', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Sundanese', 16);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Madurese', 5.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Minangkabau', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Acehnese', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Laani', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RI', 'Tetum', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('TL', 'Tetum', 42.6);

INSERT INTO spoken (country, language, percentage) VALUES ('TL', 'Portuguese', 30.8);

INSERT INTO spoken (country, language, percentage) VALUES ('TL', 'Makasae', 10.5);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'Tok Pisin', 50);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'Enga', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'Melpa', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'Kuman', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'Huli', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'Tolai', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('PNG', 'English', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Solomon Pijin', 65);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Kwara-ae', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Are-Are', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Lau', 4.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Cheke-Holo', 2.7);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Roviana', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Bilua', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Äiwoo', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'English', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Kiribati', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SOL', 'Tikopia', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'Bislama', 36.8);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'Lenakel', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'Nakanamanga', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'Uripiv', 3.3);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'West Ambae', 3.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'English', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('VU', 'French', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'French', 70);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Wallisian', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Drehu', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Nengone', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Paici', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Xârâcùù', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Ajie', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Iaai', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'Javanese', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NCL', 'West Uvean', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'English', 72.7);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'Mandarin', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'Arabic', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'Cantonese', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'Vietnamese', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'Italian', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('AUS', 'Greek', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('CX', 'English', 27.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CX', 'Mandarin', 17.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CX', 'Malay', 17.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CX', 'Cantonese', 3.7);

INSERT INTO spoken (country, language, percentage) VALUES ('CX', 'Hokkien', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CX', 'Filipino', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CC', 'Malay', 69.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CC', 'English', 22.3);

INSERT INTO spoken (country, language, percentage) VALUES ('NF', 'English', 67.6);

INSERT INTO spoken (country, language, percentage) VALUES ('NF', 'Norfuk', 23.7);

INSERT INTO spoken (country, language, percentage) VALUES ('NF', 'Fijian', 2.0);

INSERT INTO spoken (country, language, percentage) VALUES ('NF', 'Filipino', 1.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NF', 'Mandarin', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'English', 91.2);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'Maori', 3.9);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'Samoan', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'Chinese', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'French', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'Hindi', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NZ', 'German', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('PAL', 'Palauan', 65.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PAL', 'English', 19.1);

INSERT INTO spoken (country, language, percentage) VALUES ('PAL', 'Filipino', 9.9);

INSERT INTO spoken (country, language, percentage) VALUES ('PAL', 'Chinese', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PAL', 'Carolinian', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MP', 'Filipino', 32.8);

INSERT INTO spoken (country, language, percentage) VALUES ('MP', 'Chamorro', 24.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MP', 'English', 17);

INSERT INTO spoken (country, language, percentage) VALUES ('MP', 'Chinese', 6.8);

INSERT INTO spoken (country, language, percentage) VALUES ('MP', 'Carolinian', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('GU', 'English', 43.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GU', 'Filipino', 21.2);

INSERT INTO spoken (country, language, percentage) VALUES ('GU', 'Chamorro', 17.8);

INSERT INTO spoken (country, language, percentage) VALUES ('GU', 'Chinese', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Chuukese', 45);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Pohnpeian', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Kosraean', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Mortlock', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Yapese', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Ulithian', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('FSM', 'Kapingamarangi', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('MH', 'Marshallese', 98.2);

INSERT INTO spoken (country, language, percentage) VALUES ('NAU', 'Nauruan', 93);

INSERT INTO spoken (country, language, percentage) VALUES ('NAU', 'English', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('NAU', 'Kiribati', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('NAU', 'Chinese', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('KIR', 'Kiribati', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('TUV', 'Tuvaluan', 94);

INSERT INTO spoken (country, language, percentage) VALUES ('TUV', 'Kiribati', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('TOK', 'Tokelauan', 88.1);

INSERT INTO spoken (country, language, percentage) VALUES ('TOK', 'Kiribati', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('WS', 'Samoan', 97.8);

INSERT INTO spoken (country, language, percentage) VALUES ('WS', 'English', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('AS', 'Samoan', 88.6);

INSERT INTO spoken (country, language, percentage) VALUES ('AS', 'English', 3.9);

INSERT INTO spoken (country, language, percentage) VALUES ('AS', 'Tongan', 2.7);

INSERT INTO spoken (country, language, percentage) VALUES ('AS', 'Tagalog', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('WF', 'Wallisian', 59.1);

INSERT INTO spoken (country, language, percentage) VALUES ('WF', 'Futunian', 29.9);

INSERT INTO spoken (country, language, percentage) VALUES ('WF', 'French', 12.7);

INSERT INTO spoken (country, language, percentage) VALUES ('FJI', 'Fijian', 40);

INSERT INTO spoken (country, language, percentage) VALUES ('FJI', 'Fiji Hindi', 35);

INSERT INTO spoken (country, language, percentage) VALUES ('FJI', 'Wayan', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('FJI', 'Kiribati', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('FJI', 'Rotuman', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('TO', 'Tongan', 97);

INSERT INTO spoken (country, language, percentage) VALUES ('TO', 'English', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('NU', 'Niuean', 83);

INSERT INTO spoken (country, language, percentage) VALUES ('NU', 'English', 11);

INSERT INTO spoken (country, language, percentage) VALUES ('CK', 'Cook Islands Maori', 76.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CK', 'English', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('PF', 'French', 73.9);

INSERT INTO spoken (country, language, percentage) VALUES ('PF', 'Tahitian', 20.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PF', 'Marquesan', 2.8);

INSERT INTO spoken (country, language, percentage) VALUES ('PF', 'Tuamotuan', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('PF', 'Chinese', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('PF', 'English', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PN', 'Pitcairn Creole', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('ET', 'Arabic', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('ET', 'Nubian', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('ET', 'Beja', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('LAR', 'Arabic', 92);

INSERT INTO spoken (country, language, percentage) VALUES ('LAR', 'Tebu', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('LAR', 'Berber', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('LAR', 'Tuareg', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('LAR', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('LAR', 'Italian', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('TN', 'Berber', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('TN', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('TN', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('DZ', 'Arabic', 72);

INSERT INTO spoken (country, language, percentage) VALUES ('DZ', 'Berber', 27);

INSERT INTO spoken (country, language, percentage) VALUES ('DZ', 'French', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('DZ', 'Hassaniya Arabic', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('DZ', 'Tuareg', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('MA', 'Arabic', 65);

INSERT INTO spoken (country, language, percentage) VALUES ('MA', 'Berber', 28);

INSERT INTO spoken (country, language, percentage) VALUES ('MA', 'Hassaniya Arabic', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MA', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WSA', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WSA', 'Hassaniya Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WSA', 'Berber', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WSA', 'Spanish', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WSA', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Bambara', 40);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Fulfulde', 14);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Western Maninka', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Senufo', 9.6);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Soninke', 6.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Songhai', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Dogon', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Kita Maninka', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Tuareg', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Bobo', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Hassaniya Arabic', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Bozo', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Mossi', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RMM', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RIM', 'Hassaniya Arabic', 70);

INSERT INTO spoken (country, language, percentage) VALUES ('RIM', 'Fulfulde', 22);

INSERT INTO spoken (country, language, percentage) VALUES ('RIM', 'Wolof', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('RIM', 'Soninke', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RIM', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RIM', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Wolof', 45);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Fulfulde', 22);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Serer', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Mandinka', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Diola', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Soninke', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Hassaniya Arabic', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Balanta', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Manjak', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Bambara', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'Guinea-Bissau Creole', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('SN', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Mandinka', 34);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Fulfulde', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Wolof', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Diola', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Soninke', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Serer', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'Manjak', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WAG', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Guinea-Bissau Creole', 40);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Fulfulde', 16);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Balanta', 14);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Mandinka', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Portuguese', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Manjak', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Papel', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('GUB', 'Soninke', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Fulfulde', 33.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Eastern Maninka', 24.9);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Susu', 21.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Kpelle', 7.8);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Kissi', 6.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Kuranko', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'French', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('RG', 'Loma', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Mende', 29.7);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Temne', 26.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Krio', 18.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Limba', 5.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Kono', 5.1);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Kuranko', 4.0);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Fulfulde', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Susu', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Kissi', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'Mandinka', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('SLE', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Kpelle', 20.3);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Bassa', 13.4);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Grebo', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Dan', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Mano', 7.9);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Klao', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Gola', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Loma', 5.1);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Kissi', 4.8);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Vai', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Eastern Maninka', 3.2);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'English', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('LB', 'Mende', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Mossi', 52);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Fulfulde', 8.4);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Gurma', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Bobo', 4.9);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Gurunsi', 4.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Senufo', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Bissa', 3.7);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Dyula', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Marka', 1.9);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Tuareg', 1.9);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('BF', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Akan', 42.4);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Dyula', 16.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Senufo', 16.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Wee', 11);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Mossi', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Guro', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Dan', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Fulfulde', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Hausa', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Bissa', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'Yoruba', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CI', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Akan', 47.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Dagbani', 16);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Ewe', 13.9);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Gurma', 5.7);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Bissa', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Fulfulde', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Gurunsi', 2.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Hausa', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Yoruba', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Dyula', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Mossi', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'Ibibio', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GH', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Ewe', 46);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Gurunsi', 22);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Gurma', 9.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Yoruba', 6.8);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Adja', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Mossi', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Akan', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'Akebu', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RT', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Fon', 38);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Adja', 15.1);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Yoruba', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Bariba', 9.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Fulfulde', 8.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Gurma', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Bissa', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'Hausa', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('BEN', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Hausa', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Yoruba', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Igbo', 17.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Fulfulde', 7.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Kanuri', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Ibibio', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Tiv', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Anaang', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Arabic', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Ijo', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Igala', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Nupe', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Ebira', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Gbagyi', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Idoma', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Edo', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'Berom', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NGR', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Hausa', 55.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Songhai', 21);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Tuareg', 9.3);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Fulfulde', 8.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Kanuri', 4.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Tebu', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Gurma', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'Arabic', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RN', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Arabic', 40);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Sara', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Kanuri', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Masalit', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Fulfulde', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Tebu', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('TCH', 'Bagirmi', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Arabic', 70);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Beja', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Nubian', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Hausa', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Tigre', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Fur', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Masalit', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'Tebu', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SUD', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'Dinka', 35);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'Nuer', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'Shilluk', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'Bari', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'Azande', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SSD', 'Arabic', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RCA', 'Sango', 35);

INSERT INTO spoken (country, language, percentage) VALUES ('RCA', 'Gbaya', 33);

INSERT INTO spoken (country, language, percentage) VALUES ('RCA', 'Banda', 22);

INSERT INTO spoken (country, language, percentage) VALUES ('RCA', 'Sara', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('RCA', 'Azande', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RCA', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Fulfulde', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Pahuin', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Bamileke', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Bamum', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Basaa', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Duala', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Ibibio', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Kom', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Gbaya', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Arabic', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Maka', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Mafa', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Igbo', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'Kanuri', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CAM', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'Fang', 80);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'Bube', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'Annobonese', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'Ibibio', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'Spanish', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'Portuguese', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GQ', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'French', 36.3);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Fang', 32);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Nzebi', 9);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Teke', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Punu', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Mbete', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Shira', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Kota', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Myene', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('G', 'Hausa', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'Kikongo', 35);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'Lingala', 25);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'Teke', 14);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'Mboshi', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'Mbete', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'Punu', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('RCB', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Lingala', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Tshiluba', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Kinyarwanda', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Kikongo', 8.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Luba', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Azande', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Lugbara', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Chokwe', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Gbaya', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Lunda', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'Swahili', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CGO', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Portuguese', 47);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Umbundu', 23);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Kikongo', 8.2);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Kimbundu', 7.8);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Chokwe', 6.5);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Lunda', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Oshivambo', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('ANG', 'Otshiherero', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Oshivambo', 48.9);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Khoekhoe', 11);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Afrikaans', 10.4);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Otshiherero', 8.6);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Kwangali', 8.5);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Lozi', 4.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'English', 3.4);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'German', 0.9);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'San', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NAM', 'Tswana', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'Tswana', 77.3);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'Kalanga', 7.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'English', 2.8);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'Shona', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'Afrikaans', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'San', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RB', 'Ndebele', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Zulu', 22.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Xhosa', 16.0);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Afrikaans', 13.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'English', 9.6);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Sepedi', 9.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Tswana', 8.0);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Sotho', 7.6);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Tsonga', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Swati', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Venda', 2.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RSA', 'Ndebele', 2.1);

INSERT INTO spoken (country, language, percentage) VALUES ('LS', 'Sesotho', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('SD', 'Swati', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('SD', 'Zulu', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('SD', 'Tsonga', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Makua', 26.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Portuguese', 16.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Tsonga', 8.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Chewa', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Sena', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Lomwe', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Shona', 3.8);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Yao', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('MOC', 'Makonde', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('ZW', 'Shona', 70);

INSERT INTO spoken (country, language, percentage) VALUES ('ZW', 'Ndebele', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('ZW', 'Chewa', 6);

INSERT INTO spoken (country, language, percentage) VALUES ('ZW', 'Zambezi', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('ZW', 'English', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('ZW', 'Xhosa', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Bemba', 33.5);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Chewa', 19.2);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Zambezi', 11.4);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Lozi', 5.7);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Nsenga', 2.9);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Tumbuka', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Luba', 1.8);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'English', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('Z', 'Lunda', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'Chewa', 68);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'Yao', 10.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'Tumbuka', 9.5);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'Sena', 2.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'Lomwe', 2.4);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'chiTonga', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MW', 'English', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Sukuma', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Swahili', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Nyamwezi', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Chaga', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Haya', 4.5);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Gogo', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Makonde', 3.5);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Ha', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Maasai', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Dholuo', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Iraqw', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Zigula', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Yao', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Arabic', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'Mijikenda', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAT', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('BI', 'Kirundi', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('BI', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('BI', 'Swahili', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RWA', 'Kinyarwanda', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('RWA', 'Swahili', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RWA', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Ganda', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Dholuo', 10.5);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Nkore', 9.4);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Soga', 8.7);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Kiga', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Ateso', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Gisu', 4.9);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Lugbara', 3.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Kinyarwanda', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Karamojong', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Bari', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'Swahili', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('EAU', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Kikuyu', 17);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Luhya', 14);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Kalenjin', 13);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Kamba', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Dholuo', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Somali', 6.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Kisii', 5.7);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Mijikenda', 5.1);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Meru', 5.0);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Turkana', 2.6);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Maasai', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Oromo', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'Swahili', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('EAK', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SO', 'Somali', 97);

INSERT INTO spoken (country, language, percentage) VALUES ('SO', 'Bravanese Swahili', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('SO', 'Zigula', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SO', 'Arabic', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SO', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SO', 'Italian', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('DJI', 'Somali', 55);

INSERT INTO spoken (country, language, percentage) VALUES ('DJI', 'Afar', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('DJI', 'Arabic', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('DJI', 'French', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Oromo', 33.8);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Amharic', 29.3);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Somali', 6.3);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Tigrinya', 5.9);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Sidamo', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Welaita', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Hadiya', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Afar', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'Nuer', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('ETH', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('ER', 'Tigrinya', 55);

INSERT INTO spoken (country, language, percentage) VALUES ('ER', 'Tigre', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('ER', 'Afar', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('ER', 'Beja', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('ER', 'Kunama', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('ER', 'Arabic', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('CV', 'Krioulo', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('STP', 'Portuguese', 55);

INSERT INTO spoken (country, language, percentage) VALUES ('STP', 'Forro', 36);

INSERT INTO spoken (country, language, percentage) VALUES ('STP', 'Krioulo', 8.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SY', 'Seychellois Creole', 87);

INSERT INTO spoken (country, language, percentage) VALUES ('SY', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SY', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('COM', 'Comorian', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('MYT', 'Comorian', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('MYT', 'French', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('MYT', 'Arabic', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('RM', 'Malagasy', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('MS', 'Mauritian Creole', 87);

INSERT INTO spoken (country, language, percentage) VALUES ('MS', 'Bhojpuri', 5.3);

INSERT INTO spoken (country, language, percentage) VALUES ('MS', 'French', 4.1);

INSERT INTO spoken (country, language, percentage) VALUES ('MS', 'Tamil', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('MS', 'English', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('RE', 'Reunion Creole', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('RE', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('HELX', 'English', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('GL', 'Kalaallisut', 80);

INSERT INTO spoken (country, language, percentage) VALUES ('GL', 'Danish', 12);

INSERT INTO spoken (country, language, percentage) VALUES ('GL', 'Tunumiit', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('SPM', 'French', 100);

INSERT INTO spoken (country, language, percentage) VALUES ('BM', 'English', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('BM', 'Portuguese', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'English', 67.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'French', 21.5);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Mandarin', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Cantonese', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Punjabi', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Spanish', 1.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Filipino', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Arabic', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'German', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Italian', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Persian', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Urdu', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Hindi', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Gujarati', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Ukrainian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Cree', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Tamil', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Malayalam', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Bengali', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Inuktitut', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Ojibwe', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CDN', 'Dakota', 0.06);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'English', 78.2);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Spanish', 13.4);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Chinese', 1.1);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Tagalog', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Vietnamese', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Arabic', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'French', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Korean', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Russian', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'German', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Hindi', 0.25);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Portuguese', 0.25);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Italian', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Polish', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Urdu', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Yiddish', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Japanese', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Persian', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Gujarati', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Telugu', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Bengali', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Thai', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Navajo', 0.05);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Hawaiian', 0.007);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Cherokee', 0.006);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Dakota', 0.005);

INSERT INTO spoken (country, language, percentage) VALUES ('USA', 'Yupik', 0.004);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Spanish', 92.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Nahuatl', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Yucatec', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Mixtec', 0.48);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Zapotec', 0.45);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Tzeltal', 0.44);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Tzotzil', 0.40);

INSERT INTO spoken (country, language, percentage) VALUES ('MEX', 'Otomi', 0.30);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'Spanish', 43);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'Belize Creole', 37);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'English', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'Qeqchi', 5.0);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'Garifuna', 4.0);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'Mopan', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'German', 2.3);

INSERT INTO spoken (country, language, percentage) VALUES ('BZ', 'Yucatec', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Spanish', 69.9);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Kiche', 7.8);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Qeqchi', 7.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Kaqchikel', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Mam', 4.4);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Qanjobal', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Poqomchi', 1.0);

INSERT INTO spoken (country, language, percentage) VALUES ('GCA', 'Garifuna', 0.15);

INSERT INTO spoken (country, language, percentage) VALUES ('ES', 'Spanish', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('HN', 'Spanish', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('HN', 'Miskito', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('HN', 'Garifuna', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('NIC', 'Spanish', 95.3);

INSERT INTO spoken (country, language, percentage) VALUES ('NIC', 'Miskito', 2.2);

INSERT INTO spoken (country, language, percentage) VALUES ('NIC', 'Miskito Coast Creole', 2.0);

INSERT INTO spoken (country, language, percentage) VALUES ('NIC', 'Garifuna', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CR', 'Spanish', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('CR', 'Cabecar', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CR', 'Ngäbere', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('CR', 'Bribri', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('PA', 'Spanish', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('PA', 'Ngäbere', 6.5);

INSERT INTO spoken (country, language, percentage) VALUES ('PA', 'Kuna', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('PA', 'Embera', 0.9);

INSERT INTO spoken (country, language, percentage) VALUES ('PA', 'Buglere', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('BS', 'English', 75);

INSERT INTO spoken (country, language, percentage) VALUES ('BS', 'Bahamian Creole', 25);

INSERT INTO spoken (country, language, percentage) VALUES ('TUCA', 'Turks and Caicos Creole', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('TUCA', 'English', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('TUCA', 'Spanish', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('CYM', 'English', 90.9);

INSERT INTO spoken (country, language, percentage) VALUES ('CYM', 'Spanish', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('CYM', 'Filipino', 3.3);

INSERT INTO spoken (country, language, percentage) VALUES ('C', 'Spanish', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('C', 'Haitian Creole', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('JA', 'Jamaican Patois', 75);

INSERT INTO spoken (country, language, percentage) VALUES ('JA', 'English', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('RH', 'Haitian Creole', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('RH', 'French', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('DOM', 'Spanish', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('DOM', 'Haitian Creole', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('PR', 'Spanish', 94.3);

INSERT INTO spoken (country, language, percentage) VALUES ('PR', 'English', 5.5);

INSERT INTO spoken (country, language, percentage) VALUES ('PR', 'French', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VIRG', 'English', 71.6);

INSERT INTO spoken (country, language, percentage) VALUES ('VIRG', 'Spanish', 17.2);

INSERT INTO spoken (country, language, percentage) VALUES ('VIRG', 'French', 8.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BVI', 'English', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('BVI', 'Spanish', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('AXA', 'English', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('AXA', 'Spanish', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('SMAR', 'English', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('SMAR', 'Haitian Creole', 8);

INSERT INTO spoken (country, language, percentage) VALUES ('SMAR', 'French', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('SMAR', 'Antillean Creole', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('SX', 'English', 67.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SX', 'Spanish', 12.9);

INSERT INTO spoken (country, language, percentage) VALUES ('SX', 'Antillean Creole', 8.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SX', 'French', 6.6);

INSERT INTO spoken (country, language, percentage) VALUES ('SX', 'Dutch', 4.2);

INSERT INTO spoken (country, language, percentage) VALUES ('SX', 'Papiamento', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('SBAR', 'French', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('SBAR', 'Portuguese', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('KN', 'St. Kitts Creole English', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('AG', 'Antiguan Creole', 90);

INSERT INTO spoken (country, language, percentage) VALUES ('AG', 'English', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('AG', 'Spanish', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('MNTS', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GP', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('GP', 'Antillean Creole', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WD', 'Antillean Creole', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('WD', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('MQ', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('MQ', 'Antillean Creole', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WL', 'Antillean Creole', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('WL', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('BDS', 'Bajan', 95);

INSERT INTO spoken (country, language, percentage) VALUES ('BDS', 'English', 0.4);

INSERT INTO spoken (country, language, percentage) VALUES ('WV', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WV', 'Vincentian Creole', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WV', 'Antillean Creole', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('WG', 'Grenadian Creole English', 89);

INSERT INTO spoken (country, language, percentage) VALUES ('WG', 'Antillean Creole', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('WG', 'English', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('TT', 'Trinidadian Creole', 75);

INSERT INTO spoken (country, language, percentage) VALUES ('TT', 'Tobagonian Creole', 20);

INSERT INTO spoken (country, language, percentage) VALUES ('TT', 'Caribbean Hindustani', 1.2);

INSERT INTO spoken (country, language, percentage) VALUES ('TT', 'Hindi', 0.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NLB', 'Papiamento', 75);

INSERT INTO spoken (country, language, percentage) VALUES ('NLB', 'Spanish', 11.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NLB', 'Dutch', 8.8);

INSERT INTO spoken (country, language, percentage) VALUES ('NLB', 'English', 2.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CUR', 'Papiamento', 79.9);

INSERT INTO spoken (country, language, percentage) VALUES ('CUR', 'Dutch', 8.8);

INSERT INTO spoken (country, language, percentage) VALUES ('CUR', 'Spanish', 5.6);

INSERT INTO spoken (country, language, percentage) VALUES ('CUR', 'English', 3.1);

INSERT INTO spoken (country, language, percentage) VALUES ('ARU', 'Papiamento', 69.4);

INSERT INTO spoken (country, language, percentage) VALUES ('ARU', 'Spanish', 13.7);

INSERT INTO spoken (country, language, percentage) VALUES ('ARU', 'English', 7.1);

INSERT INTO spoken (country, language, percentage) VALUES ('ARU', 'Dutch', 6.1);

INSERT INTO spoken (country, language, percentage) VALUES ('ARU', 'Chinese', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('YV', 'Spanish', 97);

INSERT INTO spoken (country, language, percentage) VALUES ('YV', 'Chinese', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('YV', 'Wayuu', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('GUY', 'Guyanese Creole', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('GUY', 'Caribbean Hindustani', 5);

INSERT INTO spoken (country, language, percentage) VALUES ('GUY', 'Kapong', 3);

INSERT INTO spoken (country, language, percentage) VALUES ('GUY', 'Wapishana', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('GUY', 'Macushi', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Dutch', 50);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Sranantongo', 15);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Saramaccan', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Caribbean Hindustani', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Ndyuka', 7);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Javanese', 4);

INSERT INTO spoken (country, language, percentage) VALUES ('SME', 'Carib', 0.5);

INSERT INTO spoken (country, language, percentage) VALUES ('GF', 'French Guianese Creole', 85);

INSERT INTO spoken (country, language, percentage) VALUES ('GF', 'Saramaccan', 10);

INSERT INTO spoken (country, language, percentage) VALUES ('GF', 'Carib', 1.4);

INSERT INTO spoken (country, language, percentage) VALUES ('GF', 'French', 0);

INSERT INTO spoken (country, language, percentage) VALUES ('CO', 'Spanish', 99.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CO', 'Wayuu', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CO', 'Paez', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('CO', 'Embera', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('EC', 'Spanish', 93);

INSERT INTO spoken (country, language, percentage) VALUES ('EC', 'Quechua', 4.1);

INSERT INTO spoken (country, language, percentage) VALUES ('EC', 'Shuar', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('PE', 'Spanish', 82.6);

INSERT INTO spoken (country, language, percentage) VALUES ('PE', 'Quechua', 13.9);

INSERT INTO spoken (country, language, percentage) VALUES ('PE', 'Aymara', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('PE', 'Ashaninka', 0.3);

INSERT INTO spoken (country, language, percentage) VALUES ('PE', 'Aguaruna', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'Spanish', 60.7);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'Quechua', 21.2);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'Aymara', 14.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'German', 1.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'Guarani', 0.7);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'Portuguese', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('BOL', 'Moxo', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RCH', 'Spanish', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('RCH', 'Mapuche', 1.7);

INSERT INTO spoken (country, language, percentage) VALUES ('RCH', 'German', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RCH', 'Aymara', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RCH', 'Quechua', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Spanish', 94);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Arabic', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Guarani', 2);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'German', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Quechua', 0.2);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Mapuche', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Wichi', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Aymara', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('RA', 'Toba', 0.1);

INSERT INTO spoken (country, language, percentage) VALUES ('PY', 'Guarani', 60);

INSERT INTO spoken (country, language, percentage) VALUES ('PY', 'Spanish', 30);

INSERT INTO spoken (country, language, percentage) VALUES ('PY', 'German', 2.5);

INSERT INTO spoken (country, language, percentage) VALUES ('ROU', 'Spanish', 99);

INSERT INTO spoken (country, language, percentage) VALUES ('ROU', 'German', 1);

INSERT INTO spoken (country, language, percentage) VALUES ('ROU', 'Portuguese', 0.6);

INSERT INTO spoken (country, language, percentage) VALUES ('BR', 'Portuguese', 98);

INSERT INTO spoken (country, language, percentage) VALUES ('BR', 'German', 1.5);

INSERT INTO spoken (country, language, percentage) VALUES ('BR', 'Guarani', 0.025);

INSERT INTO spoken (country, language, percentage) VALUES ('FALK', 'English', 100);
